In [1]:
!pip install ipykernel

Requirement already satisfied: ipykernel in .\git\.venv\Lib\site-packages (7.2.0)
Requirement already satisfied: comm>=0.1.1 in .\git\.venv\Lib\site-packages (from ipykernel) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in .\git\.venv\Lib\site-packages (from ipykernel) (1.8.20)
Requirement already satisfied: ipython>=7.23.1 in .\git\.venv\Lib\site-packages (from ipykernel) (9.13.0)
Requirement already satisfied: jupyter-client>=8.8.0 in .\git\.venv\Lib\site-packages (from ipykernel) (8.8.0)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in .\git\.venv\Lib\site-packages (from ipykernel) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in .\git\.venv\Lib\site-packages (from ipykernel) (0.2.2)
Requirement already satisfied: nest-asyncio>=1.4 in .\git\.venv\Lib\site-packages (from ipykernel) (1.6.0)
Requirement already satisfied: packaging>=22 in .\git\.venv\Lib\site-packages (from ipykernel) (26.1)
Requirement already satisfied: psutil>=5.7 in .\git\.venv\Lib\site-packages (from ipykernel) (7.2.2)
Requirement already satisfied: pyzmq>=25 in .\git\.venv\Lib\site-packages (from ipykernel) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in .\git\.venv\Lib\site-packages (from ipykernel) (6.5.5)
Requirement already satisfied: traitlets>=5.4.0 in .\git\.venv\Lib\site-packages (from ipykernel) (5.15.0)
Requirement already satisfied: colorama>=0.4.4 in .\git\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in .\git\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in .\git\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in .\git\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.20.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in .\git\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in .\git\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in .\git\.venv\Lib\site-packages (from ipython>=7.23.1->ipykernel) (0.6.3)
Requirement already satisfied: wcwidth in .\git\.venv\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel) (0.7.0)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in .\git\.venv\Lib\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel) (0.8.7)
Requirement already satisfied: python-dateutil>=2.8.2 in .\git\.venv\Lib\site-packages (from jupyter-client>=8.8.0->ipykernel) (2.9.0.post0)
Requirement already satisfied: platformdirs>=2.5 in .\git\.venv\Lib\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel) (4.9.6)
Requirement already satisfied: six>=1.5 in .\git\.venv\Lib\site-packages (from python-dateutil>=2.8.2->jupyter-client>=8.8.0->ipykernel) (1.17.0)
Requirement already satisfied: executing>=1.2.0 in .\git\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in .\git\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (3.0.1)
Requirement already satisfied: pure-eval in .\git\.venv\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel) (0.2.3)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
!pip install torch torchvision --index-url https://download.pytorch.org/whl/cu128

Looking in indexes: https://download.pytorch.org/whl/cu128
Requirement already satisfied: torch in .\git\.venv\Lib\site-packages (2.11.0+cu128)
Requirement already satisfied: torchvision in .\git\.venv\Lib\site-packages (0.26.0+cu128)
Requirement already satisfied: filelock in .\git\.venv\Lib\site-packages (from torch) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in .\git\.venv\Lib\site-packages (from torch) (4.15.0)
Requirement already satisfied: setuptools<82 in .\git\.venv\Lib\site-packages (from torch) (70.2.0)
Requirement already satisfied: sympy>=1.13.3 in .\git\.venv\Lib\site-packages (from torch) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in .\git\.venv\Lib\site-packages (from torch) (3.6.1)
Requirement already satisfied: jinja2 in .\git\.venv\Lib\site-packages (from torch) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in .\git\.venv\Lib\site-packages (from torch) (2026.4.0)
Requirement already satisfied: numpy in .\git\.venv\Lib\site-packages (from torchvision) (2.4.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in .\git\.venv\Lib\site-packages (from torchvision) (12.2.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in .\git\.venv\Lib\site-packages (from sympy>=1.13.3->torch) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in .\git\.venv\Lib\site-packages (from jinja2->torch) (3.0.3)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [3]:
# !pip install roboflow

In [3]:
!pip install opencv-python --upgrade

Requirement already satisfied: opencv-python in .\git\.venv\Lib\site-packages (4.13.0.92)
Requirement already satisfied: numpy>=2 in .\git\.venv\Lib\site-packages (from opencv-python) (2.4.4)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
print("Hello World!")

Hello World!

In [5]:
import torch

# 1. Check if CUDA is available
print(f"CUDA available: {torch.cuda.is_available()}")

# 2. Get the name of the active GPU
if torch.cuda.is_available():
    print(f"GPU Name: {torch.cuda.get_device_name(0)}")
    print(f"CUDA Version: {torch.version.cuda}")

CUDA available: True
GPU Name: NVIDIA GeForce RTX 5070 Laptop GPU
CUDA Version: 12.8

In [6]:
import numpy as np
import pandas as pd

In [7]:
!pip install matplotlib --upgrade

Requirement already satisfied: matplotlib in .\git\.venv\Lib\site-packages (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in .\git\.venv\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\git\.venv\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\git\.venv\Lib\site-packages (from matplotlib) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in .\git\.venv\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: numpy>=1.25 in .\git\.venv\Lib\site-packages (from matplotlib) (2.4.4)
Requirement already satisfied: packaging>=20.0 in .\git\.venv\Lib\site-packages (from matplotlib) (26.1)
Requirement already satisfied: pillow>=9 in .\git\.venv\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in .\git\.venv\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in .\git\.venv\Lib\site-packages (from matplotlib) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in .\git\.venv\Lib\site-packages (from python-dateutil>=2.7->matplotlib) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [8]:
!pip install -U ultralytics

Requirement already satisfied: ultralytics in .\git\.venv\Lib\site-packages (8.4.66)
Collecting ultralytics
  Downloading ultralytics-8.4.72-py3-none-any.whl.metadata (41 kB)
Requirement already satisfied: numpy>=1.23.0 in .\git\.venv\Lib\site-packages (from ultralytics) (2.4.4)
Requirement already satisfied: matplotlib>=3.3.0 in .\git\.venv\Lib\site-packages (from ultralytics) (3.11.0)
Requirement already satisfied: opencv-python>=4.6.0 in .\git\.venv\Lib\site-packages (from ultralytics) (4.13.0.92)
Requirement already satisfied: pillow>=7.1.2 in .\git\.venv\Lib\site-packages (from ultralytics) (12.2.0)
Requirement already satisfied: pyyaml>=5.3.1 in .\git\.venv\Lib\site-packages (from ultralytics) (6.0.3)
Requirement already satisfied: requests>=2.23.0 in .\git\.venv\Lib\site-packages (from ultralytics) (2.33.1)
Requirement already satisfied: scipy>=1.4.1 in .\git\.venv\Lib\site-packages (from ultralytics) (1.17.1)
Requirement already satisfied: torch>=1.8.0 in .\git\.venv\Lib\site-packages (from ultralytics) (2.11.0+cu128)
Requirement already satisfied: torchvision>=0.9.0 in .\git\.venv\Lib\site-packages (from ultralytics) (0.26.0+cu128)
Requirement already satisfied: psutil>=5.8.0 in .\git\.venv\Lib\site-packages (from ultralytics) (7.2.2)
Requirement already satisfied: polars>=0.20.0 in .\git\.venv\Lib\site-packages (from ultralytics) (1.40.1)
Requirement already satisfied: nvidia-ml-py>=12.0.0 in .\git\.venv\Lib\site-packages (from ultralytics) (13.610.43)
Requirement already satisfied: ultralytics-thop>=2.0.18 in .\git\.venv\Lib\site-packages (from ultralytics) (2.0.19)
Requirement already satisfied: contourpy>=1.0.1 in .\git\.venv\Lib\site-packages (from matplotlib>=3.3.0->ultralytics) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\git\.venv\Lib\site-packages (from matplotlib>=3.3.0->ultralytics) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\git\.venv\Lib\site-packages (from matplotlib>=3.3.0->ultralytics) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in .\git\.venv\Lib\site-packages (from matplotlib>=3.3.0->ultralytics) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\git\.venv\Lib\site-packages (from matplotlib>=3.3.0->ultralytics) (26.1)
Requirement already satisfied: pyparsing>=3 in .\git\.venv\Lib\site-packages (from matplotlib>=3.3.0->ultralytics) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in .\git\.venv\Lib\site-packages (from matplotlib>=3.3.0->ultralytics) (2.9.0.post0)
Requirement already satisfied: polars-runtime-32==1.40.1 in .\git\.venv\Lib\site-packages (from polars>=0.20.0->ultralytics) (1.40.1)
Requirement already satisfied: six>=1.5 in .\git\.venv\Lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\git\.venv\Lib\site-packages (from requests>=2.23.0->ultralytics) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in .\git\.venv\Lib\site-packages (from requests>=2.23.0->ultralytics) (3.7)
Requirement already satisfied: urllib3<3,>=1.26 in .\git\.venv\Lib\site-packages (from requests>=2.23.0->ultralytics) (2.6.3)
Requirement already satisfied: certifi>=2023.5.7 in .\git\.venv\Lib\site-packages (from requests>=2.23.0->ultralytics) (2026.4.22)
Requirement already satisfied: filelock in .\git\.venv\Lib\site-packages (from torch>=1.8.0->ultralytics) (3.29.0)
Requirement already satisfied: typing-extensions>=4.10.0 in .\git\.venv\Lib\site-packages (from torch>=1.8.0->ultralytics) (4.15.0)
Requirement already satisfied: setuptools<82 in .\git\.venv\Lib\site-packages (from torch>=1.8.0->ultralytics) (70.2.0)
Requirement already satisfied: sympy>=1.13.3 in .\git\.venv\Lib\site-packages (from torch>=1.8.0->ultralytics) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in .\git\.venv\Lib\site-packages (from torch>=1.8.0->ultralytics) (3.6.1)
Requirement already satisfied: jinja2 in .\git\.venv\Lib\site-packages (from torch>=1.8.0->ultralytics) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in .\git\.venv\Lib\site-packages (from torch>=1.8.0->ultralytics) (2026.4.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in .\git\.venv\Lib\site-packages (from sympy>=1.13.3->torch>=1.8.0->ultralytics) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in .\git\.venv\Lib\site-packages (from jinja2->torch>=1.8.0->ultralytics) (3.0.3)
Downloading ultralytics-8.4.72-py3-none-any.whl (1.3 MB)
   ---------------------------------------- 0.0/1.3 MB ? eta -:--:--
   ------- -------------------------------- 0.3/1.3 MB ? eta -:--:--
   ----------------------- ---------------- 0.8/1.3 MB 2.7 MB/s eta 0:00:01
   ---------------------------------------- 1.3/1.3 MB 2.9 MB/s  0:00:00
Installing collected packages: ultralytics
  Attempting uninstall: ultralytics
    Found existing installation: ultralytics 8.4.66
    Uninstalling ultralytics-8.4.66:
      Successfully uninstalled ultralytics-8.4.66
Successfully installed ultralytics-8.4.72

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="сюда вставить ключ")
project = rf.workspace("yolo-eg7ka").project("detecting-cars-and-pedestrians")
version = project.version(1)
dataset = version.download("yolo26")

Requirement already satisfied: roboflow in .\git\.venv\Lib\site-packages (1.3.9)
Requirement already satisfied: certifi in .\git\.venv\Lib\site-packages (from roboflow) (2026.4.22)
Requirement already satisfied: idna==3.7 in .\git\.venv\Lib\site-packages (from roboflow) (3.7)
Requirement already satisfied: cycler in .\git\.venv\Lib\site-packages (from roboflow) (0.12.1)
Requirement already satisfied: kiwisolver>=1.3.1 in .\git\.venv\Lib\site-packages (from roboflow) (1.5.0)
Requirement already satisfied: matplotlib in .\git\.venv\Lib\site-packages (from roboflow) (3.10.9)
Requirement already satisfied: numpy>=1.18.5 in .\git\.venv\Lib\site-packages (from roboflow) (2.4.4)
Requirement already satisfied: opencv-python-headless==4.10.0.84 in .\git\.venv\Lib\site-packages (from roboflow) (4.10.0.84)
Requirement already satisfied: Pillow>=7.1.2 in .\git\.venv\Lib\site-packages (from roboflow) (12.2.0)
Requirement already satisfied: pi-heif<2 in .\git\.venv\Lib\site-packages (from roboflow) (1.3.0)
Requirement already satisfied: pillow-avif-plugin<2 in .\git\.venv\Lib\site-packages (from roboflow) (1.5.5)
Requirement already satisfied: python-dateutil in .\git\.venv\Lib\site-packages (from roboflow) (2.9.0.post0)
Requirement already satisfied: python-dotenv in .\git\.venv\Lib\site-packages (from roboflow) (1.2.2)
Requirement already satisfied: requests in .\git\.venv\Lib\site-packages (from roboflow) (2.33.1)
Requirement already satisfied: six in .\git\.venv\Lib\site-packages (from roboflow) (1.17.0)
Requirement already satisfied: urllib3>=1.26.6 in .\git\.venv\Lib\site-packages (from roboflow) (2.6.3)
Requirement already satisfied: tqdm>=4.41.0 in .\git\.venv\Lib\site-packages (from roboflow) (4.67.3)
Requirement already satisfied: PyYAML>=5.3.1 in .\git\.venv\Lib\site-packages (from roboflow) (6.0.3)
Requirement already satisfied: requests_toolbelt in .\git\.venv\Lib\site-packages (from roboflow) (1.0.0)
Requirement already satisfied: filetype in .\git\.venv\Lib\site-packages (from roboflow) (1.2.0)
Requirement already satisfied: typer<0.26,>=0.12.0 in .\git\.venv\Lib\site-packages (from roboflow) (0.25.1)
Requirement already satisfied: click>=8.0 in .\git\.venv\Lib\site-packages (from roboflow) (8.4.1)
Requirement already satisfied: shellingham>=1.3.0 in .\git\.venv\Lib\site-packages (from typer<0.26,>=0.12.0->roboflow) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in .\git\.venv\Lib\site-packages (from typer<0.26,>=0.12.0->roboflow) (15.0.0)
Requirement already satisfied: annotated-doc>=0.0.2 in .\git\.venv\Lib\site-packages (from typer<0.26,>=0.12.0->roboflow) (0.0.4)
Requirement already satisfied: colorama in .\git\.venv\Lib\site-packages (from click>=8.0->roboflow) (0.4.6)
Requirement already satisfied: markdown-it-py>=2.2.0 in .\git\.venv\Lib\site-packages (from rich>=13.8.0->typer<0.26,>=0.12.0->roboflow) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in .\git\.venv\Lib\site-packages (from rich>=13.8.0->typer<0.26,>=0.12.0->roboflow) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in .\git\.venv\Lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<0.26,>=0.12.0->roboflow) (0.1.2)
Requirement already satisfied: contourpy>=1.0.1 in .\git\.venv\Lib\site-packages (from matplotlib->roboflow) (1.3.3)
Requirement already satisfied: fonttools>=4.22.0 in .\git\.venv\Lib\site-packages (from matplotlib->roboflow) (4.62.1)
Requirement already satisfied: packaging>=20.0 in .\git\.venv\Lib\site-packages (from matplotlib->roboflow) (26.1)
Requirement already satisfied: pyparsing>=3 in .\git\.venv\Lib\site-packages (from matplotlib->roboflow) (3.3.2)
Requirement already satisfied: charset_normalizer<4,>=2 in .\git\.venv\Lib\site-packages (from requests->roboflow) (3.4.7)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

loading Roboflow workspace...
loading Roboflow project...

In [11]:

# from roboflow import Roboflow
# rf = Roboflow(api_key="сюда вставить ключ roboflow")
# project = rf.workspace("yolo-zad4").project("trafficlight-mmhsv")
# version = project.version(1)
# dataset = version.download("yolov8")

In [9]:
from ultralytics import YOLO
model = YOLO("yolo26l-seg.pt")

In [10]:
torch.cuda.empty_cache()

In [11]:
imgSize = 640

In [15]:
# import os

# label_dir = 'kitti/labels/val/'
# empty_files = []

# for file in os.listdir(label_dir):
#     if file.endswith('.txt'):
#         path = os.path.join(label_dir, file)
#         # Check if file is empty or only contains whitespace
#         if os.path.getsize(path) == 0 or len(open(path).read().strip()) == 0:
#             empty_files.append(file)

# print(f"Found {len(empty_files)} empty label files.")
# print(empty_files)

In [16]:
# trained_model = model.train(data='Detecting-cars-and-pedestrians-1/data.yaml', batch=4, epochs=100, imgsz=imgSize)

In [12]:
# Train the model - fast
# trained_model = model.train(data="coco8-seg.yaml", epochs=1, imgsz=imgSize,  patience=20)
trained_model = model.train(data="coco8-seg.yaml", epochs=10, imgsz=imgSize,  patience=20)
# trained_model = model.train(data="coco8-seg.yaml", epochs=100, imgsz=imgSize,  patience=20)
# Train the model
# trained_model = model.train(data="coco.yaml", epochs=100, imgsz=320, cache=False, batch=8, optimizer="AdamW", patience=10 )

Ultralytics 8.4.72  Python-3.14.4 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 5070 Laptop GPU, 8151MiB)
engine\trainer: agnostic_nms=False, amp=True, angle=1.0, augment=False, auto_augment=randaugment, batch=16, bgr=0.0, box=7.5, cache=False, cfg=None, classes=None, close_mosaic=10, cls=0.5, cls_pw=0.0, compile=False, conf=None, copy_paste=0.0, copy_paste_mode=flip, cos_lr=False, cutmix=0.0, data=coco8-seg.yaml, degrees=0.0, deterministic=True, device=None, dfl=1.5, dnn=False, dropout=0.0, dynamic=False, embed=None, end2end=None, epochs=10, erasing=0.4, exist_ok=False, fliplr=0.5, flipud=0.0, format=torchscript, fraction=1.0, freeze=None, half=False, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, imgsz=640, int8=False, iou=0.7, keras=False, kobj=1.0, line_width=None, lr0=0.01, lrf=0.01, mask_ratio=4, max_det=300, mixup=0.0, mode=train, model=yolo26l-seg.pt, momentum=0.937, mosaic=1.0, multi_scale=0.0, name=train-38, nbs=64, nms=False, opset=None, optimize=False, optimizer=auto, overlap_mask=True, patience=20, perspective=0.0, plots=True, pose=12.0, pretrained=True, profile=False, project=None, rect=False, resume=False, retina_masks=False, rle=1.0, save=True, save_conf=False, save_crop=False, save_dir=C:\Users\Yura Sannikov\\--2026\DevOps\gitt\runs\segment\train-38, save_frames=False, save_json=False, save_period=-1, save_txt=False, scale=0.5, seed=0, shear=0.0, show=False, show_boxes=True, show_conf=True, show_labels=True, simplify=True, single_cls=False, source=None, split=val, stream_buffer=False, task=segment, time=None, tracker=botsort.yaml, translate=0.1, val=True, verbose=True, vid_stride=1, visualize=False, warmup_bias_lr=0.1, warmup_epochs=3.0, warmup_momentum=0.8, weight_decay=0.0005, workers=8, workspace=None

                   from  n    params  module                                       arguments
  0                  -1  1      1856  ultralytics.nn.modules.conv.Conv             [3, 64, 3, 2]
  1                  -1  1     73984  ultralytics.nn.modules.conv.Conv             [64, 128, 3, 2]
  2                  -1  2    173824  ultralytics.nn.modules.block.C3k2            [128, 256, 2, True, 0.25]
  3                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
  4                  -1  2    691712  ultralytics.nn.modules.block.C3k2            [256, 512, 2, True, 0.25]
  5                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
  6                  -1  2   2234368  ultralytics.nn.modules.block.C3k2            [512, 512, 2, True]
  7                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
  8                  -1  2   2234368  ultralytics.nn.modules.block.C3k2            [512, 512, 2, True]
  9                  -1  1    656896  ultralytics.nn.modules.block.SPPF            [512, 512, 5, 3, True]
 10                  -1  2   1455616  ultralytics.nn.modules.block.C2PSA           [512, 512, 2]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  2   2496512  ultralytics.nn.modules.block.C3k2            [1024, 512, 2, True]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  2    756736  ultralytics.nn.modules.block.C3k2            [1024, 256, 2, True]
 17                  -1  1    590336  ultralytics.nn.modules.conv.Conv             [256, 256, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  2   2365440  ultralytics.nn.modules.block.C3k2            [768, 512, 2, True]
 20                  -1  1   2360320  ultralytics.nn.modules.conv.Conv             [512, 512, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  1   1974784  ultralytics.nn.modules.block.C3k2            [1024, 512, 1, True, 0.5, True]
 23        [16, 19, 22]  1   8137800  ultralytics.nn.modules.head.Segment26        [80, 32, 256, 1, True, [256, 512, 512]]
YOLO26l-seg summary: 441 layers, 31,515,528 parameters, 31,515,528 gradients, 150.9 GFLOPs

Transferred 1228/1228 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks...
AMP: checks passed
train: Fast image access  (ping: 0.10.1 ms, read: 100.542.4 MB/s, size: 50.0 KB)
train: Scanning C:\Users\Yura Sannikov\Учеба\учеба-весна-2026\DevOps\datasets\coco8-seg\labels\train.cache... 4 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 4/4 1.2Mit/s 0.0s
val: Fast image access  (ping: 0.00.0 ms, read: 90.542.8 MB/s, size: 54.0 KB)
val: Scanning C:\Users\Yura Sannikov\Учеба\учеба-весна-2026\DevOps\datasets\coco8-seg\labels\val.cache... 4 images, 0 backgrounds, 0 corrupt: 100% ━━━━━━━━━━━━ 4/4 883.0Kit/s 0.0s
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000119, momentum=0.9) with parameter groups 198 weight(decay=0.0), 218 weight(decay=0.0005), 218 bias(decay=0.0)
Plotting labels to C:\Users\Yura Sannikov\\--2026\DevOps\gitt\runs\segment\train-38\labels.jpg...
Image sizes 640 train, 640 val
Using 8 dataloader workers
Logging results to C:\Users\Yura Sannikov\\--2026\DevOps\gitt\runs\segment\train-38
Starting training for 10 epochs...
Closing dataloader mosaic

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       1/10      3.68G     0.7973      1.858     0.9525    0.01156     0.1701         13        640: 100% ━━━━━━━━━━━━ 1/1 7.7s/it 7.7s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 1.5s/it 1.5s
                   all          4         17      0.911      0.817      0.916      0.709      0.911      0.817      0.876      0.644

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       2/10      3.79G     0.6489      1.928     0.8498   0.007751     0.1798         13        640: 100% ━━━━━━━━━━━━ 1/1 3.7it/s 0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 8.7it/s 0.1s
                   all          4         17      0.913      0.815      0.916      0.709      0.913      0.815      0.876      0.636

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       3/10      3.79G     0.9095      1.934      1.127    0.01311     0.1457         13        640: 100% ━━━━━━━━━━━━ 1/1 3.7it/s 0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.5it/s 0.1s
                   all          4         17      0.917      0.813      0.916      0.709      0.917      0.813      0.875      0.635

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       4/10      3.84G     0.5971      1.489     0.8883   0.009845     0.1504         13        640: 100% ━━━━━━━━━━━━ 1/1 2.6it/s 0.4s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 11.0it/s 0.1s
                   all          4         17      0.921      0.811      0.883      0.705      0.921      0.811      0.876      0.634

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       5/10      3.88G     0.6494      1.873      1.019    0.01088     0.1967         13        640: 100% ━━━━━━━━━━━━ 1/1 3.6it/s 0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.8it/s 0.1s
                   all          4         17      0.924       0.81      0.883      0.706      0.924       0.81      0.877      0.636

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       6/10      3.88G     0.6187      1.413      0.546   0.008975     0.1686         13        640: 100% ━━━━━━━━━━━━ 1/1 3.5it/s 0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.2it/s 0.1s
                   all          4         17      0.851      0.845      0.883      0.707      0.851      0.845      0.879      0.637

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       7/10      3.88G     0.8565       1.91      0.844    0.01123     0.1316         13        640: 100% ━━━━━━━━━━━━ 1/1 3.6it/s 0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.5it/s 0.1s
                   all          4         17      0.833      0.858      0.885      0.708      0.833      0.858      0.882      0.641

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       8/10      3.88G     0.5645      1.322     0.6093   0.007984     0.1167         13        640: 100% ━━━━━━━━━━━━ 1/1 3.5it/s 0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.7it/s 0.1s
                   all          4         17      0.782      0.867      0.886      0.708      0.782      0.867      0.882      0.624

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
       9/10      3.88G     0.5308      1.343     0.6663   0.006696     0.1094         13        640: 100% ━━━━━━━━━━━━ 1/1 3.5it/s 0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 10.4it/s 0.1s
                   all          4         17      0.934      0.806      0.888       0.71      0.934      0.806      0.884      0.625

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss   sem_loss  Instances       Size
      10/10      3.88G     0.6033      1.301     0.6354   0.007542     0.1128         13        640: 100% ━━━━━━━━━━━━ 1/1 3.6it/s 0.3s
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 9.8it/s 0.1s
                   all          4         17      0.936      0.803      0.888       0.71      0.936      0.803      0.885      0.623

10 epochs completed in 0.008 hours.
Optimizer stripped from C:\Users\Yura Sannikov\\--2026\DevOps\gitt\runs\segment\train-38\weights\last.pt, 63.8MB
Optimizer stripped from C:\Users\Yura Sannikov\\--2026\DevOps\gitt\runs\segment\train-38\weights\best.pt, 63.8MB

Validating C:\Users\Yura Sannikov\\--2026\DevOps\gitt\runs\segment\train-38\weights\best.pt...
Ultralytics 8.4.72  Python-3.14.4 torch-2.11.0+cu128 CUDA:0 (NVIDIA GeForce RTX 5070 Laptop GPU, 8151MiB)
YOLO26l-seg summary (fused): 207 layers, 27,965,436 parameters, 0 gradients, 139.8 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95)     Mask(P          R      mAP50  mAP50-95): 100% ━━━━━━━━━━━━ 1/1 13.0it/s 0.1s
                   all          4         17      0.912      0.816      0.915      0.708      0.912      0.816      0.875      0.644
                person          3         10          1      0.397      0.818        0.5          1      0.397      0.773      0.431
                   dog          1          1      0.803          1      0.995      0.895      0.803          1      0.995      0.895
                 horse          1          2      0.872          1      0.995      0.795      0.872          1      0.995      0.496
              elephant          1          2      0.946        0.5      0.695      0.267      0.946        0.5      0.495      0.247
              umbrella          1          1          1          1      0.995      0.995          1          1      0.995      0.995
          potted plant          1          1       0.85          1      0.995      0.796       0.85          1      0.995      0.796
Speed: 0.4ms preprocess, 9.9ms inference, 0.0ms loss, 0.6ms postprocess per image
Results saved to C:\Users\Yura Sannikov\\--2026\DevOps\gitt\runs\segment\train-38

In [23]:
trained_model

ultralytics.utils.metrics.SegmentMetrics object with attributes:

ap_class_index: array([ 0, 16, 17, 20, 25, 58])
box: ultralytics.utils.metrics.Metric object
confusion_matrix: <ultralytics.utils.metrics.ConfusionMatrix object at 0x0000014F24127110>
curves: ['Precision-Recall(B)', 'F1-Confidence(B)', 'Precision-Confidence(B)', 'Recall-Confidence(B)', 'Precision-Recall(M)', 'F1-Confidence(M)', 'Precision-Confidence(M)', 'Recall-Confidence(M)']
curves_results: [[array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,
           0.40841,     0.40941,     0.41041,     0.41141,     0.41241,     0.41341,     0.41441,     0.41542,     0.41642,     0.41742,     0.41842,     0.41942,     0.42042,     0.42142,     0.42242,     0.42342,     0.42442,     0.42543,     0.42643,     0.42743,     0.42843,     0.42943,     0.43043,     0.43143,
           0.43243,     0.43343,     0.43443,     0.43544,     0.43644,     0.43744,     0.43844,     0.43944,     0.44044,     0.44144,     0.44244,     0.44344,     0.44444,     0.44545,     0.44645,     0.44745,     0.44845,     0.44945,     0.45045,     0.45145,     0.45245,     0.45345,     0.45445,     0.45546,
           0.45646,     0.45746,     0.45846,     0.45946,     0.46046,     0.46146,     0.46246,     0.46346,     0.46446,     0.46547,     0.46647,     0.46747,     0.46847,     0.46947,     0.47047,     0.47147,     0.47247,     0.47347,     0.47447,     0.47548,     0.47648,     0.47748,     0.47848,     0.47948,
           0.48048,     0.48148,     0.48248,     0.48348,     0.48448,     0.48549,     0.48649,     0.48749,     0.48849,     0.48949,     0.49049,     0.49149,     0.49249,     0.49349,     0.49449,      0.4955,      0.4965,      0.4975,      0.4985,      0.4995,      0.5005,      0.5015,      0.5025,      0.5035,
            0.5045,     0.50551,     0.50651,     0.50751,     0.50851,     0.50951,     0.51051,     0.51151,     0.51251,     0.51351,     0.51451,     0.51552,     0.51652,     0.51752,     0.51852,     0.51952,     0.52052,     0.52152,     0.52252,     0.52352,     0.52452,     0.52553,     0.52653,     0.52753,
           0.52853,     0.52953,     0.53053,     0.53153,     0.53253,     0.53353,     0.53453,     0.53554,     0.53654,     0.53754,     0.53854,     0.53954,     0.54054,     0.54154,     0.54254,     0.54354,     0.54454,     0.54555,     0.54655,     0.54755,     0.54855,     0.54955,     0.55055,     0.55155,
           0.55255,     0.55355,     0.55455,     0.55556,     0.55656,     0.55756,     0.55856,     0.55956,     0.56056,     0.56156,     0.56256,     0.56356,     0.56456,     0.56557,     0.56657,     0.56757,     0.56857,     0.56957,     0.57057,     0.57157,     0.57257,     0.57357,     0.57457,     0.57558,
           0.57658,     0.57758,     0.57858,     0.57958,     0.58058,     0.58158,     0.58258,     0.58358,     0.58458,     0.58559,     0.58659,     0.58759,     0.58859,     0.58959,     0.59059,     0.59159,     0.59259,     0.59359,     0.59459,      0.5956,      0.5966,      0.5976,      0.5986,      0.5996,
            0.6006,      0.6016,      0.6026,      0.6036,      0.6046,     0.60561,     0.60661,     0.60761,     0.60861,     0.60961,     0.61061,     0.61161,     0.61261,     0.61361,     0.61461,     0.61562,     0.61662,     0.61762,     0.61862,     0.61962,     0.62062,     0.62162,     0.62262,     0.62362,
           0.62462,     0.62563,     0.62663,     0.62763,     0.62863,     0.62963,     0.63063,     0.63163,     0.63263,     0.63363,     0.63463,     0.63564,     0.63664,     0.63764,     0.63864,     0.63964,     0.64064,     0.64164,     0.64264,     0.64364,     0.64464,     0.64565,     0.64665,     0.64765,
           0.64865,     0.64965,     0.65065,     0.65165,     0.65265,     0.65365,     0.65465,     0.65566,     0.65666,     0.65766,     0.65866,     0.65966,     0.66066,     0.66166,     0.66266,     0.66366,     0.66466,     0.66567,     0.66667,     0.66767,     0.66867,     0.66967,     0.67067,     0.67167,
           0.67267,     0.67367,     0.67467,     0.67568,     0.67668,     0.67768,     0.67868,     0.67968,     0.68068,     0.68168,     0.68268,     0.68368,     0.68468,     0.68569,     0.68669,     0.68769,     0.68869,     0.68969,     0.69069,     0.69169,     0.69269,     0.69369,     0.69469,      0.6957,
            0.6967,      0.6977,      0.6987,      0.6997,      0.7007,      0.7017,      0.7027,      0.7037,      0.7047,     0.70571,     0.70671,     0.70771,     0.70871,     0.70971,     0.71071,     0.71171,     0.71271,     0.71371,     0.71471,     0.71572,     0.71672,     0.71772,     0.71872,     0.71972,
           0.72072,     0.72172,     0.72272,     0.72372,     0.72472,     0.72573,     0.72673,     0.72773,     0.72873,     0.72973,     0.73073,     0.73173,     0.73273,     0.73373,     0.73473,     0.73574,     0.73674,     0.73774,     0.73874,     0.73974,     0.74074,     0.74174,     0.74274,     0.74374,
           0.74474,     0.74575,     0.74675,     0.74775,     0.74875,     0.74975,     0.75075,     0.75175,     0.75275,     0.75375,     0.75475,     0.75576,     0.75676,     0.75776,     0.75876,     0.75976,     0.76076,     0.76176,     0.76276,     0.76376,     0.76476,     0.76577,     0.76677,     0.76777,
           0.76877,     0.76977,     0.77077,     0.77177,     0.77277,     0.77377,     0.77477,     0.77578,     0.77678,     0.77778,     0.77878,     0.77978,     0.78078,     0.78178,     0.78278,     0.78378,     0.78478,     0.78579,     0.78679,     0.78779,     0.78879,     0.78979,     0.79079,     0.79179,
           0.79279,     0.79379,     0.79479,      0.7958,      0.7968,      0.7978,      0.7988,      0.7998,      0.8008,      0.8018,      0.8028,      0.8038,      0.8048,     0.80581,     0.80681,     0.80781,     0.80881,     0.80981,     0.81081,     0.81181,     0.81281,     0.81381,     0.81481,     0.81582,
           0.81682,     0.81782,     0.81882,     0.81982,     0.82082,     0.82182,     0.82282,     0.82382,     0.82482,     0.82583,     0.82683,     0.82783,     0.82883,     0.82983,     0.83083,     0.83183,     0.83283,     0.83383,     0.83483,     0.83584,     0.83684,     0.83784,     0.83884,     0.83984,
           0.84084,     0.84184,     0.84284,     0.84384,     0.84484,     0.84585,     0.84685,     0.84785,     0.84885,     0.84985,     0.85085,     0.85185,     0.85285,     0.85385,     0.85485,     0.85586,     0.85686,     0.85786,     0.85886,     0.85986,     0.86086,     0.86186,     0.86286,     0.86386,
           0.86486,     0.86587,     0.86687,     0.86787,     0.86887,     0.86987,     0.87087,     0.87187,     0.87287,     0.87387,     0.87487,     0.87588,     0.87688,     0.87788,     0.87888,     0.87988,     0.88088,     0.88188,     0.88288,     0.88388,     0.88488,     0.88589,     0.88689,     0.88789,
           0.88889,     0.88989,     0.89089,     0.89189,     0.89289,     0.89389,     0.89489,      0.8959,      0.8969,      0.8979,      0.8989,      0.8999,      0.9009,      0.9019,      0.9029,      0.9039,      0.9049,     0.90591,     0.90691,     0.90791,     0.90891,     0.90991,     0.91091,     0.91191,
           0.91291,     0.91391,     0.91491,     0.91592,     0.91692,     0.91792,     0.91892,     0.91992,     0.92092,     0.92192,     0.92292,     0.92392,     0.92492,     0.92593,     0.92693,     0.92793,     0.92893,     0.92993,     0.93093,     0.93193,     0.93293,     0.93393,     0.93493,     0.93594,
           0.93694,     0.93794,     0.93894,     0.93994,     0.94094,     0.94194,     0.94294,     0.94394,     0.94494,     0.94595,     0.94695,     0.94795,     0.94895,     0.94995,     0.95095,     0.95195,     0.95295,     0.95395,     0.95495,     0.95596,     0.95696,     0.95796,     0.95896,     0.95996,
           0.96096,     0.96196,     0.96296,     0.96396,     0.96496,     0.96597,     0.96697,     0.96797,     0.96897,     0.96997,     0.97097,     0.97197,     0.97297,     0.97397,     0.97497,     0.97598,     0.97698,     0.97798,     0.97898,     0.97998,     0.98098,     0.98198,     0.98298,     0.98398,
           0.98498,     0.98599,     0.98699,     0.98799,     0.98899,     0.98999,     0.99099,     0.99199,     0.99299,     0.99399,     0.99499,       0.996,       0.997,       0.998,       0.999,           1]), array([[          1,           1,           1, ...,    0.090909,    0.090909,           0],
       [          1,           1,           1, ...,           1,           1,           0],
       [          1,           1,           1, ...,           1,           1,           0],
       [          1,           1,           1, ...,         0.4,         0.4,           0],
       [          1,           1,           1, ...,           1,           1,           0],
       [          1,           1,           1, ...,           1,           1,           0]], shape=(6, 1000)), 'Recall', 'Precision'], [array([          0,    0.001001,    0.002002,    0.003003,    0.004004,    0.005005,    0.006006,    0.007007,    0.008008,    0.009009,     0.01001,    0.011011,    0.012012,    0.013013,    0.014014,    0.015015,    0.016016,    0.017017,    0.018018,    0.019019,     0.02002,    0.021021,    0.022022,    0.023023,
          0.024024,    0.025025,    0.026026,    0.027027,    0.028028,    0.029029,     0.03003,    0.031031,    0.032032,    0.033033,    0.034034,    0.035035,    0.036036,    0.037037,    0.038038,    0.039039,     0.04004,    0.041041,    0.042042,    0.043043,    0.044044,    0.045045,    0.046046,    0.047047,
          0.048048,    0.049049,     0.05005,    0.051051,    0.052052,    0.053053,    0.054054,    0.055055,    0.056056,    0.057057,    0.058058,    0.059059,     0.06006,    0.061061,    0.062062,    0.063063,    0.064064,    0.065065,    0.066066,    0.067067,    0.068068,    0.069069,     0.07007,    0.071071,
          0.072072,    0.073073,    0.074074,    0.075075,    0.076076,    0.077077,    0.078078,    0.079079,     0.08008,    0.081081,    0.082082,    0.083083,    0.084084,    0.085085,    0.086086,    0.087087,    0.088088,    0.089089,     0.09009,    0.091091,    0.092092,    0.093093,    0.094094,    0.095095,
          0.096096,    0.097097,    0.098098,    0.099099,      0.1001,      0.1011,      0.1021,      0.1031,      0.1041,     0.10511,     0.10611,     0.10711,     0.10811,     0.10911,     0.11011,     0.11111,     0.11211,     0.11311,     0.11411,     0.11512,     0.11612,     0.11712,     0.11812,     0.11912,
           0.12012,     0.12112,     0.12212,     0.12312,     0.12412,     0.12513,     0.12613,     0.12713,     0.12813,     0.12913,     0.13013,     0.13113,     0.13213,     0.13313,     0.13413,     0.13514,     0.13614,     0.13714,     0.13814,     0.13914,     0.14014,     0.14114,     0.14214,     0.14314,
           0.14414,     0.14515,     0.14615,     0.14715,     0.14815,     0.14915,     0.15015,     0.15115,     0.15215,     0.15315,     0.15415,     0.15516,     0.15616,     0.15716,     0.15816,     0.15916,     0.16016,     0.16116,     0.16216,     0.16316,     0.16416,     0.16517,     0.16617,     0.16717,
           0.16817,     0.16917,     0.17017,     0.17117,     0.17217,     0.17317,     0.17417,     0.17518,     0.17618,     0.17718,     0.17818,     0.17918,     0.18018,     0.18118,     0.18218,     0.18318,     0.18418,     0.18519,     0.18619,     0.18719,     0.18819,     0.18919,     0.19019,     0.19119,
           0.19219,     0.19319,     0.19419,      0.1952,      0.1962,      0.1972,      0.1982,      0.1992,      0.2002,      0.2012,      0.2022,      0.2032,      0.2042,     0.20521,     0.20621,     0.20721,     0.20821,     0.20921,     0.21021,     0.21121,     0.21221,     0.21321,     0.21421,     0.21522,
           0.21622,     0.21722,     0.21822,     0.21922,     0.22022,     0.22122,     0.22222,     0.22322,     0.22422,     0.22523,     0.22623,     0.22723,     0.22823,     0.22923,     0.23023,     0.23123,     0.23223,     0.23323,     0.23423,     0.23524,     0.23624,     0.23724,     0.23824,     0.23924,
           0.24024,     0.24124,     0.24224,     0.24324,     0.24424,     0.24525,     0.24625,     0.24725,     0.24825,     0.24925,     0.25025,     0.25125,     0.25225,     0.25325,     0.25425,     0.25526,     0.25626,     0.25726,     0.25826,     0.25926,     0.26026,     0.26126,     0.26226,     0.26326,
           0.26426,     0.26527,     0.26627,     0.26727,     0.26827,     0.26927,     0.27027,     0.27127,     0.27227,     0.27327,     0.27427,     0.27528,     0.27628,     0.27728,     0.27828,     0.27928,     0.28028,     0.28128,     0.28228,     0.28328,     0.28428,     0.28529,     0.28629,     0.28729,
           0.28829,     0.28929,     0.29029,     0.29129,     0.29229,     0.29329,     0.29429,      0.2953,      0.2963,      0.2973,      0.2983,      0.2993,      0.3003,      0.3013,      0.3023,      0.3033,      0.3043,     0.30531,     0.30631,     0.30731,     0.30831,     0.30931,     0.31031,     0.31131,
           0.31231,     0.31331,     0.31431,     0.31532,     0.31632,     0.31732,     0.31832,     0.31932,     0.32032,     0.32132,     0.32232,     0.32332,     0.32432,     0.32533,     0.32633,     0.32733,     0.32833,     0.32933,     0.33033,     0.33133,     0.33233,     0.33333,     0.33433,     0.33534,
           0.33634,     0.33734,     0.33834,     0.33934,     0.34034,     0.34134,     0.34234,     0.34334,     0.34434,     0.34535,     0.34635,     0.34735,     0.34835,     0.34935,     0.35035,     0.35135,     0.35235,     0.35335,     0.35435,     0.35536,     0.35636,     0.35736,     0.35836,     0.35936,
           0.36036,     0.36136,     0.36236,     0.36336,     0.36436,     0.36537,     0.36637,     0.36737,     0.36837,     0.36937,     0.37037,     0.37137,     0.37237,     0.37337,     0.37437,     0.37538,     0.37638,     0.37738,     0.37838,     0.37938,     0.38038,     0.38138,     0.38238,     0.38338,
           0.38438,     0.38539,     0.38639,     0.38739,     0.38839,     0.38939,     0.39039,     0.39139,     0.39239,     0.39339,     0.39439,      0.3954,      0.3964,      0.3974,      0.3984,      0.3994,      0.4004,      0.4014,      0.4024,      0.4034,      0.4044,     0.40541,     0.40641,     0.40741,

In [ ]:
from pprint import pprint
import matplotlib
matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
from os import listdir
from os.path import isfile, join
import cv2

def showResult(results):
    for result in results:
        print(type(result.show()))

def checkTrainedModel(trained_model):
    # 'C:/Users/Yura Sannikov/Учеба/учеба-весна-2026/DevOps/gitt/runs/segment/train'
    dataFr = pd.read_csv(str(trained_model.save_dir)+'/results.csv')
    plt.title("График точности")
    plt.plot(dataFr["epoch"], dataFr["metrics/precision(B)"])
    plt.xlabel("Эпоха обучения")
    plt.ylabel("Значение точности")
    plt.legend()
    plt.grid()
    plt.show()

In [14]:
model_best = YOLO(str(trained_model.save_dir)+'/weights/best.pt')

In [15]:
# Посмотрим результаты обучения
checkTrainedModel(trained_model)

C:\Users\Yura Sannikov\AppData\Local\Temp\ipykernel_15272\1619115411.py:23: UserWarning: No artists with labels found to put in legend.  Note that artists whose label start with an underscore are ignored when legend() is called with no argument.
  plt.legend()

In [22]:
# results = model_best("https://ultralytics.com/images/bus.jpg")  # predict on an image
# # Access the results
# showResult(results)

In [23]:
# img_to_check = cv2.imread("frameToCheck.jpg")
# # Predict with the model
# results = model_best(img_to_check)  # predict on an image
# # Access the results
# showResult(results)

In [24]:
# # Дотренировываем модель с размеченными данными
# model = YOLO(str(trained_model.save_dir)+'/weights/best.pt')

In [25]:
# trained_model = model.train(data="trafficLight-1/data.yaml", epochs=700, imgsz=imgSize, optimizer="AdamW", patience=30)

In [26]:
# # Посмотрим результаты обучения
# checkTrainedModel(trained_model)

In [27]:
# model_best = YOLO(str(trained_model.save_dir)+'/weights/best.pt')

In [28]:
# results = model_best("https://ultralytics.com/images/bus.jpg")  # predict on an image
# # Access the results
# showResult(results)

In [29]:
# img_to_check = cv2.imread("frameToCheck.jpg")
# # Predict with the model
# results = model_best(img_to_check)  # predict on an image
# # Access the results
# showResult(results)

In [16]:
pathToVideoFolder = 'C:/Users/Yura Sannikov/Учеба/НИР-диплом26/Папка с кодомм/исходные/'
videoImagesFolder = 'C:/Users/Yura Sannikov/Учеба/НИР-диплом26/Папка с кодомм/исходные/imagesFolder/'

In [17]:
import time
import math
# from google.colab.patches import cv2_imshow

import os
from glob import glob

# Новый код

In [18]:
def getMaxMinCort(a, b):
   return (a, b) if a > b else (b, a)
def getFarthestNearestDots(a, b, dots):
   return (dots[0], dots[1]) if a > b else (dots[1], dots[0])


def getRightLeftTopBottom(line1, line2):
   right, left = getFarthestNearestDots(line1[0][0], line1[1][0], line1)
   bottom, top = getFarthestNearestDots(line2[0][1], line2[1][1], line2)
   return right, left, top, bottom

def drawLine(img, coordinates, color=(128, 0, 32)):
   coord0_int = tuple(int(x) for x in coordinates[0])
   coord1_int = tuple(int(x) for x in coordinates[1])

   cv2.line(img, coord0_int, coord1_int, color, 2)

In [19]:
def find_fourth_point(a, b, c):
    """
    a, b, c — кортежи или списки вида (x, y).
    Предполагается, что b — общая вершина для сторон ab и bc.
    """
    dx = a[0] + c[0] - b[0]
    dy = a[1] + c[1] - b[1]
    return (dx, dy)

# Пример использования:
A = (1, 1)
B = (4, 2)
C = (5, 5)

D = find_fourth_point(A, B, C)
print(f"Координаты 4-й точки: {D}")

Координаты 4-й точки: (2, 4)

In [20]:
class DrawLineWidget(object):
    def __init__(self, img):
        self.original_image = img
        self.clone = self.original_image.copy()

        cv2.namedWindow('image')
        cv2.setMouseCallback('image', self.extract_coordinates)

        # List to store start/end points
        self.image_coordinates = []

    def extract_coordinates(self, event, x, y, flags, parameters):
        # Record starting (x,y) coordinates on left mouse button click
        if event == cv2.EVENT_LBUTTONDOWN:
            if (len(self.image_coordinates) < 2):
                self.image_coordinates = [(x,y)]

        # Record ending (x,y) coordinates on left mouse bottom release
        elif event == cv2.EVENT_LBUTTONUP:
            if (len(self.image_coordinates) < 2):
                self.image_coordinates.append((x,y))
                print('Starting: {}, Ending: {}'.format(self.image_coordinates[0], self.image_coordinates[1]))

                # Draw line
                drawLine(self.clone, self.image_coordinates)
                cv2.imshow("image", self.clone) 

        # Clear drawing boxes on right mouse button click
        elif event == cv2.EVENT_RBUTTONDOWN:
            self.clone = self.original_image.copy()
            self.image_coordinates = []

    def getImageCoordinates(self):
        return self.image_coordinates
    def show_image(self):
        return self.clone

In [21]:
!pip install shapely

Requirement already satisfied: shapely in .\git\.venv\Lib\site-packages (2.1.2)
Requirement already satisfied: numpy>=1.21 in .\git\.venv\Lib\site-packages (from shapely) (2.4.4)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [22]:
from enum import Enum
from itertools import chain

class Direction(str, Enum):
    '''
    сторона относительно линии
    '''
    LEFT = 'left'
    RIGHT = 'right'
def getReverseDirection(direc: Direction):
    '''
    обратное направление
    '''
    return Direction.LEFT if direc == Direction.RIGHT else Direction.RIGHT
class VerticalDirection(str, Enum):
    '''
    Вертикальное направление
    '''
    ToTop = 'ToTop'
    ToBottom = 'ToBottom'
class HorizontalDirection(str, Enum):
    '''
    Горизонтальное направление
    '''
    ToRight = 'ToRight'
    ToLeft = 'ToLeft'
# Все направления
AllDirections = Enum(
    'AllDirections',
    {item.name: item.value for item in chain(HorizontalDirection, VerticalDirection)}
)

class AreaCoords:
    def __init__(self, top_left=None, top_right=None, bottom_right=None, bottom_left=None):
        self.top_left = top_left
        self.top_right = top_right
        self.bottom_right = bottom_right
        self.bottom_left = bottom_left

    def set_coords(self, top_left=None, top_right=None, bottom_right=None, bottom_left=None):
        if top_left != None:
            self.top_left = top_left
        if top_right != None:
            self.top_right = top_right
        if bottom_right != None:
            self.bottom_right = bottom_right
        if bottom_left != None:
            self.bottom_left = bottom_left

    def is_any_none(self):
        '''
        Есть ли хоть одна координата None
        '''
        return True if self.top_left == None or self.top_right == None or self.bottom_left == None or self.bottom_right == None else False
    
    def get_area_coords(self):
        '''
        Returns array of coords
        '''
        return np.array([self.top_left, self.top_right, self.bottom_right, self.bottom_left])
    
    def get_bottom_coords(self, direction: HorizontalDirection):
        '''
        Returns array of bottom coords
        direction - direction to last dot in array
        '''
        return [self.bottom_right, self.bottom_left
             ] if direction == HorizontalDirection.ToLeft else [self.bottom_left, self.bottom_right]
    def get_right_coords(self, direction: VerticalDirection):
        '''
        Returns array of right coords
        direction - direction to last dot in array
        '''
        return [self.top_right, self.bottom_right
                ] if direction == VerticalDirection.ToBottom else [self.bottom_right, self.top_right]
    def get_top_coords(self, direction: HorizontalDirection):
        '''
        Returns array of top coords
        direction - direction to last dot in array
        '''
        return [self.top_left, self.top_right] if direction == HorizontalDirection.ToRight else [self.top_right, self.top_left]
    def get_left_coords(self, direction: VerticalDirection):
        '''
        Returns array of left coords
        direction - direction to last dot in array
        '''
        return [self.bottom_left, self.top_left] if direction == VerticalDirection.ToTop else [self.top_left, self.bottom_left]
    
    def state_dict(self):
      return {
        'top_left': self.top_left,
        'top_right': self.top_right,
        'bottom_left': self.bottom_left,
        'bottom_right': self.bottom_right,
      }

    def load_state_dict(self, state):
      self.top_left = tuple(state['top_left'])
      self.top_right = tuple(state['top_right'])
      self.bottom_left = tuple(state['bottom_left'])
      self.bottom_right = tuple(state['bottom_right'])

In [23]:
from shapely import LineString

def isLineInsideCorrectArea(main_line: LineString, object_line: LineString, correct_position: Direction, withIntersect = True) -> str:
    """
    Проверяет, если крайняя граница объекта к встречному движению пересекает либо находится в нужном от него напралении
    (для движения спарва налево, проверяем нижнюю границу объекта)
    main_line - Линия направления движения (координаты передаются по направлению движения)
    object_line - крайняя линия объекта
    correct_position - требуемое расположение линии объекта относительно основной
    returns: boolean
    """
    if withIntersect and object_line.intersects(main_line):
        return True
    # Смещаем на 1 единицу влево и вправо
    left = main_line.offset_curve(1.0)
    right = main_line.offset_curve(-1.0)
    
    # Сравниваем расстояния
    position = Direction.LEFT if left.distance(object_line) < right.distance(object_line) else Direction.RIGHT
    return position == correct_position

# Пример
ref = LineString([(0, 0), (5, 0)])
print(isLineInsideCorrectArea(ref, LineString([(1, 1), (4, 1)]), Direction.LEFT))   # left

True

In [ ]:
print(isLineInsideCorrectArea(LineString([[1956,  767], [1358,  628]]), LineString([[1691, 739], [1627, 739]]), Direction.RIGHT))   # left

True

In [ ]:
import shapely
from shapely.geometry import LineString, Polygon

def getInfiniteRay(line:LineString):
    '''
    Создает луч из данного вектора
    '''
    a, b =  line.coords[0], line.coords[-1] 
    # a, b - кортежи (x, y)
    dx = b[0] - a[0]
    dy = b[1] - a[1]
    
    # т.к. луч - бесконечная прямая, 
    # умножаем вектор на очень большое число (100000) 
    # и строим отрезок от точки A
    scale = 100000
    p2_x = a[0] + dx * scale
    p2_y = a[1] + dy * scale
    
    return LineString([a, (p2_x, p2_y)])

def getIntersectionPoint(line1: LineString, line2: LineString):
    '''
    Получает точку пересечения двух линий, которые точно должны пересечься
    '''
    return line1.intersection(line2)
def getNextIntersectPoint(line1:LineString, line2:LineString):
    '''
    Получает на вход два вектора и возвращает точку, в которой они сомкнутся
    '''
    ray1 = getInfiniteRay(line1)
    ray2 = getInfiniteRay(line2)
    return getIntersectionPoint(ray1, ray2)

In [37]:
line_1 = LineString([(1354, 622), (1305, 665)])
line_2= LineString([(1906, 801), (1205, 605)])
print(f"точка пересечения: {getNextIntersectPoint(line_1, line_2)}")

точка пересечения: POINT (1332.688630588472 640.7018139733816)

In [ ]:
def isIntersectOrInside(square_coords, area_coords):
    '''
    Проверяет есть ли общие точки у квадрата и области 
    (так-же проверяет, если крайняя граница объекта к встречному движению пересекает либо находится в нужном от него напралении)
    (для движения спарва налево, проверяем нижнюю границу объекта)
    square_coords - координаты квадрата
    area_coords - координаты области
    '''
    square = Polygon(square_coords)
    target_area = Polygon(area_coords)
    # 1. Проверить, пересекает ли квадрат область (есть ли общие точки)
    if square.intersects(target_area):
        return True
    # 2. Проверить, находится ли квадрат ПОЛНОСТЬЮ внутри области
    if square.within(target_area):
        return True
    return False

In [27]:
print(Polygon(np.array([(0,0),(1,1),(2,2),(4,4)])))

POLYGON ((0 0, 1 1, 2 2, 4 4, 0 0))

In [28]:
from collections import Counter
Counter()

Counter()

In [29]:

class DirectionOfGreen(str, Enum):
    '''
    В какомм направлении необходимо пускать зеленый
    '''
    HORIZONTAL = 2
    VERTICAL = 1
    NONE = 0

In [30]:
mapOfDirections = {
    '0': 'NoneDirections',
    '1': 'VerticalDirections',
    '2': 'HorizontalDirecctions',
}

In [31]:
!pip install catboost

Requirement already satisfied: catboost in .\git\.venv\Lib\site-packages (1.2.10)
Requirement already satisfied: graphviz in .\git\.venv\Lib\site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in .\git\.venv\Lib\site-packages (from catboost) (3.11.0)
Requirement already satisfied: numpy<3.0,>=1.16.0 in .\git\.venv\Lib\site-packages (from catboost) (2.4.4)
Requirement already satisfied: pandas<4.0,>=0.24 in .\git\.venv\Lib\site-packages (from catboost) (3.0.2)
Requirement already satisfied: scipy in .\git\.venv\Lib\site-packages (from catboost) (1.17.1)
Requirement already satisfied: plotly in .\git\.venv\Lib\site-packages (from catboost) (6.7.0)
Requirement already satisfied: six in .\git\.venv\Lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in .\git\.venv\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: tzdata in .\git\.venv\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2026.1)
Requirement already satisfied: contourpy>=1.0.1 in .\git\.venv\Lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\git\.venv\Lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\git\.venv\Lib\site-packages (from matplotlib->catboost) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in .\git\.venv\Lib\site-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\git\.venv\Lib\site-packages (from matplotlib->catboost) (26.1)
Requirement already satisfied: pillow>=9 in .\git\.venv\Lib\site-packages (from matplotlib->catboost) (12.2.0)
Requirement already satisfied: pyparsing>=3 in .\git\.venv\Lib\site-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: narwhals>=1.15.1 in .\git\.venv\Lib\site-packages (from plotly->catboost) (2.20.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [32]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in .\git\.venv\Lib\site-packages (1.9.0)
Requirement already satisfied: numpy>=1.24.1 in .\git\.venv\Lib\site-packages (from scikit-learn) (2.4.4)
Requirement already satisfied: scipy>=1.10.0 in .\git\.venv\Lib\site-packages (from scikit-learn) (1.17.1)
Requirement already satisfied: joblib>=1.4.0 in .\git\.venv\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in .\git\.venv\Lib\site-packages (from scikit-learn) (2.20.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in .\git\.venv\Lib\site-packages (from scikit-learn) (3.6.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [33]:
from catboost import CatBoostClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

In [ ]:
import json
from collections import Counter
import random


class VideoConverterClassV2:

  def __init__(self, pathToVideoFolder = '/content/drive/MyDrive/2025Mag2/НИР/Видео/', videoImagesFolder = '/content/drive/MyDrive/2025Mag2/НИР/Видео/imagesFolder/', tracker_choice='botsort'):
    self.pathToVideoFolder = pathToVideoFolder # путь до папки с видео
    self.videoImagesFolder = videoImagesFolder # путь до папки, для сохранения отдельно предсказанных изображения изображений
    self.setTrackerChoice(tracker_choice)
    # количество кадров в секунду
    self.fps = 24
    self.info_color = (102,0,102)
    self.pred_color = (32,178,170)
    self.default_color = (128, 128, 128)
    # Координаты задающие направления на перекрестке
    self.area_coord_right_to_left = AreaCoords();
    self.crossroad_right_to_left_lines_coordinates = []
    self.right_to_left_color = (0,255,0)
    self.area_coord_top_to_bottom = AreaCoords();
    self.crossroad_top_to_bottom_lines_coordinates = []
    self.top_to_bottom_color = (255, 80, 255)
    self.area_coord_left_to_right = AreaCoords();
    self.crossroad_left_to_right_lines_coordinates = []
    self.left_to_right_color = (0, 168, 243)
    self.area_coord_bottom_to_top = AreaCoords();
    self.crossroad_bottom_to_top_lines_coordinates = []
    self.bottom_to_top_color = (255, 236, 20)
    # координаты области перекрестка
    self.area_crossroad = AreaCoords();
    self.area_crossroad_color = (127,255,212)
    self.arrayToDraw = np.array(['car', 'person', 'bus', 'truck', 'motorcycle'])
    self.windowNameForLine = 'image'
    self.json_lines_name = 'json_lines.json'
    self.csv_name = 'collected_info.csv'
    self.json_folder_name = '/json_lines'
    # Данные о дорожной ситуации
    '''
    'time_of_info' - время, когда получена информация
    'count_to...' - текущее количество автомобилей в направлении ...
    'count_stuck_middle' - текущее количесство автомобилей, застрявших посреди перекрестка
    'count_stuck_to...' - текущее количесство автомобилей, застрявших в направлении ...
    'is_jam_next...' - наличие пробки у следующего перекрестка по направлению ...
    *застрявших означает что объект находится в области больше одной итерации.*
    'is_green_horizontal' - В данный момент горит зеленый для горизонтальных направлений
    'is_green_vertical' - В данный момент горит зеленый для вертикальных направлений
    'y' - направление которому необходимо дать зеленый сигнал 
    '''
    self.columns = ['time_of_info',
                    'count_to_r',
                    'count_to_l',
                    'count_to_b',
                    'count_to_t',
                    'count_stuck_middle',
                    'count_stuck_to_r',
                    'count_stuck_to_l',
                    'count_stuck_to_b',
                    'count_stuck_to_t',
                    'is_jam_next_l',
                    'is_jam_next_r',
                    'is_jam_next_t',
                    'is_jam_next_b',
                    'is_green_horizontal',
                    'is_green_vertical',
                    'y',
                    ]
    self.feature_cols = self.columns[1:-1]
    self.pred_col = self.columns[-1]
    # датафрейм для сохранения информации о ситуации на перекрестке
    self.trafficInfoDF = pd.DataFrame(columns=self.columns)
    # счетчик итераций для машин, застрявших в указанной области
    self.objects_stuck_middle = Counter()
    self.objects_stuck_to_r = Counter()
    self.objects_stuck_to_l = Counter()
    self.objects_stuck_to_b = Counter()
    self.objects_stuck_to_t = Counter()
    # сеты машин, в указанной области
    self.objects_to_r = set()
    self.objects_to_l = set()
    self.objects_to_b = set()
    self.objects_to_t = set()

  def save_lines_to_json(self, folder_to_save):
    '''
    Сохраняет данные об областях в json файлик
    json файл сохраняется в папку self.json_folder_name в папке, где хранятся кадры видео
    '''
    data = {
      'area_coord_right_to_left': self.area_coord_right_to_left.state_dict(),
      'area_coord_top_to_bottom': self.area_coord_top_to_bottom.state_dict(),
      'area_coord_left_to_right': self.area_coord_left_to_right.state_dict(),
      'area_coord_bottom_to_top': self.area_coord_bottom_to_top.state_dict(),
      'area_crossroad': self.area_crossroad.state_dict()
    }
    path_to_save_folder = folder_to_save + self.json_folder_name
    if not os.path.exists(path_to_save_folder):
      os.makedirs(path_to_save_folder)
    
    file_name = path_to_save_folder +'/'+ self.json_lines_name
    # Open file in write mode ('w')
    with open(file_name, "w") as file:
        json.dump(data, file)

  def save_dataframe(self, folder_to_save):
    '''
    Сохраняет собранные данные об областях в csv файлик
    csv файл сохраняется в папку self.json_folder_name в папке, где хранятся кадры видео
    '''

    path_to_save_folder = folder_to_save + self.json_folder_name
    fileListLen = str(len(glob(path_to_save_folder+'/*')))
    if not os.path.exists(path_to_save_folder):
      os.makedirs(path_to_save_folder)
    
    file_name = path_to_save_folder +'/'+fileListLen+'_'+ self.csv_name
    # Open file in write mode ('w')
    # сохранение собранной информации в csv
    self.trafficInfoDF.to_csv(file_name, index=False)

  def load_lines_from_json(self, folder_to_save):
    '''
    Загружает данные об областях из json файлика
    json файл должен находиться в папке self.json_folder_name в папке, где хранятся кадры видео
    '''
    path_to_save_folder = folder_to_save+self.json_folder_name
    file_name = path_to_save_folder +'/'+ self.json_lines_name
    if not os.path.exists(file_name):
      print("File with lines not found :(. Please draw new ones")
      return False
    else:
      try:
        # Open the file and parse its contents
        with open(file_name, 'r', encoding='utf-8') as file:
            data = json.load(file)
            self.area_coord_right_to_left.load_state_dict(data["area_coord_right_to_left"])
            self.area_coord_top_to_bottom.load_state_dict(data["area_coord_top_to_bottom"])
            self.area_coord_left_to_right.load_state_dict(data["area_coord_left_to_right"])
            self.area_coord_bottom_to_top.load_state_dict(data["area_coord_bottom_to_top"])
            self.area_crossroad.load_state_dict(data["area_crossroad"])
            print("lines loaded")
            return True
      except:
        print("Error occured while reading :(. Please draw new ones")
        return False

  def setTrackerChoice(self, tracker_choice):
    if tracker_choice not in ['botsort', 'bytetrack']:
        print(f"Invalid tracker choice '{tracker_choice}', defaulting to 'botsort'")
        self.tracker_choice = 'botsort'
    else:
       self.tracker_choice = tracker_choice

  def convertToVid(self, folder_name, video_name = 'vidSeg.avi'):
    '''
    Конвертация изображений в видео
    folder_name - Название папки с сегментированными изображениями
    video_name - название собранного видео
    '''
    pathToVideoImages = self.videoImagesFolder + folder_name
    if not os.path.exists(pathToVideoImages):
      print("Try run Mask Video first")
    else:

      images = [img for img in os.listdir(pathToVideoImages) if img.endswith((".jpg", ".jpeg", ".png"))]
      print("Images:", images)

      # Set frame from the first image
      frame = cv2.imread(os.path.join(pathToVideoImages, images[0]))
      height, width, layers = frame.shape

      # Video writer to create .avi file
      pathToVideo = self.pathToVideoFolder + video_name
      video = cv2.VideoWriter(pathToVideo, cv2.VideoWriter_fourcc(*'DIVX'), self.fps, (width, height))

      # Appending images to video
      for image in images:
          video.write(cv2.imread(os.path.join(pathToVideoImages, image)))

      # Release the video file
      video.release()
      cv2.destroyAllWindows()
      print("Video generated successfully!")

  def predictSingleImg(self, img, model, pathToVideoImages, curIm):
    '''
    Predict single img with the model
    img - Изображение для сегментации
    model - обученная модель для сегментации
    '''
    results = model(img)  # predict on an image

    # Access the results
    for result in results:
      name = pathToVideoImages + "/" + str(curIm).zfill(32) + '.jpg'
      result.save(filename=name)

    return result
  
  def addLineOnImage(self, img, label):
     cv2.putText(img, f"draw line: {label}", (10, 70),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, self.info_color, 3)
     cv2.putText(img, f"q - skip draw \n e - continue \n rClick - clear line", (10, 150),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, self.info_color, 3)
     draw_line_widget = DrawLineWidget(img)
     while True:
      cv2.imshow(self.windowNameForLine, draw_line_widget.show_image())

      key = cv2.waitKey(1) & 0xFF

      # Close program with keyboard 'q'
      if key == ord('q'):
          cv2.destroyWindow(self.windowNameForLine)
          return []
      if key == ord('e'):
        line_coords = draw_line_widget.getImageCoordinates()
        print(line_coords)
        if (len(line_coords) != 2):
          cv2.putText(img, f"add line", (10, 230),
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 0, 255), 3)
        else:
          cv2.destroyWindow(self.windowNameForLine)
          return line_coords
  
  def drawAllCoords(self, img, area: AreaCoords, color=(128, 0, 32)):
      drawLine(img, area.get_bottom_coords(HorizontalDirection.ToLeft), color)
      drawLine(img, area.get_right_coords(VerticalDirection.ToBottom), color)
      drawLine(img, area.get_top_coords(HorizontalDirection.ToLeft), color)
      drawLine(img, area.get_left_coords(VerticalDirection.ToBottom), color)

  def drawSeparatorLines(self, img):
    if self.area_coord_right_to_left.is_any_none() == False:
      self.drawAllCoords(img, self.area_coord_right_to_left)
    if self.area_coord_bottom_to_top.is_any_none() == False:
      self.drawAllCoords(img, self.area_coord_bottom_to_top)
    if self.area_coord_left_to_right.is_any_none() == False:
      self.drawAllCoords(img, self.area_coord_left_to_right)
    if self.area_coord_top_to_bottom.is_any_none() == False:
      self.drawAllCoords(img, self.area_coord_top_to_bottom)
    if self.area_crossroad.is_any_none() == False:
      self.drawAllCoords(img, self.area_crossroad, self.area_crossroad_color)
  
  def isCorrectLines(self, main_line, border_line, object_line, correct_position: Direction):
    # т.к. в видео захвате y сверх вниз делаем реверс correct_position
    main_correct_position = getReverseDirection(correct_position)
    border_correct_position = Direction.LEFT if main_correct_position == Direction.RIGHT else Direction.RIGHT
    mainLineString = LineString(main_line)
    objectLineString = LineString(object_line)
    borderLineString = LineString(border_line)
    return isLineInsideCorrectArea(
          main_line=mainLineString,
          object_line=objectLineString,
          correct_position=main_correct_position) and isLineInsideCorrectArea(
          main_line=borderLineString,
          object_line=objectLineString,
          correct_position=border_correct_position,
          withIntersect=False)
    

  def checkIfObjectInsideCorrectArea(self, box_coords, objectBox: AreaCoords, areaDirection: HorizontalDirection | VerticalDirection):
    '''
    В случае, когда объект касается нужной области проверяет,
    если этот объект находится на корректной стороне движения и не на обочине
    '''
    match areaDirection:
      case HorizontalDirection.ToLeft:
        areaObject = self.area_coord_right_to_left
        # В случае, если объект касается области проверяем, если 
        if isIntersectOrInside(box_coords, areaObject.get_area_coords()) == False:
          return False
        else:
          object_line = objectBox.get_bottom_coords(HorizontalDirection.ToLeft)
          # print(areaObject.get_area_coords(), object_line)
          return self.isCorrectLines(
            main_line=areaObject.get_bottom_coords(HorizontalDirection.ToLeft),
            object_line=object_line,
            border_line=areaObject.get_top_coords(HorizontalDirection.ToLeft),
            correct_position=Direction.RIGHT
          )
      case HorizontalDirection.ToRight:
        areaObject = self.area_coord_left_to_right
        # В случае, если объект касается области проверяем, если 
        if isIntersectOrInside(box_coords, areaObject.get_area_coords()) == False:
          return False
        else:
          object_line = objectBox.get_top_coords(HorizontalDirection.ToRight)
          return self.isCorrectLines(
            main_line=areaObject.get_top_coords(HorizontalDirection.ToRight),
            object_line=object_line,
            border_line=areaObject.get_bottom_coords(HorizontalDirection.ToRight),
            correct_position=Direction.RIGHT
          )
      case VerticalDirection.ToBottom:
        areaObject = self.area_coord_top_to_bottom
        # В случае, если объект касается области проверяем, если 
        if isIntersectOrInside(box_coords, areaObject.get_area_coords()) == False:
          return False
        else:
          object_line = objectBox.get_right_coords(VerticalDirection.ToBottom)
          return self.isCorrectLines(
            main_line=areaObject.get_right_coords(VerticalDirection.ToBottom),
            object_line=object_line,
            border_line=areaObject.get_left_coords(VerticalDirection.ToBottom),
            correct_position=Direction.RIGHT
          )
      case VerticalDirection.ToTop:
        areaObject = self.area_coord_bottom_to_top
        # В случае, если объект касается области проверяем, если 
        if isIntersectOrInside(box_coords, areaObject.get_area_coords()) == False:
          return False
        else:
          object_line = objectBox.get_left_coords(VerticalDirection.ToTop)
          return self.isCorrectLines(
            main_line=areaObject.get_left_coords(VerticalDirection.ToTop),
            object_line=object_line,
            border_line=areaObject.get_right_coords(VerticalDirection.ToTop),
            correct_position=Direction.RIGHT
          )
      case _:
        return False
      
  def getTrullyStuck(self, _counter: Counter):
    '''
    Возвращает количество машин, которые простояли в области n больше 2 итераций
    '''
    return len([item for item, count in _counter.items() if count > 2])
  
  def addToDirectionSet(self, _set: set, trackId):
    if trackId not in _set:
      _set.add(trackId)
  def addToDirectionCounter(self, _counter: Counter, trackId, skipCheck=False):
    if skipCheck or trackId not in _counter:
      _counter.update([trackId])
    
  def removeFromSet(self, _set: set, trackId):
    if trackId in _set:
      _set.remove(trackId)
  def removeFromCounter(self, _counter: Counter, trackId):
    if trackId in _counter:
      del _counter[trackId]

  def removeFromOtherStuckCounters(self, trackId):
    self.removeFromCounter(self.objects_stuck_to_b, trackId)
    self.removeFromCounter(self.objects_stuck_to_l, trackId)
    self.removeFromCounter(self.objects_stuck_to_r, trackId)
    self.removeFromCounter(self.objects_stuck_to_t, trackId)

  def removeFromOtherCurrentSets(self, trackId):
    self.removeFromSet(self.objects_to_b, trackId)
    self.removeFromSet(self.objects_to_l, trackId)
    self.removeFromSet(self.objects_to_r, trackId)
    self.removeFromSet(self.objects_to_t, trackId)
  
  def addToMiddleCounter(self, trackId):
    if trackId not in self.objects_stuck_middle:
      self.objects_stuck_middle.update([trackId])
      self.removeFromOtherStuckCounters(trackId)
      self.removeFromOtherCurrentSets(trackId)

  def getLinesOnFrame(self, frame_result, folder_to_save):
    '''
    Получает отрисованные пользователем линии для областей наблюдения
    '''
    # линии для справа налево
    line1 = self.addLineOnImage(frame_result.orig_img.copy(), "separating traffic right to left with pedestrian crossing")
    if (len(line1)):
      self.crossroad_right_to_left_lines_coordinates.append(line1)
    line2 = self.addLineOnImage(frame_result.orig_img.copy(), "pedestrian crossing on right to left")
    if (len(line2)):
      self.crossroad_right_to_left_lines_coordinates.append(line2)
    if (len(line2) and len(line1)):
      right, left, top, bottom = getRightLeftTopBottom(line1, line2)
      #!!!!!!!! нужно получить угол по которому стоит дорога
      coord_border = find_fourth_point(right, left, top)
      self.crossroad_right_to_left_lines_coordinates.append([top, coord_border])
      self.area_coord_right_to_left.set_coords(
        top_left=top,
        top_right=coord_border, 
        bottom_left=left, 
        bottom_right=right
      )
    else:
      self.crossroad_right_to_left_lines_coordinates = []

    # линии для сверху вниз
    line1 = self.addLineOnImage(frame_result.orig_img.copy(), "separating traffic top to bottom with pedestrian crossing")
    if (len(line1)):
      self.crossroad_top_to_bottom_lines_coordinates.append(line1)
    line2 = self.addLineOnImage(frame_result.orig_img.copy(), "pedestrian crossing on top to bottom")
    if (len(line2)):
      self.crossroad_top_to_bottom_lines_coordinates.append(line2)
    if (len(line2) and len(line1)):
      right, left, top, bottom = getRightLeftTopBottom(line2, line1)
      coord_border = find_fourth_point(left, bottom, top)
      self.area_coord_top_to_bottom.set_coords(
        top_left=coord_border, 
        top_right=top, 
        bottom_left=left, 
        bottom_right=bottom
      )
      self.crossroad_top_to_bottom_lines_coordinates.append([left, coord_border])
    else:
      self.crossroad_top_to_bottom_lines_coordinates = []
    
    # линии для слева направо
    line1 = self.addLineOnImage(frame_result.orig_img.copy(), "separating traffic left to right with pedestrian crossing")
    if (len(line1)):
      self.crossroad_left_to_right_lines_coordinates.append(line1)
    line2 = self.addLineOnImage(frame_result.orig_img.copy(), "pedestrian crossing on left to right")
    if (len(line2)):
      self.crossroad_left_to_right_lines_coordinates.append(line2)
    if (len(line2) and len(line1)):
      right, left, top, bottom = getRightLeftTopBottom(line1, line2)
      coord_border = find_fourth_point(left, right, bottom)
      self.area_coord_left_to_right.set_coords(
        top_left=left, 
        top_right=right, 
        bottom_left=coord_border, 
        bottom_right=bottom
      )
      self.crossroad_left_to_right_lines_coordinates.append([bottom, coord_border])
    else:
      self.crossroad_left_to_right_lines_coordinates = []
    
    # линии для снизу вверх
    line1 = self.addLineOnImage(frame_result.orig_img.copy(), "separating traffic bottom to top with pedestrian crossing")
    if (len(line1)):
      self.crossroad_bottom_to_top_lines_coordinates.append(line1)
    line2 = self.addLineOnImage(frame_result.orig_img.copy(), "pedestrian crossing on bottom to top")
    if (len(line2)):
      self.crossroad_bottom_to_top_lines_coordinates.append(line2)
    if (len(line2) and len(line1)):
      right, left, top, bottom = getRightLeftTopBottom(line2, line1)
      coord_border = find_fourth_point(bottom, top, right)
      self.area_coord_bottom_to_top.set_coords(
        top_left=top, 
        top_right=right, 
        bottom_left=bottom, 
        bottom_right=coord_border
      )
      self.crossroad_bottom_to_top_lines_coordinates.append([right, coord_border])
    else:
      self.crossroad_bottom_to_top_lines_coordinates = []

    if self.area_coord_bottom_to_top.is_any_none() == False and self.area_coord_left_to_right.is_any_none() == False and self.area_coord_top_to_bottom.is_any_none() ==False and self.area_coord_right_to_left.is_any_none() ==False:
      crossroad_top_right = getNextIntersectPoint(
        LineString(self.area_coord_right_to_left.get_left_coords(VerticalDirection.ToTop)),
        LineString(self.area_coord_top_to_bottom.get_bottom_coords(HorizontalDirection.ToRight))
                    )
      crossroad_top_left = getNextIntersectPoint(
        LineString(self.area_coord_left_to_right.get_right_coords(VerticalDirection.ToTop)),
        LineString(self.area_coord_top_to_bottom.get_bottom_coords(HorizontalDirection.ToLeft))
                    )
      crossroad_bottom_left = getNextIntersectPoint(
        LineString(self.area_coord_left_to_right.get_right_coords(VerticalDirection.ToBottom)),
        LineString(self.area_coord_bottom_to_top.get_top_coords(HorizontalDirection.ToLeft))
                    )
      crossroad_bottom_right = getNextIntersectPoint(
        LineString(self.area_coord_right_to_left.get_left_coords(VerticalDirection.ToBottom)),
        LineString(self.area_coord_bottom_to_top.get_top_coords(HorizontalDirection.ToRight))
                    )
      self.area_crossroad.set_coords(
          top_left=crossroad_top_left.coords[0], 
          top_right=crossroad_top_right.coords[0], 
          bottom_left=crossroad_bottom_left.coords[0], 
          bottom_right=crossroad_bottom_right.coords[0], 
        )
      self.save_lines_to_json(folder_to_save=folder_to_save)
  
  def getGreenLightModel(self, fileWithModelPath):
    if not os.path.exists(fileWithModelPath):
      print("Model NotFound")
      return None
    else:
      loaded_model = CatBoostClassifier()
      loaded_model.load_model("catboost_model.cbm")
      return loaded_model

  def maskVideoToImgs(self, fileName, folder_name, trained_model, second_to_switch = 5, showVideo=True, fileWithModelPath = 'catboost_model.cbm'):
    '''
    Сегментировать видео с сохранением изображений в отдельную папку
    fileName - путь до видео для сегментации
    folder_name - Название папки Для сохранения изображений
    trined_model - обученная модель для сегментации
    showVideo - показать обработанное видео в окне
    '''

    pathToVideoImages = self.videoImagesFolder + folder_name
    if not os.path.exists(pathToVideoImages):
      os.makedirs(pathToVideoImages)
    else:
      fileList = glob(pathToVideoImages+'/*')
      print("Number of files: ",len(fileList))
      for filePath in fileList:
        try:
            os.remove(filePath)
        except:
            print("Error while deleting file : ", filePath)

    print("обработанные кадры сохранятся в папку", pathToVideoImages, ". Если произошла ошибка, запустите makeVideo, чтобы собрать собранные кадры в видео")
    model = YOLO(str(trained_model.save_dir)+'/weights/best.pt')

    # Load the video file
    cap = cv2.VideoCapture(fileName)
    if not cap.isOpened():
        print(f"Error opening video file {fileName}")
        return
 
    # Initialize variables for FPS calculation
    prev_time = 0
 
    """
    Parameters of track method:
    source: str - path to video file or camera index
    tracker: str - tracker configuration file (e.g., 'bytetrack.yaml' or 'botsort.yaml')
    conf: float - confidence threshold for detections
    stream: bool - if True, yields frames one by one for real-time processing, 
                if False, processes the entire video at once
    """

    model_to_predict = self.getGreenLightModel(fileWithModelPath=fileWithModelPath)
    is_model_to_predict = model_to_predict is not None
    results = model.track(
        source=fileName, # path to video file 
        tracker=f'{self.tracker_choice}.yaml',  # 'bytetrack.yaml' or 'botsort.yaml'
        conf=0.25,   # confidence threshold                      
        stream=True # set it to True for continuous video processing                    
    )
    print(self.tracker_choice)
    curIm = 0
    fpsAvg = 0
    # loop through the results
    for frame_result in results:
        isSwitchFrame = curIm % 100 == 0
        isSwitchFrameX2 = curIm % 200 == 0
        isWriteInfoFrame = curIm % 50 == 0
        count_right_left = 0
        count_top_bottom = 0
        count_left_right = 0
        count_bottom_top = 0
        count_crossroad = 0
        if curIm == 0:
          if self.load_lines_from_json(folder_to_save=pathToVideoImages) == False:
            self.getLinesOnFrame(frame_result, pathToVideoImages)
        # print(frame_result)
        # Get the original frame
        img = frame_result.orig_img.copy()
        masks = []
        if (masks in frame_result):
          masks = frame_result.masks.data.cpu().numpy() 
 
        # Calculate FPS (fall back to input_fps until prev_time set)
        curr_time = time.time()
        fps = 1 / (curr_time - prev_time) if prev_time != 0 else cap.get(cv2.CAP_PROP_FPS)
        prev_time = curr_time

        # draw crossroad lines
        if (showVideo):
          self.drawSeparatorLines(img)
        # loop through the detected boxes and draw them on the frame
        for i, box in enumerate(frame_result.boxes):
            # Extract class
            cls = int(box.cls.cpu().item())
            """
            model.names is a dictionary mapping class indices to class names.
            {0: 'person',
            1: 'bicycle',
            2: 'car',
            3: 'motorcycle',
            ...,
            }
            """
            class_name = model.names[cls]
            # учитываем только необходимые
            if (np.any(np.array(self.arrayToDraw == class_name))):
              # Extract bounding box coordinates
              x1, y1, x2, y2 = map(int, box.xyxy.cpu().numpy()[0])
              # Extract confidence
              conf = box.conf.cpu().item()
              # Extract track ID 
              track_id = int(box.id.cpu().item()) if box.id is not None else -1

              if (showVideo and len(masks)):
                mask = masks[i]
                # Resize mask to original image size (often necessary if model resized input)
                mask_resized = cv2.resize(mask, (img.shape[1], img.shape[0]))
                
                # 3. Create a colored overlay
                color = [0, 255, 0]  # Green mask
                colored_mask = np.zeros_like(img, dtype=np.uint8)
                colored_mask[mask_resized > 0.5] = color
              
                # 4. Apply to image with transparency (0.5 weight)
                img = cv2.addWeighted(img, 1.0, colored_mask, 0.5, 0)
              box_top_left = (x1, y1)
              box_top_right = (x2, y1)
              box_bottom_right = (x2, y2)
              box_bottom_left = (x1, y2)
              box_area = AreaCoords(bottom_left=box_bottom_left, bottom_right=box_bottom_right,
                                    top_left=box_top_left, top_right=box_top_right)

              isColored = False
              
              box_coords = box_area.get_area_coords()
              # Цвет для закраски границы
              colorToBox = self.default_color
              if self.area_coord_right_to_left.is_any_none() == False:
                if self.checkIfObjectInsideCorrectArea(
                  box_coords=box_coords,
                  objectBox=box_area,
                  areaDirection=HorizontalDirection.ToLeft
                ):
                  self.addToDirectionSet(_set=self.objects_to_l, trackId=track_id)
                  self.addToDirectionCounter(_counter=self.objects_stuck_to_l, trackId=track_id, skipCheck=isSwitchFrame)
                  colorToBox = self.right_to_left_color
                  count_right_left += 1
                  isColored = True
              if isColored == False and self.area_coord_top_to_bottom.is_any_none() == False:
                if self.checkIfObjectInsideCorrectArea(
                  box_coords=box_coords,
                  objectBox=box_area,
                  areaDirection=VerticalDirection.ToBottom
                ):
                  self.addToDirectionSet(_set=self.objects_to_b, trackId=track_id)
                  self.addToDirectionCounter(_counter=self.objects_stuck_to_b, trackId=track_id, skipCheck=isSwitchFrame)
                  colorToBox = self.top_to_bottom_color
                  count_top_bottom += 1
                  isColored = True
              if isColored == False and self.area_coord_left_to_right.is_any_none() == False:
                if self.checkIfObjectInsideCorrectArea(
                  box_coords=box_coords,
                  objectBox=box_area,
                  areaDirection=HorizontalDirection.ToRight
                ):
                  self.addToDirectionSet(_set=self.objects_to_r, trackId=track_id)
                  self.addToDirectionCounter(_counter=self.objects_stuck_to_r, trackId=track_id, skipCheck=isSwitchFrame)
                  colorToBox = self.left_to_right_color
                  count_left_right += 1
                  isColored = True
              if isColored == False and self.area_coord_bottom_to_top.is_any_none() == False:
                if self.checkIfObjectInsideCorrectArea(
                  box_coords=box_coords,
                  objectBox=box_area,
                  areaDirection=VerticalDirection.ToTop
                ):
                  self.addToDirectionSet(_set=self.objects_to_t, trackId=track_id)
                  self.addToDirectionCounter(_counter=self.objects_stuck_to_t, trackId=track_id, skipCheck=isSwitchFrame)
                  count_bottom_top += 1
                  colorToBox = self.bottom_to_top_color
                  isColored = True
              if isColored == False and self.area_crossroad.is_any_none() == False:
                areaObject = self.area_crossroad
                # В случае, если объект касается области или находится внутри ее проверяем 
                if isIntersectOrInside(box_coords, areaObject.get_area_coords()):
                  self.addToMiddleCounter(trackId=track_id) if isSwitchFrame == False else self.addToDirectionCounter(_counter=self.objects_stuck_middle, trackId=track_id, skipCheck=isSwitchFrame)
                  count_crossroad += 1
                  colorToBox = self.area_crossroad_color
                  isColored = True
              if isColored == False:
                # возможно объект выехал из зоны наблюдения
                self.removeFromCounter(self.objects_stuck_middle, trackId=track_id)
              if (showVideo):  
                # Draw bounding box and label
                cv2.rectangle(img, (x1, y1), (x2, y2), colorToBox, 2)
                label = f"{class_name} ID:{track_id} {conf:.2f}"
                cv2.putText(img, label, (x1, y1 - 10),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.5, colorToBox, 2)
        if (isWriteInfoFrame):
          # Пока что рандомные числа 0 или 1 для следующего перекрестка
          # info_collected = {'time_of_info': curIm,
          #           'count_to_r': count_left_right,
          #           'count_to_l': count_right_left,
          #           'count_to_b': count_top_bottom,
          #           'count_to_t': count_bottom_top,
          #           'count_stuck_middle': self.getTrullyStuck(_counter=self.objects_stuck_middle),
          #           'count_stuck_to_r': self.getTrullyStuck(_counter=self.objects_stuck_to_r),
          #           'count_stuck_to_l': self.getTrullyStuck(_counter=self.objects_stuck_to_l),
          #           'count_stuck_to_b': self.getTrullyStuck(_counter=self.objects_stuck_to_b),
          #           'count_stuck_to_t': self.getTrullyStuck(_counter=self.objects_stuck_to_t),
          #           'is_jam_next_l': random.randint(0, 1),
          #           'is_jam_next_r': random.randint(0, 1),
          #           'is_jam_next_t': random.randint(0, 1),
          #           'is_jam_next_b': random.randint(0, 1),
          #           'is_green_horizontal': 1 if isSwitchFrameX2 else 0,
          #           'is_green_vertical': 0 if isSwitchFrameX2 else 1,
          #           'y': 1,
          # }
          # записываем информацию о ситуации на дороге в dataFrame
          info_collected = {'time_of_info': curIm,
                    'count_to_r': count_left_right,
                    'count_to_l': count_right_left,
                    'count_to_b': count_top_bottom,
                    'count_to_t': count_bottom_top,
                    'count_stuck_middle': self.getTrullyStuck(_counter=self.objects_stuck_middle),
                    'count_stuck_to_r': self.getTrullyStuck(_counter=self.objects_stuck_to_r),
                    'count_stuck_to_l': self.getTrullyStuck(_counter=self.objects_stuck_to_l),
                    'count_stuck_to_b': self.getTrullyStuck(_counter=self.objects_stuck_to_b),
                    'count_stuck_to_t': self.getTrullyStuck(_counter=self.objects_stuck_to_t),
                    'is_jam_next_l': 0,
                    'is_jam_next_r': 0,
                    'is_jam_next_t': 0,
                    'is_jam_next_b': 0,
                    'is_green_horizontal': 1 if isSwitchFrameX2 else 0,
                    'is_green_vertical': 0 if isSwitchFrameX2 else 1,
                    'y': 1,
          }
          dfInfo = pd.DataFrame(info_collected, index=[0])
          self.trafficInfoDF = pd.concat([self.trafficInfoDF, dfInfo], ignore_index=True)
          currentDirectionGreen = None
          if is_model_to_predict:
            X_to_pred = dfInfo[self.feature_cols]
            # y_to_pred = dfInfo[self.pred_col]  # 0, 1, 2
            pred = model_to_predict.predict(X_to_pred)[0]
            # print(pred)
            currentDirectionGreen = mapOfDirections[str(pred[0])]

        if (showVideo):           
          # Display tracker name and FPS on top-left corner
          cv2.putText(img, f"Tracker: {self.tracker_choice}", (10, 70),
                      cv2.FONT_HERSHEY_SIMPLEX, 2, self.info_color, 3)
          cv2.putText(img, f"FPS: {fps:.2f}", (10, 150),
                      cv2.FONT_HERSHEY_SIMPLEX, 2, self.info_color, 3)
          cv2.putText(img,
                      f"r-l: {count_right_left:.0f} | t-b: {count_top_bottom:.0f} | l-r: {count_left_right:.0f} | b-t: {count_bottom_top:.0f} | cross: {count_crossroad:.0f}", (10, 250),
                      cv2.FONT_HERSHEY_SIMPLEX, 1, self.info_color, 3)
          if currentDirectionGreen is not None:
            cv2.putText(img, f"switch to: {currentDirectionGreen}", (10, 350),
                      cv2.FONT_HERSHEY_SIMPLEX, 2, self.pred_color, 3)
          # Display the frame with detections  
          cv2.imshow('YOLOv26 Tracking', img)
          name_to_save = pathToVideoImages + "/" + str(curIm).zfill(32) + '.jpg'
          cv2.imwrite(name_to_save, img)
        # else:
        #   # Иначе показываем fps
        #   print(f"FPS: {fps:.2f} || r-l: {count_right_left:.0f} | t-b: {count_top_bottom:.0f} | l-r: {count_left_right:.0f} | b-t: {count_bottom_top:.0f}")
        if (curIm % 50 == 0):
          print("counters")
          print("mid", self.objects_stuck_middle)
          print("to_left", self.objects_stuck_to_l)
          print("to_right", self.objects_stuck_to_r)
          print("to_top", self.objects_stuck_to_t)
          print("to_bottom", self.objects_stuck_to_b)
          print("sets")
          print("to_left", self.objects_to_l)
          print("to_right", self.objects_to_r)
          print("to_top", self.objects_to_t)
          print("to_bottom", self.objects_to_b)
        curIm += 1
        fpsAvg += fps
        if curIm % 24 == 0:
          print(curIm)
        if cv2.waitKey(1) & 0xFF == ord('q'):
            print('avg FPS: ', fpsAvg/curIm)
            break
    
    # сохранение собранной информации в csv
    self.save_dataframe(folder_to_save=pathToVideoImages)

    print('avg FPS: ', fpsAvg/curIm)
    cap.release()
    cv2.destroyAllWindows()

In [35]:
classToconvertV2 = VideoConverterClassV2(pathToVideoFolder=pathToVideoFolder, videoImagesFolder=videoImagesFolder)

In [36]:
# import cv2
cv2.destroyAllWindows()

In [37]:
def print_time(func):
    # Start the timer
    start_time = time.perf_counter()

    func()

    # End the timer
    end_time = time.perf_counter()

    # Calculate and print execution time
    execution_time = end_time - start_time
    print(f"Execution time: {execution_time:.6f} seconds")

In [54]:
fileName = pathToVideoFolder + '4th_small.mp4'
folder_name = '4th-small-img'
# model_pred_green

In [39]:
def maskWithShowVideo():
    cv2.destroyAllWindows()
    classToconvertV2 = VideoConverterClassV2(pathToVideoFolder=pathToVideoFolder, videoImagesFolder=videoImagesFolder)
    classToconvertV2.maskVideoToImgs(fileName, folder_name, trained_model)
def maskWithShowVideoFalse():
    cv2.destroyAllWindows()
    classToconvertV2 = VideoConverterClassV2(pathToVideoFolder=pathToVideoFolder, videoImagesFolder=videoImagesFolder)
    classToconvertV2.maskVideoToImgs(fileName, folder_name, trained_model, showVideo=False)
def maskWithShowVideoFalseByteTrack():
    cv2.destroyAllWindows()
    classToconvertV2 = VideoConverterClassV2(pathToVideoFolder=pathToVideoFolder, videoImagesFolder=videoImagesFolder, tracker_choice='bytetrack')
    classToconvertV2.maskVideoToImgs(fileName, folder_name, trained_model, showVideo=False)
def maskWithShowVideoByteTrack():
    cv2.destroyAllWindows()
    classToconvertV2 = VideoConverterClassV2(pathToVideoFolder=pathToVideoFolder, videoImagesFolder=videoImagesFolder, tracker_choice='bytetrack')
    classToconvertV2.maskVideoToImgs(fileName, folder_name, trained_model)

In [55]:
print_time(maskWithShowVideo)

Number of files:  1035
Error while deleting file :  C:/Users/Yura Sannikov/Учеба/НИР-диплом26/Папка с кодомм/исходные/imagesFolder/4th-small-img\json_lines
обработанные кадры сохранятся в папку C:/Users/Yura Sannikov/Учеба/НИР-диплом26/Папка с кодомм/исходные/imagesFolder/4th-small-img . Если произошла ошибка, запустите makeVideo, чтобы собрать собранные кадры в видео
botsort

video 1/1 (frame 1/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 4 traffic lights, 18.2ms
lines loaded
counters
mid Counter({3: 1})
to_left Counter({5: 1, 6: 1, 7: 1, 8: 1, 9: 1, 12: 1, 14: 1, 16: 1, 19: 1})
to_right Counter({17: 1})
to_top Counter()
to_bottom Counter({4: 1})
sets
to_left {5, 6, 7, 8, 9, 12, 14, 16, 19}
to_right {17}
to_top set()
to_bottom {4}
video 1/1 (frame 2/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 4 traffic lights, 37.0ms
video 1/1 (frame 3/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 4 traffic lights, 36.5ms
video 1/1 (frame 4/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 4 traffic lights, 35.7ms
video 1/1 (frame 5/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 4 traffic lights, 35.3ms
video 1/1 (frame 6/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 5 traffic lights, 19.9ms
video 1/1 (frame 7/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 5 traffic lights, 16.2ms
video 1/1 (frame 8/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 5 traffic lights, 16.6ms
video 1/1 (frame 9/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 5 traffic lights, 18.9ms
video 1/1 (frame 10/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 5 traffic lights, 19.2ms
video 1/1 (frame 11/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 5 traffic lights, 16.7ms
video 1/1 (frame 12/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 5 traffic lights, 17.1ms
video 1/1 (frame 13/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 5 traffic lights, 15.7ms
video 1/1 (frame 14/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 13 cars, 1 bus, 1 truck, 5 traffic lights, 16.5ms
video 1/1 (frame 15/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 5 traffic lights, 16.3ms
video 1/1 (frame 16/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 5 traffic lights, 16.7ms
video 1/1 (frame 17/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 5 traffic lights, 19.7ms
video 1/1 (frame 18/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 12 cars, 1 bus, 1 truck, 5 traffic lights, 15.0ms
video 1/1 (frame 19/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 12 cars, 1 bus, 1 truck, 5 traffic lights, 19.8ms
video 1/1 (frame 20/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 4 traffic lights, 19.2ms
video 1/1 (frame 21/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 4 traffic lights, 16.2ms
video 1/1 (frame 22/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 13 cars, 1 bus, 1 truck, 4 traffic lights, 16.0ms
video 1/1 (frame 23/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 4 traffic lights, 16.2ms
video 1/1 (frame 24/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 5 traffic lights, 16.5ms
24
video 1/1 (frame 25/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 4 traffic lights, 15.6ms
video 1/1 (frame 26/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 13 cars, 1 bus, 1 truck, 5 traffic lights, 16.1ms
video 1/1 (frame 27/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 5 traffic lights, 16.0ms
video 1/1 (frame 28/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 5 traffic lights, 21.9ms
video 1/1 (frame 29/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 5 traffic lights, 31.4ms
video 1/1 (frame 30/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 5 traffic lights, 19.7ms
video 1/1 (frame 31/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 5 traffic lights, 16.3ms
video 1/1 (frame 32/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 5 traffic lights, 17.2ms
video 1/1 (frame 33/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 5 traffic lights, 18.8ms
video 1/1 (frame 34/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 5 traffic lights, 15.7ms
video 1/1 (frame 35/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 5 traffic lights, 15.6ms
video 1/1 (frame 36/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 12 cars, 1 bus, 1 truck, 5 traffic lights, 16.7ms
video 1/1 (frame 37/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 5 traffic lights, 18.6ms
video 1/1 (frame 38/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 5 traffic lights, 15.8ms
video 1/1 (frame 39/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 5 traffic lights, 15.8ms
video 1/1 (frame 40/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 5 traffic lights, 15.8ms
video 1/1 (frame 41/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 5 traffic lights, 15.7ms
video 1/1 (frame 42/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 16 cars, 1 bus, 1 truck, 5 traffic lights, 16.2ms
video 1/1 (frame 43/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 5 traffic lights, 15.0ms
video 1/1 (frame 44/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 12 cars, 1 bus, 1 truck, 5 traffic lights, 19.8ms
video 1/1 (frame 45/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.5ms
video 1/1 (frame 46/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 4 traffic lights, 15.7ms
video 1/1 (frame 47/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 4 traffic lights, 15.0ms
video 1/1 (frame 48/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 4 traffic lights, 15.7ms
48
video 1/1 (frame 49/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 4 traffic lights, 15.0ms
video 1/1 (frame 50/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 4 traffic lights, 16.3ms
video 1/1 (frame 51/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 16 cars, 1 bus, 1 truck, 4 traffic lights, 19.5ms
counters
mid Counter({3: 1, 17: 1})
to_left Counter({5: 1, 6: 1, 7: 1, 8: 1, 9: 1, 12: 1, 14: 1, 16: 1, 19: 1})
to_right Counter({11: 1})
to_top Counter()
to_bottom Counter({4: 1, 3: 1})
sets
to_left {5, 6, 7, 8, 9, 12, 14, 16, 19}
to_right {11}
to_top set()
to_bottom {3, 4}
video 1/1 (frame 52/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 4 traffic lights, 21.8ms
video 1/1 (frame 53/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 4 traffic lights, 17.6ms
video 1/1 (frame 54/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 4 traffic lights, 15.5ms
video 1/1 (frame 55/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 4 traffic lights, 15.4ms
video 1/1 (frame 56/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 4 traffic lights, 16.2ms
video 1/1 (frame 57/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 4 traffic lights, 15.7ms
video 1/1 (frame 58/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 4 traffic lights, 15.5ms
video 1/1 (frame 59/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 4 traffic lights, 15.7ms
video 1/1 (frame 60/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 4 traffic lights, 19.5ms
video 1/1 (frame 61/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 2 persons, 14 cars, 1 bus, 1 truck, 4 traffic lights, 16.4ms
video 1/1 (frame 62/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.8ms
video 1/1 (frame 63/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 2 persons, 13 cars, 1 bus, 1 truck, 4 traffic lights, 15.7ms
video 1/1 (frame 64/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 13 cars, 1 bus, 1 truck, 4 traffic lights, 17.4ms
video 1/1 (frame 65/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 13 cars, 1 bus, 1 truck, 4 traffic lights, 15.9ms
video 1/1 (frame 66/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 14.6ms
video 1/1 (frame 67/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 16.2ms
video 1/1 (frame 68/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 16.0ms
video 1/1 (frame 69/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.4ms
video 1/1 (frame 70/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.2ms
video 1/1 (frame 71/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 2 persons, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.7ms
video 1/1 (frame 72/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 2 persons, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.5ms
72
video 1/1 (frame 73/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 2 persons, 14 cars, 1 bus, 1 truck, 4 traffic lights, 21.7ms
video 1/1 (frame 74/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 16.8ms
video 1/1 (frame 75/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 16.3ms
video 1/1 (frame 76/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.7ms
video 1/1 (frame 77/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 19.3ms
video 1/1 (frame 78/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 16.2ms
video 1/1 (frame 79/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.6ms
video 1/1 (frame 80/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 16.5ms
video 1/1 (frame 81/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.5ms
video 1/1 (frame 82/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.6ms
video 1/1 (frame 83/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.3ms
video 1/1 (frame 84/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 16.3ms
video 1/1 (frame 85/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.3ms
video 1/1 (frame 86/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 5 traffic lights, 15.2ms
video 1/1 (frame 87/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 4 traffic lights, 18.5ms
video 1/1 (frame 88/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 5 traffic lights, 15.8ms
video 1/1 (frame 89/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 5 traffic lights, 16.0ms
video 1/1 (frame 90/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 5 traffic lights, 16.2ms
video 1/1 (frame 91/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.8ms
video 1/1 (frame 92/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.8ms
video 1/1 (frame 93/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 16.1ms
video 1/1 (frame 94/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.6ms
video 1/1 (frame 95/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.9ms
video 1/1 (frame 96/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.4ms
96
video 1/1 (frame 97/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.3ms
video 1/1 (frame 98/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 13 cars, 1 bus, 1 truck, 4 traffic lights, 15.8ms
video 1/1 (frame 99/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.9ms
video 1/1 (frame 100/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 4 traffic lights, 16.2ms
video 1/1 (frame 101/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.7ms
counters
mid Counter()
to_left Counter({5: 2, 6: 2, 7: 2, 8: 2, 9: 2, 12: 2, 14: 2, 16: 2, 19: 2})
to_right Counter({11: 2})
to_top Counter()
to_bottom Counter({4: 2, 3: 1})
sets
to_left {5, 6, 7, 8, 9, 12, 14, 16, 19}
to_right {11}
to_top set()
to_bottom {3, 4}
video 1/1 (frame 102/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.6ms
video 1/1 (frame 103/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.7ms
video 1/1 (frame 104/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.8ms
video 1/1 (frame 105/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 3 traffic lights, 16.2ms
video 1/1 (frame 106/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 4 traffic lights, 15.8ms
video 1/1 (frame 107/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 4 traffic lights, 15.6ms
video 1/1 (frame 108/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 3 traffic lights, 15.9ms
video 1/1 (frame 109/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 3 traffic lights, 16.1ms
video 1/1 (frame 110/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 13 cars, 1 bus, 1 truck, 3 traffic lights, 15.4ms
video 1/1 (frame 111/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 13 cars, 1 bus, 1 truck, 3 traffic lights, 16.0ms
video 1/1 (frame 112/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 3 traffic lights, 15.4ms
video 1/1 (frame 113/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 3 traffic lights, 25.4ms
video 1/1 (frame 114/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 3 traffic lights, 19.2ms
video 1/1 (frame 115/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 3 traffic lights, 18.5ms
video 1/1 (frame 116/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 3 traffic lights, 15.4ms
video 1/1 (frame 117/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 3 traffic lights, 17.7ms
video 1/1 (frame 118/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 14 cars, 1 bus, 1 truck, 3 traffic lights, 19.0ms
video 1/1 (frame 119/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 3 traffic lights, 15.4ms
video 1/1 (frame 120/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 3 traffic lights, 15.8ms
120
video 1/1 (frame 121/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 3 traffic lights, 15.8ms
video 1/1 (frame 122/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 3 traffic lights, 16.2ms
video 1/1 (frame 123/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 3 traffic lights, 16.3ms
video 1/1 (frame 124/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 12 cars, 1 bus, 1 truck, 3 traffic lights, 19.4ms
video 1/1 (frame 125/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 12 cars, 1 bus, 1 truck, 3 traffic lights, 19.1ms
video 1/1 (frame 126/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 13 cars, 1 bus, 1 truck, 3 traffic lights, 19.6ms
video 1/1 (frame 127/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 13 cars, 1 bus, 1 truck, 3 traffic lights, 15.9ms
video 1/1 (frame 128/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 12 cars, 1 bus, 1 truck, 3 traffic lights, 15.2ms
video 1/1 (frame 129/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 12 cars, 1 bus, 1 truck, 3 traffic lights, 15.2ms
video 1/1 (frame 130/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 12 cars, 2 buss, 1 truck, 3 traffic lights, 16.2ms
video 1/1 (frame 131/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 12 cars, 2 buss, 1 truck, 3 traffic lights, 15.4ms
video 1/1 (frame 132/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 13 cars, 1 truck, 4 traffic lights, 19.0ms
video 1/1 (frame 133/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 13 cars, 1 bus, 1 truck, 4 traffic lights, 15.3ms
video 1/1 (frame 134/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.6ms
video 1/1 (frame 135/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 13 cars, 1 bus, 1 truck, 4 traffic lights, 15.5ms
video 1/1 (frame 136/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 13 cars, 1 bus, 1 truck, 4 traffic lights, 16.1ms
video 1/1 (frame 137/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 14 cars, 1 bus, 1 truck, 4 traffic lights, 15.0ms
video 1/1 (frame 138/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 1 person, 15 cars, 1 bus, 1 truck, 4 traffic lights, 15.9ms

In [56]:
video_name = '4th-small-SegVidV2BotsortWithPreddiction.avi'
classToconvertV2.convertToVid(folder_name, video_name)

Images: ['00000000000000000000000000000000.jpg', '00000000000000000000000000000001.jpg', '00000000000000000000000000000002.jpg', '00000000000000000000000000000003.jpg', '00000000000000000000000000000004.jpg', '00000000000000000000000000000005.jpg', '00000000000000000000000000000006.jpg', '00000000000000000000000000000007.jpg', '00000000000000000000000000000008.jpg', '00000000000000000000000000000009.jpg', '00000000000000000000000000000010.jpg', '00000000000000000000000000000011.jpg', '00000000000000000000000000000012.jpg', '00000000000000000000000000000013.jpg', '00000000000000000000000000000014.jpg', '00000000000000000000000000000015.jpg', '00000000000000000000000000000016.jpg', '00000000000000000000000000000017.jpg', '00000000000000000000000000000018.jpg', '00000000000000000000000000000019.jpg', '00000000000000000000000000000020.jpg', '00000000000000000000000000000021.jpg', '00000000000000000000000000000022.jpg', '00000000000000000000000000000023.jpg', '00000000000000000000000000000024.jpg', '00000000000000000000000000000025.jpg', '00000000000000000000000000000026.jpg', '00000000000000000000000000000027.jpg', '00000000000000000000000000000028.jpg', '00000000000000000000000000000029.jpg', '00000000000000000000000000000030.jpg', '00000000000000000000000000000031.jpg', '00000000000000000000000000000032.jpg', '00000000000000000000000000000033.jpg', '00000000000000000000000000000034.jpg', '00000000000000000000000000000035.jpg', '00000000000000000000000000000036.jpg', '00000000000000000000000000000037.jpg', '00000000000000000000000000000038.jpg', '00000000000000000000000000000039.jpg', '00000000000000000000000000000040.jpg', '00000000000000000000000000000041.jpg', '00000000000000000000000000000042.jpg', '00000000000000000000000000000043.jpg', '00000000000000000000000000000044.jpg', '00000000000000000000000000000045.jpg', '00000000000000000000000000000046.jpg', '00000000000000000000000000000047.jpg', '00000000000000000000000000000048.jpg', '00000000000000000000000000000049.jpg', '00000000000000000000000000000050.jpg', '00000000000000000000000000000051.jpg', '00000000000000000000000000000052.jpg', '00000000000000000000000000000053.jpg', '00000000000000000000000000000054.jpg', '00000000000000000000000000000055.jpg', '00000000000000000000000000000056.jpg', '00000000000000000000000000000057.jpg', '00000000000000000000000000000058.jpg', '00000000000000000000000000000059.jpg', '00000000000000000000000000000060.jpg', '00000000000000000000000000000061.jpg', '00000000000000000000000000000062.jpg', '00000000000000000000000000000063.jpg', '00000000000000000000000000000064.jpg', '00000000000000000000000000000065.jpg', '00000000000000000000000000000066.jpg', '00000000000000000000000000000067.jpg', '00000000000000000000000000000068.jpg', '00000000000000000000000000000069.jpg', '00000000000000000000000000000070.jpg', '00000000000000000000000000000071.jpg', '00000000000000000000000000000072.jpg', '00000000000000000000000000000073.jpg', '00000000000000000000000000000074.jpg', '00000000000000000000000000000075.jpg', '00000000000000000000000000000076.jpg', '00000000000000000000000000000077.jpg', '00000000000000000000000000000078.jpg', '00000000000000000000000000000079.jpg', '00000000000000000000000000000080.jpg', '00000000000000000000000000000081.jpg', '00000000000000000000000000000082.jpg', '00000000000000000000000000000083.jpg', '00000000000000000000000000000084.jpg', '00000000000000000000000000000085.jpg', '00000000000000000000000000000086.jpg', '00000000000000000000000000000087.jpg', '00000000000000000000000000000088.jpg', '00000000000000000000000000000089.jpg', '00000000000000000000000000000090.jpg', '00000000000000000000000000000091.jpg', '00000000000000000000000000000092.jpg', '00000000000000000000000000000093.jpg', '00000000000000000000000000000094.jpg', '00000000000000000000000000000095.jpg', '00000000000000000000000000000096.jpg', '00000000000000000000000000000097.jpg', '00000000000000000000000000000098.jpg', '00000000000000000000000000000099.jpg', '00000000000000000000000000000100.jpg', '00000000000000000000000000000101.jpg', '00000000000000000000000000000102.jpg', '00000000000000000000000000000103.jpg', '00000000000000000000000000000104.jpg', '00000000000000000000000000000105.jpg', '00000000000000000000000000000106.jpg', '00000000000000000000000000000107.jpg', '00000000000000000000000000000108.jpg', '00000000000000000000000000000109.jpg', '00000000000000000000000000000110.jpg', '00000000000000000000000000000111.jpg', '00000000000000000000000000000112.jpg', '00000000000000000000000000000113.jpg', '00000000000000000000000000000114.jpg', '00000000000000000000000000000115.jpg', '00000000000000000000000000000116.jpg', '00000000000000000000000000000117.jpg', '00000000000000000000000000000118.jpg', '00000000000000000000000000000119.jpg', '00000000000000000000000000000120.jpg', '00000000000000000000000000000121.jpg', '00000000000000000000000000000122.jpg', '00000000000000000000000000000123.jpg', '00000000000000000000000000000124.jpg', '00000000000000000000000000000125.jpg', '00000000000000000000000000000126.jpg', '00000000000000000000000000000127.jpg', '00000000000000000000000000000128.jpg', '00000000000000000000000000000129.jpg', '00000000000000000000000000000130.jpg', '00000000000000000000000000000131.jpg', '00000000000000000000000000000132.jpg', '00000000000000000000000000000133.jpg', '00000000000000000000000000000134.jpg', '00000000000000000000000000000135.jpg', '00000000000000000000000000000136.jpg', '00000000000000000000000000000137.jpg', '00000000000000000000000000000138.jpg', '00000000000000000000000000000139.jpg', '00000000000000000000000000000140.jpg', '00000000000000000000000000000141.jpg', '00000000000000000000000000000142.jpg', '00000000000000000000000000000143.jpg', '00000000000000000000000000000144.jpg', '00000000000000000000000000000145.jpg', '00000000000000000000000000000146.jpg', '00000000000000000000000000000147.jpg', '00000000000000000000000000000148.jpg', '00000000000000000000000000000149.jpg', '00000000000000000000000000000150.jpg', '00000000000000000000000000000151.jpg', '00000000000000000000000000000152.jpg', '00000000000000000000000000000153.jpg', '00000000000000000000000000000154.jpg', '00000000000000000000000000000155.jpg', '00000000000000000000000000000156.jpg', '00000000000000000000000000000157.jpg', '00000000000000000000000000000158.jpg', '00000000000000000000000000000159.jpg', '00000000000000000000000000000160.jpg', '00000000000000000000000000000161.jpg', '00000000000000000000000000000162.jpg', '00000000000000000000000000000163.jpg', '00000000000000000000000000000164.jpg', '00000000000000000000000000000165.jpg', '00000000000000000000000000000166.jpg', '00000000000000000000000000000167.jpg', '00000000000000000000000000000168.jpg', '00000000000000000000000000000169.jpg', '00000000000000000000000000000170.jpg', '00000000000000000000000000000171.jpg', '00000000000000000000000000000172.jpg', '00000000000000000000000000000173.jpg', '00000000000000000000000000000174.jpg', '00000000000000000000000000000175.jpg', '00000000000000000000000000000176.jpg', '00000000000000000000000000000177.jpg', '00000000000000000000000000000178.jpg', '00000000000000000000000000000179.jpg', '00000000000000000000000000000180.jpg', '00000000000000000000000000000181.jpg', '00000000000000000000000000000182.jpg', '00000000000000000000000000000183.jpg', '00000000000000000000000000000184.jpg', '00000000000000000000000000000185.jpg', '00000000000000000000000000000186.jpg', '00000000000000000000000000000187.jpg', '00000000000000000000000000000188.jpg', '00000000000000000000000000000189.jpg', '00000000000000000000000000000190.jpg', '00000000000000000000000000000191.jpg', '00000000000000000000000000000192.jpg', '00000000000000000000000000000193.jpg', '00000000000000000000000000000194.jpg', '00000000000000000000000000000195.jpg', '00000000000000000000000000000196.jpg', '00000000000000000000000000000197.jpg', '00000000000000000000000000000198.jpg', '00000000000000000000000000000199.jpg', '00000000000000000000000000000200.jpg', '00000000000000000000000000000201.jpg', '00000000000000000000000000000202.jpg', '00000000000000000000000000000203.jpg', '00000000000000000000000000000204.jpg', '00000000000000000000000000000205.jpg', '00000000000000000000000000000206.jpg', '00000000000000000000000000000207.jpg', '00000000000000000000000000000208.jpg', '00000000000000000000000000000209.jpg', '00000000000000000000000000000210.jpg', '00000000000000000000000000000211.jpg', '00000000000000000000000000000212.jpg', '00000000000000000000000000000213.jpg', '00000000000000000000000000000214.jpg', '00000000000000000000000000000215.jpg', '00000000000000000000000000000216.jpg', '00000000000000000000000000000217.jpg', '00000000000000000000000000000218.jpg', '00000000000000000000000000000219.jpg', '00000000000000000000000000000220.jpg', '00000000000000000000000000000221.jpg', '00000000000000000000000000000222.jpg', '00000000000000000000000000000223.jpg', '00000000000000000000000000000224.jpg', '00000000000000000000000000000225.jpg', '00000000000000000000000000000226.jpg', '00000000000000000000000000000227.jpg', '00000000000000000000000000000228.jpg', '00000000000000000000000000000229.jpg', '00000000000000000000000000000230.jpg', '00000000000000000000000000000231.jpg', '00000000000000000000000000000232.jpg', '00000000000000000000000000000233.jpg', '00000000000000000000000000000234.jpg', '00000000000000000000000000000235.jpg', '00000000000000000000000000000236.jpg', '00000000000000000000000000000237.jpg', '00000000000000000000000000000238.jpg', '00000000000000000000000000000239.jpg', '00000000000000000000000000000240.jpg', '00000000000000000000000000000241.jpg', '00000000000000000000000000000242.jpg', '00000000000000000000000000000243.jpg', '00000000000000000000000000000244.jpg', '00000000000000000000000000000245.jpg', '00000000000000000000000000000246.jpg', '00000000000000000000000000000247.jpg', '00000000000000000000000000000248.jpg', '00000000000000000000000000000249.jpg', '00000000000000000000000000000250.jpg', '00000000000000000000000000000251.jpg', '00000000000000000000000000000252.jpg', '00000000000000000000000000000253.jpg', '00000000000000000000000000000254.jpg', '00000000000000000000000000000255.jpg', '00000000000000000000000000000256.jpg', '00000000000000000000000000000257.jpg', '00000000000000000000000000000258.jpg', '00000000000000000000000000000259.jpg', '00000000000000000000000000000260.jpg', '00000000000000000000000000000261.jpg', '00000000000000000000000000000262.jpg', '00000000000000000000000000000263.jpg', '00000000000000000000000000000264.jpg', '00000000000000000000000000000265.jpg', '00000000000000000000000000000266.jpg', '00000000000000000000000000000267.jpg', '00000000000000000000000000000268.jpg', '00000000000000000000000000000269.jpg', '00000000000000000000000000000270.jpg', '00000000000000000000000000000271.jpg', '00000000000000000000000000000272.jpg', '00000000000000000000000000000273.jpg', '00000000000000000000000000000274.jpg', '00000000000000000000000000000275.jpg', '00000000000000000000000000000276.jpg', '00000000000000000000000000000277.jpg', '00000000000000000000000000000278.jpg', '00000000000000000000000000000279.jpg', '00000000000000000000000000000280.jpg', '00000000000000000000000000000281.jpg', '00000000000000000000000000000282.jpg', '00000000000000000000000000000283.jpg', '00000000000000000000000000000284.jpg', '00000000000000000000000000000285.jpg', '00000000000000000000000000000286.jpg', '00000000000000000000000000000287.jpg', '00000000000000000000000000000288.jpg', '00000000000000000000000000000289.jpg', '00000000000000000000000000000290.jpg', '00000000000000000000000000000291.jpg', '00000000000000000000000000000292.jpg', '00000000000000000000000000000293.jpg', '00000000000000000000000000000294.jpg', '00000000000000000000000000000295.jpg', '00000000000000000000000000000296.jpg', '00000000000000000000000000000297.jpg', '00000000000000000000000000000298.jpg', '00000000000000000000000000000299.jpg', '00000000000000000000000000000300.jpg', '00000000000000000000000000000301.jpg', '00000000000000000000000000000302.jpg', '00000000000000000000000000000303.jpg', '00000000000000000000000000000304.jpg', '00000000000000000000000000000305.jpg', '00000000000000000000000000000306.jpg', '00000000000000000000000000000307.jpg', '00000000000000000000000000000308.jpg', '00000000000000000000000000000309.jpg', '00000000000000000000000000000310.jpg', '00000000000000000000000000000311.jpg', '00000000000000000000000000000312.jpg', '00000000000000000000000000000313.jpg', '00000000000000000000000000000314.jpg', '00000000000000000000000000000315.jpg', '00000000000000000000000000000316.jpg', '00000000000000000000000000000317.jpg', '00000000000000000000000000000318.jpg', '00000000000000000000000000000319.jpg', '00000000000000000000000000000320.jpg', '00000000000000000000000000000321.jpg', '00000000000000000000000000000322.jpg', '00000000000000000000000000000323.jpg', '00000000000000000000000000000324.jpg', '00000000000000000000000000000325.jpg', '00000000000000000000000000000326.jpg', '00000000000000000000000000000327.jpg', '00000000000000000000000000000328.jpg', '00000000000000000000000000000329.jpg', '00000000000000000000000000000330.jpg', '00000000000000000000000000000331.jpg', '00000000000000000000000000000332.jpg', '00000000000000000000000000000333.jpg', '00000000000000000000000000000334.jpg', '00000000000000000000000000000335.jpg', '00000000000000000000000000000336.jpg', '00000000000000000000000000000337.jpg', '00000000000000000000000000000338.jpg', '00000000000000000000000000000339.jpg', '00000000000000000000000000000340.jpg', '00000000000000000000000000000341.jpg', '00000000000000000000000000000342.jpg', '00000000000000000000000000000343.jpg', '00000000000000000000000000000344.jpg', '00000000000000000000000000000345.jpg', '00000000000000000000000000000346.jpg', '00000000000000000000000000000347.jpg', '00000000000000000000000000000348.jpg', '00000000000000000000000000000349.jpg', '00000000000000000000000000000350.jpg', '00000000000000000000000000000351.jpg', '00000000000000000000000000000352.jpg', '00000000000000000000000000000353.jpg', '00000000000000000000000000000354.jpg', '00000000000000000000000000000355.jpg', '00000000000000000000000000000356.jpg', '00000000000000000000000000000357.jpg', '00000000000000000000000000000358.jpg', '00000000000000000000000000000359.jpg', '00000000000000000000000000000360.jpg', '00000000000000000000000000000361.jpg', '00000000000000000000000000000362.jpg', '00000000000000000000000000000363.jpg', '00000000000000000000000000000364.jpg', '00000000000000000000000000000365.jpg', '00000000000000000000000000000366.jpg', '00000000000000000000000000000367.jpg', '00000000000000000000000000000368.jpg', '00000000000000000000000000000369.jpg', '00000000000000000000000000000370.jpg', '00000000000000000000000000000371.jpg', '00000000000000000000000000000372.jpg', '00000000000000000000000000000373.jpg', '00000000000000000000000000000374.jpg', '00000000000000000000000000000375.jpg', '00000000000000000000000000000376.jpg', '00000000000000000000000000000377.jpg', '00000000000000000000000000000378.jpg', '00000000000000000000000000000379.jpg', '00000000000000000000000000000380.jpg', '00000000000000000000000000000381.jpg', '00000000000000000000000000000382.jpg', '00000000000000000000000000000383.jpg', '00000000000000000000000000000384.jpg', '00000000000000000000000000000385.jpg', '00000000000000000000000000000386.jpg', '00000000000000000000000000000387.jpg', '00000000000000000000000000000388.jpg', '00000000000000000000000000000389.jpg', '00000000000000000000000000000390.jpg', '00000000000000000000000000000391.jpg', '00000000000000000000000000000392.jpg', '00000000000000000000000000000393.jpg', '00000000000000000000000000000394.jpg', '00000000000000000000000000000395.jpg', '00000000000000000000000000000396.jpg', '00000000000000000000000000000397.jpg', '00000000000000000000000000000398.jpg', '00000000000000000000000000000399.jpg', '00000000000000000000000000000400.jpg', '00000000000000000000000000000401.jpg', '00000000000000000000000000000402.jpg', '00000000000000000000000000000403.jpg', '00000000000000000000000000000404.jpg', '00000000000000000000000000000405.jpg', '00000000000000000000000000000406.jpg', '00000000000000000000000000000407.jpg', '00000000000000000000000000000408.jpg', '00000000000000000000000000000409.jpg', '00000000000000000000000000000410.jpg', '00000000000000000000000000000411.jpg', '00000000000000000000000000000412.jpg', '00000000000000000000000000000413.jpg', '00000000000000000000000000000414.jpg', '00000000000000000000000000000415.jpg', '00000000000000000000000000000416.jpg', '00000000000000000000000000000417.jpg', '00000000000000000000000000000418.jpg', '00000000000000000000000000000419.jpg', '00000000000000000000000000000420.jpg', '00000000000000000000000000000421.jpg', '00000000000000000000000000000422.jpg', '00000000000000000000000000000423.jpg', '00000000000000000000000000000424.jpg', '00000000000000000000000000000425.jpg', '00000000000000000000000000000426.jpg', '00000000000000000000000000000427.jpg', '00000000000000000000000000000428.jpg', '00000000000000000000000000000429.jpg', '00000000000000000000000000000430.jpg', '00000000000000000000000000000431.jpg', '00000000000000000000000000000432.jpg', '00000000000000000000000000000433.jpg', '00000000000000000000000000000434.jpg', '00000000000000000000000000000435.jpg', '00000000000000000000000000000436.jpg', '00000000000000000000000000000437.jpg', '00000000000000000000000000000438.jpg', '00000000000000000000000000000439.jpg', '00000000000000000000000000000440.jpg', '00000000000000000000000000000441.jpg', '00000000000000000000000000000442.jpg', '00000000000000000000000000000443.jpg', '00000000000000000000000000000444.jpg', '00000000000000000000000000000445.jpg', '00000000000000000000000000000446.jpg', '00000000000000000000000000000447.jpg', '00000000000000000000000000000448.jpg', '00000000000000000000000000000449.jpg', '00000000000000000000000000000450.jpg', '00000000000000000000000000000451.jpg', '00000000000000000000000000000452.jpg', '00000000000000000000000000000453.jpg', '00000000000000000000000000000454.jpg', '00000000000000000000000000000455.jpg', '00000000000000000000000000000456.jpg', '00000000000000000000000000000457.jpg', '00000000000000000000000000000458.jpg', '00000000000000000000000000000459.jpg', '00000000000000000000000000000460.jpg', '00000000000000000000000000000461.jpg', '00000000000000000000000000000462.jpg', '00000000000000000000000000000463.jpg', '00000000000000000000000000000464.jpg', '00000000000000000000000000000465.jpg', '00000000000000000000000000000466.jpg', '00000000000000000000000000000467.jpg', '00000000000000000000000000000468.jpg', '00000000000000000000000000000469.jpg', '00000000000000000000000000000470.jpg', '00000000000000000000000000000471.jpg', '00000000000000000000000000000472.jpg', '00000000000000000000000000000473.jpg', '00000000000000000000000000000474.jpg', '00000000000000000000000000000475.jpg', '00000000000000000000000000000476.jpg', '00000000000000000000000000000477.jpg', '00000000000000000000000000000478.jpg', '00000000000000000000000000000479.jpg', '00000000000000000000000000000480.jpg', '00000000000000000000000000000481.jpg', '00000000000000000000000000000482.jpg', '00000000000000000000000000000483.jpg', '00000000000000000000000000000484.jpg', '00000000000000000000000000000485.jpg', '00000000000000000000000000000486.jpg', '00000000000000000000000000000487.jpg', '00000000000000000000000000000488.jpg', '00000000000000000000000000000489.jpg', '00000000000000000000000000000490.jpg', '00000000000000000000000000000491.jpg', '00000000000000000000000000000492.jpg', '00000000000000000000000000000493.jpg', '00000000000000000000000000000494.jpg', '00000000000000000000000000000495.jpg', '00000000000000000000000000000496.jpg', '00000000000000000000000000000497.jpg', '00000000000000000000000000000498.jpg', '000000000000000000000000000004

In [ ]:
print_time(maskWithShowVideoByteTrack)

Number of files:  0
обработанные кадры сохранятся в папку C:/Users/Yura Sannikov/Учеба/НИР-диплом26/Папка с кодомм/исходные/imagesFolder/4th-small-img . Если произошла ошибка, запустите makeVideo, чтобы собрать собранные кадры в видео
bytetrack

video 1/1 (frame 1/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 384x640 15 cars, 1 bus, 1 truck, 4 traffic lights, 15.4ms
Starting: (1308, 664), Ending: (1564, 718)
[(1308, 664), (1564, 718)]
Starting: (1263, 701), Ending: (1363, 619)
[(1263, 701), (1363, 619)]
Starting: (1098, 523), Ending: (1300, 375)
[(1098, 523), (1300, 375)]
Starting: (979, 496), Ending: (1210, 546)
[(979, 496), (1210, 546)]
Starting: (740, 530), Ending: (380, 442)
[(740, 530), (380, 442)]
Starting: (673, 562), Ending: (798, 503)
[(673, 562), (798, 503)]
Starting: (779, 810), Ending: (484, 1072)
[(779, 810), (484, 1072)]
Starting: (683, 772), Ending: (889, 850)
[(683, 772), (889, 850)]
(865.2328645184263, 470.18728858821436)
[[     1397.3      590.91]
 [     865.23      470.19]]
[(779, 810), (484, 1072)]

error: OpenCV(4.13.0) :-1: error: (-5:Bad argument) in function 'line'
> Overload resolution failed:
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type
>  - Can't parse 'pt1'. Sequence item with index 0 has a wrong type

In [87]:
video_name = '4th-small-SegVidV2Bytetrack.avi'
classToconvertV2.convertToVid(folder_name, video_name)

Images: ['00000000000000000000000000000000.jpg', '00000000000000000000000000000001.jpg', '00000000000000000000000000000002.jpg', '00000000000000000000000000000003.jpg', '00000000000000000000000000000004.jpg', '00000000000000000000000000000005.jpg', '00000000000000000000000000000006.jpg', '00000000000000000000000000000007.jpg', '00000000000000000000000000000008.jpg', '00000000000000000000000000000009.jpg', '00000000000000000000000000000010.jpg', '00000000000000000000000000000011.jpg', '00000000000000000000000000000012.jpg', '00000000000000000000000000000013.jpg', '00000000000000000000000000000014.jpg', '00000000000000000000000000000015.jpg', '00000000000000000000000000000016.jpg', '00000000000000000000000000000017.jpg', '00000000000000000000000000000018.jpg', '00000000000000000000000000000019.jpg', '00000000000000000000000000000020.jpg', '00000000000000000000000000000021.jpg', '00000000000000000000000000000022.jpg', '00000000000000000000000000000023.jpg', '00000000000000000000000000000024.jpg', '00000000000000000000000000000025.jpg', '00000000000000000000000000000026.jpg', '00000000000000000000000000000027.jpg', '00000000000000000000000000000028.jpg', '00000000000000000000000000000029.jpg', '00000000000000000000000000000030.jpg', '00000000000000000000000000000031.jpg', '00000000000000000000000000000032.jpg', '00000000000000000000000000000033.jpg', '00000000000000000000000000000034.jpg', '00000000000000000000000000000035.jpg', '00000000000000000000000000000036.jpg', '00000000000000000000000000000037.jpg', '00000000000000000000000000000038.jpg', '00000000000000000000000000000039.jpg', '00000000000000000000000000000040.jpg', '00000000000000000000000000000041.jpg', '00000000000000000000000000000042.jpg', '00000000000000000000000000000043.jpg', '00000000000000000000000000000044.jpg', '00000000000000000000000000000045.jpg', '00000000000000000000000000000046.jpg', '00000000000000000000000000000047.jpg', '00000000000000000000000000000048.jpg', '00000000000000000000000000000049.jpg', '00000000000000000000000000000050.jpg', '00000000000000000000000000000051.jpg', '00000000000000000000000000000052.jpg', '00000000000000000000000000000053.jpg', '00000000000000000000000000000054.jpg', '00000000000000000000000000000055.jpg', '00000000000000000000000000000056.jpg', '00000000000000000000000000000057.jpg', '00000000000000000000000000000058.jpg', '00000000000000000000000000000059.jpg', '00000000000000000000000000000060.jpg', '00000000000000000000000000000061.jpg', '00000000000000000000000000000062.jpg', '00000000000000000000000000000063.jpg', '00000000000000000000000000000064.jpg', '00000000000000000000000000000065.jpg', '00000000000000000000000000000066.jpg', '00000000000000000000000000000067.jpg', '00000000000000000000000000000068.jpg', '00000000000000000000000000000069.jpg', '00000000000000000000000000000070.jpg', '00000000000000000000000000000071.jpg', '00000000000000000000000000000072.jpg', '00000000000000000000000000000073.jpg', '00000000000000000000000000000074.jpg', '00000000000000000000000000000075.jpg', '00000000000000000000000000000076.jpg', '00000000000000000000000000000077.jpg', '00000000000000000000000000000078.jpg', '00000000000000000000000000000079.jpg', '00000000000000000000000000000080.jpg', '00000000000000000000000000000081.jpg', '00000000000000000000000000000082.jpg', '00000000000000000000000000000083.jpg', '00000000000000000000000000000084.jpg', '00000000000000000000000000000085.jpg', '00000000000000000000000000000086.jpg', '00000000000000000000000000000087.jpg', '00000000000000000000000000000088.jpg', '00000000000000000000000000000089.jpg', '00000000000000000000000000000090.jpg', '00000000000000000000000000000091.jpg', '00000000000000000000000000000092.jpg', '00000000000000000000000000000093.jpg', '00000000000000000000000000000094.jpg', '00000000000000000000000000000095.jpg', '00000000000000000000000000000096.jpg', '00000000000000000000000000000097.jpg', '00000000000000000000000000000098.jpg', '00000000000000000000000000000099.jpg', '00000000000000000000000000000100.jpg', '00000000000000000000000000000101.jpg', '00000000000000000000000000000102.jpg', '00000000000000000000000000000103.jpg', '00000000000000000000000000000104.jpg', '00000000000000000000000000000105.jpg', '00000000000000000000000000000106.jpg', '00000000000000000000000000000107.jpg', '00000000000000000000000000000108.jpg', '00000000000000000000000000000109.jpg', '00000000000000000000000000000110.jpg', '00000000000000000000000000000111.jpg', '00000000000000000000000000000112.jpg', '00000000000000000000000000000113.jpg', '00000000000000000000000000000114.jpg', '00000000000000000000000000000115.jpg', '00000000000000000000000000000116.jpg', '00000000000000000000000000000117.jpg', '00000000000000000000000000000118.jpg', '00000000000000000000000000000119.jpg', '00000000000000000000000000000120.jpg', '00000000000000000000000000000121.jpg', '00000000000000000000000000000122.jpg', '00000000000000000000000000000123.jpg', '00000000000000000000000000000124.jpg', '00000000000000000000000000000125.jpg', '00000000000000000000000000000126.jpg', '00000000000000000000000000000127.jpg', '00000000000000000000000000000128.jpg', '00000000000000000000000000000129.jpg', '00000000000000000000000000000130.jpg', '00000000000000000000000000000131.jpg', '00000000000000000000000000000132.jpg', '00000000000000000000000000000133.jpg', '00000000000000000000000000000134.jpg', '00000000000000000000000000000135.jpg', '00000000000000000000000000000136.jpg', '00000000000000000000000000000137.jpg', '00000000000000000000000000000138.jpg', '00000000000000000000000000000139.jpg', '00000000000000000000000000000140.jpg', '00000000000000000000000000000141.jpg', '00000000000000000000000000000142.jpg', '00000000000000000000000000000143.jpg', '00000000000000000000000000000144.jpg', '00000000000000000000000000000145.jpg', '00000000000000000000000000000146.jpg', '00000000000000000000000000000147.jpg', '00000000000000000000000000000148.jpg', '00000000000000000000000000000149.jpg', '00000000000000000000000000000150.jpg', '00000000000000000000000000000151.jpg', '00000000000000000000000000000152.jpg', '00000000000000000000000000000153.jpg', '00000000000000000000000000000154.jpg', '00000000000000000000000000000155.jpg', '00000000000000000000000000000156.jpg', '00000000000000000000000000000157.jpg', '00000000000000000000000000000158.jpg', '00000000000000000000000000000159.jpg', '00000000000000000000000000000160.jpg', '00000000000000000000000000000161.jpg', '00000000000000000000000000000162.jpg', '00000000000000000000000000000163.jpg', '00000000000000000000000000000164.jpg', '00000000000000000000000000000165.jpg', '00000000000000000000000000000166.jpg', '00000000000000000000000000000167.jpg', '00000000000000000000000000000168.jpg', '00000000000000000000000000000169.jpg', '00000000000000000000000000000170.jpg', '00000000000000000000000000000171.jpg', '00000000000000000000000000000172.jpg', '00000000000000000000000000000173.jpg', '00000000000000000000000000000174.jpg', '00000000000000000000000000000175.jpg', '00000000000000000000000000000176.jpg', '00000000000000000000000000000177.jpg', '00000000000000000000000000000178.jpg', '00000000000000000000000000000179.jpg', '00000000000000000000000000000180.jpg', '00000000000000000000000000000181.jpg', '00000000000000000000000000000182.jpg', '00000000000000000000000000000183.jpg', '00000000000000000000000000000184.jpg', '00000000000000000000000000000185.jpg', '00000000000000000000000000000186.jpg', '00000000000000000000000000000187.jpg', '00000000000000000000000000000188.jpg', '00000000000000000000000000000189.jpg', '00000000000000000000000000000190.jpg', '00000000000000000000000000000191.jpg', '00000000000000000000000000000192.jpg', '00000000000000000000000000000193.jpg', '00000000000000000000000000000194.jpg', '00000000000000000000000000000195.jpg', '00000000000000000000000000000196.jpg', '00000000000000000000000000000197.jpg', '00000000000000000000000000000198.jpg', '00000000000000000000000000000199.jpg', '00000000000000000000000000000200.jpg', '00000000000000000000000000000201.jpg', '00000000000000000000000000000202.jpg', '00000000000000000000000000000203.jpg', '00000000000000000000000000000204.jpg', '00000000000000000000000000000205.jpg', '00000000000000000000000000000206.jpg', '00000000000000000000000000000207.jpg', '00000000000000000000000000000208.jpg', '00000000000000000000000000000209.jpg', '00000000000000000000000000000210.jpg', '00000000000000000000000000000211.jpg', '00000000000000000000000000000212.jpg', '00000000000000000000000000000213.jpg', '00000000000000000000000000000214.jpg', '00000000000000000000000000000215.jpg', '00000000000000000000000000000216.jpg', '00000000000000000000000000000217.jpg', '00000000000000000000000000000218.jpg', '00000000000000000000000000000219.jpg', '00000000000000000000000000000220.jpg', '00000000000000000000000000000221.jpg', '00000000000000000000000000000222.jpg', '00000000000000000000000000000223.jpg', '00000000000000000000000000000224.jpg', '00000000000000000000000000000225.jpg', '00000000000000000000000000000226.jpg', '00000000000000000000000000000227.jpg', '00000000000000000000000000000228.jpg', '00000000000000000000000000000229.jpg', '00000000000000000000000000000230.jpg', '00000000000000000000000000000231.jpg', '00000000000000000000000000000232.jpg', '00000000000000000000000000000233.jpg', '00000000000000000000000000000234.jpg', '00000000000000000000000000000235.jpg', '00000000000000000000000000000236.jpg', '00000000000000000000000000000237.jpg', '00000000000000000000000000000238.jpg', '00000000000000000000000000000239.jpg', '00000000000000000000000000000240.jpg', '00000000000000000000000000000241.jpg', '00000000000000000000000000000242.jpg', '00000000000000000000000000000243.jpg', '00000000000000000000000000000244.jpg', '00000000000000000000000000000245.jpg', '00000000000000000000000000000246.jpg', '00000000000000000000000000000247.jpg', '00000000000000000000000000000248.jpg', '00000000000000000000000000000249.jpg', '00000000000000000000000000000250.jpg', '00000000000000000000000000000251.jpg', '00000000000000000000000000000252.jpg', '00000000000000000000000000000253.jpg', '00000000000000000000000000000254.jpg', '00000000000000000000000000000255.jpg', '00000000000000000000000000000256.jpg', '00000000000000000000000000000257.jpg', '00000000000000000000000000000258.jpg', '00000000000000000000000000000259.jpg', '00000000000000000000000000000260.jpg', '00000000000000000000000000000261.jpg', '00000000000000000000000000000262.jpg', '00000000000000000000000000000263.jpg', '00000000000000000000000000000264.jpg', '00000000000000000000000000000265.jpg', '00000000000000000000000000000266.jpg', '00000000000000000000000000000267.jpg', '00000000000000000000000000000268.jpg', '00000000000000000000000000000269.jpg', '00000000000000000000000000000270.jpg', '00000000000000000000000000000271.jpg', '00000000000000000000000000000272.jpg', '00000000000000000000000000000273.jpg', '00000000000000000000000000000274.jpg', '00000000000000000000000000000275.jpg', '00000000000000000000000000000276.jpg', '00000000000000000000000000000277.jpg', '00000000000000000000000000000278.jpg', '00000000000000000000000000000279.jpg', '00000000000000000000000000000280.jpg', '00000000000000000000000000000281.jpg', '00000000000000000000000000000282.jpg', '00000000000000000000000000000283.jpg', '00000000000000000000000000000284.jpg', '00000000000000000000000000000285.jpg', '00000000000000000000000000000286.jpg', '00000000000000000000000000000287.jpg', '00000000000000000000000000000288.jpg', '00000000000000000000000000000289.jpg', '00000000000000000000000000000290.jpg', '00000000000000000000000000000291.jpg', '00000000000000000000000000000292.jpg', '00000000000000000000000000000293.jpg', '00000000000000000000000000000294.jpg', '00000000000000000000000000000295.jpg', '00000000000000000000000000000296.jpg', '00000000000000000000000000000297.jpg', '00000000000000000000000000000298.jpg', '00000000000000000000000000000299.jpg', '00000000000000000000000000000300.jpg', '00000000000000000000000000000301.jpg', '00000000000000000000000000000302.jpg', '00000000000000000000000000000303.jpg', '00000000000000000000000000000304.jpg', '00000000000000000000000000000305.jpg', '00000000000000000000000000000306.jpg', '00000000000000000000000000000307.jpg', '00000000000000000000000000000308.jpg', '00000000000000000000000000000309.jpg', '00000000000000000000000000000310.jpg', '00000000000000000000000000000311.jpg', '00000000000000000000000000000312.jpg', '00000000000000000000000000000313.jpg', '00000000000000000000000000000314.jpg', '00000000000000000000000000000315.jpg', '00000000000000000000000000000316.jpg', '00000000000000000000000000000317.jpg', '00000000000000000000000000000318.jpg', '00000000000000000000000000000319.jpg', '00000000000000000000000000000320.jpg', '00000000000000000000000000000321.jpg', '00000000000000000000000000000322.jpg', '00000000000000000000000000000323.jpg', '00000000000000000000000000000324.jpg', '00000000000000000000000000000325.jpg', '00000000000000000000000000000326.jpg', '00000000000000000000000000000327.jpg', '00000000000000000000000000000328.jpg', '00000000000000000000000000000329.jpg', '00000000000000000000000000000330.jpg', '00000000000000000000000000000331.jpg', '00000000000000000000000000000332.jpg', '00000000000000000000000000000333.jpg', '00000000000000000000000000000334.jpg', '00000000000000000000000000000335.jpg', '00000000000000000000000000000336.jpg', '00000000000000000000000000000337.jpg', '00000000000000000000000000000338.jpg', '00000000000000000000000000000339.jpg', '00000000000000000000000000000340.jpg', '00000000000000000000000000000341.jpg', '00000000000000000000000000000342.jpg', '00000000000000000000000000000343.jpg', '00000000000000000000000000000344.jpg', '00000000000000000000000000000345.jpg', '00000000000000000000000000000346.jpg', '00000000000000000000000000000347.jpg', '00000000000000000000000000000348.jpg', '00000000000000000000000000000349.jpg', '00000000000000000000000000000350.jpg', '00000000000000000000000000000351.jpg', '00000000000000000000000000000352.jpg', '00000000000000000000000000000353.jpg', '00000000000000000000000000000354.jpg', '00000000000000000000000000000355.jpg', '00000000000000000000000000000356.jpg', '00000000000000000000000000000357.jpg', '00000000000000000000000000000358.jpg', '00000000000000000000000000000359.jpg', '00000000000000000000000000000360.jpg', '00000000000000000000000000000361.jpg', '00000000000000000000000000000362.jpg', '00000000000000000000000000000363.jpg', '00000000000000000000000000000364.jpg', '00000000000000000000000000000365.jpg', '00000000000000000000000000000366.jpg', '00000000000000000000000000000367.jpg', '00000000000000000000000000000368.jpg', '00000000000000000000000000000369.jpg', '00000000000000000000000000000370.jpg', '00000000000000000000000000000371.jpg', '00000000000000000000000000000372.jpg', '00000000000000000000000000000373.jpg', '00000000000000000000000000000374.jpg', '00000000000000000000000000000375.jpg', '00000000000000000000000000000376.jpg', '00000000000000000000000000000377.jpg', '00000000000000000000000000000378.jpg', '00000000000000000000000000000379.jpg', '00000000000000000000000000000380.jpg', '00000000000000000000000000000381.jpg', '00000000000000000000000000000382.jpg', '00000000000000000000000000000383.jpg', '00000000000000000000000000000384.jpg', '00000000000000000000000000000385.jpg', '00000000000000000000000000000386.jpg', '00000000000000000000000000000387.jpg', '00000000000000000000000000000388.jpg', '00000000000000000000000000000389.jpg', '00000000000000000000000000000390.jpg', '00000000000000000000000000000391.jpg', '00000000000000000000000000000392.jpg', '00000000000000000000000000000393.jpg', '00000000000000000000000000000394.jpg', '00000000000000000000000000000395.jpg', '00000000000000000000000000000396.jpg', '00000000000000000000000000000397.jpg', '00000000000000000000000000000398.jpg', '00000000000000000000000000000399.jpg', '00000000000000000000000000000400.jpg', '00000000000000000000000000000401.jpg', '00000000000000000000000000000402.jpg', '00000000000000000000000000000403.jpg', '00000000000000000000000000000404.jpg', '00000000000000000000000000000405.jpg', '00000000000000000000000000000406.jpg', '00000000000000000000000000000407.jpg', '00000000000000000000000000000408.jpg', '00000000000000000000000000000409.jpg', '00000000000000000000000000000410.jpg', '00000000000000000000000000000411.jpg', '00000000000000000000000000000412.jpg', '00000000000000000000000000000413.jpg', '00000000000000000000000000000414.jpg', '00000000000000000000000000000415.jpg', '00000000000000000000000000000416.jpg', '00000000000000000000000000000417.jpg', '00000000000000000000000000000418.jpg', '00000000000000000000000000000419.jpg', '00000000000000000000000000000420.jpg', '00000000000000000000000000000421.jpg', '00000000000000000000000000000422.jpg', '00000000000000000000000000000423.jpg', '00000000000000000000000000000424.jpg', '00000000000000000000000000000425.jpg', '00000000000000000000000000000426.jpg', '00000000000000000000000000000427.jpg', '00000000000000000000000000000428.jpg', '00000000000000000000000000000429.jpg', '00000000000000000000000000000430.jpg', '00000000000000000000000000000431.jpg', '00000000000000000000000000000432.jpg', '00000000000000000000000000000433.jpg', '00000000000000000000000000000434.jpg', '00000000000000000000000000000435.jpg', '00000000000000000000000000000436.jpg', '00000000000000000000000000000437.jpg', '00000000000000000000000000000438.jpg', '00000000000000000000000000000439.jpg', '00000000000000000000000000000440.jpg', '00000000000000000000000000000441.jpg', '00000000000000000000000000000442.jpg', '00000000000000000000000000000443.jpg', '00000000000000000000000000000444.jpg', '00000000000000000000000000000445.jpg', '00000000000000000000000000000446.jpg', '00000000000000000000000000000447.jpg', '00000000000000000000000000000448.jpg', '00000000000000000000000000000449.jpg', '00000000000000000000000000000450.jpg', '00000000000000000000000000000451.jpg', '00000000000000000000000000000452.jpg', '00000000000000000000000000000453.jpg', '00000000000000000000000000000454.jpg', '00000000000000000000000000000455.jpg', '00000000000000000000000000000456.jpg', '00000000000000000000000000000457.jpg', '00000000000000000000000000000458.jpg', '00000000000000000000000000000459.jpg', '00000000000000000000000000000460.jpg', '00000000000000000000000000000461.jpg', '00000000000000000000000000000462.jpg', '00000000000000000000000000000463.jpg', '00000000000000000000000000000464.jpg', '00000000000000000000000000000465.jpg', '00000000000000000000000000000466.jpg', '00000000000000000000000000000467.jpg', '00000000000000000000000000000468.jpg', '00000000000000000000000000000469.jpg', '00000000000000000000000000000470.jpg', '00000000000000000000000000000471.jpg', '00000000000000000000000000000472.jpg', '00000000000000000000000000000473.jpg', '00000000000000000000000000000474.jpg', '00000000000000000000000000000475.jpg', '00000000000000000000000000000476.jpg', '00000000000000000000000000000477.jpg', '00000000000000000000000000000478.jpg', '00000000000000000000000000000479.jpg', '00000000000000000000000000000480.jpg', '00000000000000000000000000000481.jpg', '00000000000000000000000000000482.jpg', '00000000000000000000000000000483.jpg', '00000000000000000000000000000484.jpg', '00000000000000000000000000000485.jpg', '00000000000000000000000000000486.jpg', '00000000000000000000000000000487.jpg', '00000000000000000000000000000488.jpg', '00000000000000000000000000000489.jpg', '00000000000000000000000000000490.jpg', '00000000000000000000000000000491.jpg', '00000000000000000000000000000492.jpg', '00000000000000000000000000000493.jpg', '00000000000000000000000000000494.jpg', '00000000000000000000000000000495.jpg', '00000000000000000000000000000496.jpg', '00000000000000000000000000000497.jpg', '00000000000000000000000000000498.jpg', '000000000000000000000000000004

In [88]:
print_time(maskWithShowVideoFalse)

Number of files:  1034
обработанные кадры сохранятся в папку C:/Users/Yura Sannikov/Учеба/НИР-диплом26/Папка с кодомм/исходные/imagesFolder/4th-small-img . Если произошла ошибка, запустите makeVideo, чтобы собрать собранные кадры в видео
botsort

video 1/1 (frame 1/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 2 traffic lights, 28.7ms
Starting: (1307, 664), Ending: (1915, 801)
[(1307, 664), (1915, 801)]
Starting: (1259, 706), Ending: (1353, 625)
[(1259, 706), (1353, 625)]
Starting: (1103, 524), Ending: (1329, 350)
[(1103, 524), (1329, 350)]
Starting: (976, 495), Ending: (1219, 548)
[(976, 495), (1219, 548)]
Starting: (736, 534), Ending: (284, 425)
[(736, 534), (284, 425)]
Starting: (678, 557), Ending: (803, 495)
[(678, 557), (803, 495)]
Starting: (773, 807), Ending: (482, 1077)
[(773, 807), (482, 1077)]
Starting: (682, 778), Ending: (881, 847)
[(682, 778), (881, 847)]
video 1/1 (frame 2/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 2 traffic lights, 40.8ms
video 1/1 (frame 3/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 23.0ms
video 1/1 (frame 4/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 2 traffic lights, 22.6ms
video 1/1 (frame 5/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 22.8ms
video 1/1 (frame 6/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 15.4ms
video 1/1 (frame 7/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 15.2ms
video 1/1 (frame 8/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 15.1ms
video 1/1 (frame 9/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 1 traffic light, 17.8ms
video 1/1 (frame 10/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 21.8ms
video 1/1 (frame 11/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 23.2ms
video 1/1 (frame 12/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 22.0ms
video 1/1 (frame 13/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 21.5ms
video 1/1 (frame 14/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 16.1ms
video 1/1 (frame 15/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 16.0ms
video 1/1 (frame 16/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 18.4ms
video 1/1 (frame 17/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 20.2ms
video 1/1 (frame 18/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 15.6ms
video 1/1 (frame 19/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 17.1ms
video 1/1 (frame 20/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 15.9ms
video 1/1 (frame 21/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 17.3ms
video 1/1 (frame 22/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 1 traffic light, 17.3ms
video 1/1 (frame 23/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 15.5ms
video 1/1 (frame 24/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 22.6ms
24
video 1/1 (frame 25/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 1 traffic light, 15.6ms
video 1/1 (frame 26/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 1 traffic light, 14.9ms
video 1/1 (frame 27/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 1 traffic light, 27.4ms
video 1/1 (frame 28/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 15.4ms
video 1/1 (frame 29/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 14.5ms
video 1/1 (frame 30/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 1 traffic light, 17.5ms
video 1/1 (frame 31/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 14.5ms
video 1/1 (frame 32/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 20.0ms
video 1/1 (frame 33/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 14.8ms
video 1/1 (frame 34/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 1 traffic light, 17.0ms
video 1/1 (frame 35/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 1 traffic light, 18.3ms
video 1/1 (frame 36/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 18.0ms
video 1/1 (frame 37/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 17.1ms
video 1/1 (frame 38/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 19.0ms
video 1/1 (frame 39/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 17.3ms
video 1/1 (frame 40/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 17.4ms
video 1/1 (frame 41/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 17.6ms
video 1/1 (frame 42/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 16.3ms
video 1/1 (frame 43/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 14.5ms
video 1/1 (frame 44/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 18.0ms
video 1/1 (frame 45/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 18.7ms
video 1/1 (frame 46/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 2 traffic lights, 16.5ms
video 1/1 (frame 47/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 2 traffic lights, 17.7ms
video 1/1 (frame 48/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 2 traffic lights, 19.6ms
48
video 1/1 (frame 49/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 9 cars, 1 bus, 1 truck, 2 traffic lights, 17.7ms
video 1/1 (frame 50/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 2 traffic lights, 17.3ms
video 1/1 (frame 51/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 1 traffic light, 15.6ms
video 1/1 (frame 52/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 27.8ms
video 1/1 (frame 53/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 2 traffic lights, 17.1ms
video 1/1 (frame 54/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 2 traffic lights, 14.8ms
video 1/1 (frame 55/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 2 traffic lights, 15.4ms
video 1/1 (frame 56/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 2 traffic lights, 21.2ms
video 1/1 (frame 57/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 15.6ms
video 1/1 (frame 58/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 15.1ms
video 1/1 (frame 59/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 14.7ms
video 1/1 (frame 60/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 15.8ms
video 1/1 (frame 61/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 19.7ms
video 1/1 (frame 62/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 17.1ms
video 1/1 (frame 63/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 16.8ms
video 1/1 (frame 64/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 15.0ms
video 1/1 (frame 65/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 3 traffic lights, 17.8ms
video 1/1 (frame 66/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 15.8ms
video 1/1 (frame 67/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 14.9ms
video 1/1 (frame 68/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 17.6ms
video 1/1 (frame 69/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 4 traffic lights, 18.6ms
video 1/1 (frame 70/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 4 traffic lights, 16.3ms
video 1/1 (frame 71/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 4 traffic lights, 14.8ms
video 1/1 (frame 72/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 4 traffic lights, 16.2ms
72
video 1/1 (frame 73/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 17.6ms
video 1/1 (frame 74/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 14.5ms
video 1/1 (frame 75/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 16.5ms
video 1/1 (frame 76/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 15.4ms
video 1/1 (frame 77/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 15.1ms
video 1/1 (frame 78/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 14.9ms
video 1/1 (frame 79/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 15.0ms
video 1/1 (frame 80/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 15.1ms
video 1/1 (frame 81/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 19.1ms
video 1/1 (frame 82/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 4 traffic lights, 16.0ms
video 1/1 (frame 83/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 4 traffic lights, 14.8ms
video 1/1 (frame 84/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 4 traffic lights, 18.2ms
video 1/1 (frame 85/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 4 traffic lights, 14.5ms
video 1/1 (frame 86/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 3 traffic lights, 17.9ms
video 1/1 (frame 87/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 3 traffic lights, 14.4ms
video 1/1 (frame 88/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 3 traffic lights, 15.5ms
video 1/1 (frame 89/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 17.6ms
video 1/1 (frame 90/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 15.0ms
video 1/1 (frame 91/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 15.0ms
video 1/1 (frame 92/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 14.7ms
video 1/1 (frame 93/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 3 traffic lights, 17.8ms
video 1/1 (frame 94/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 3 traffic lights, 15.0ms
video 1/1 (frame 95/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 14.2ms
video 1/1 (frame 96/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 21.5ms
96
video 1/1 (frame 97/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 15.3ms
video 1/1 (frame 98/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 3 traffic lights, 14.9ms
video 1/1 (frame 99/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 18.6ms
video 1/1 (frame 100/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 3 traffic lights, 14.9ms
video 1/1 (frame 101/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 3 traffic lights, 14.8ms
video 1/1 (frame 102/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 14.6ms
video 1/1 (frame 103/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 3 traffic lights, 14.8ms
video 1/1 (frame 104/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 2 traffic lights, 18.6ms
video 1/1 (frame 105/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 2 traffic lights, 14.9ms
video 1/1 (frame 106/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 2 traffic lights, 17.4ms
video 1/1 (frame 107/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 2 traffic lights, 21.3ms
video 1/1 (frame 108/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 2 traffic lights, 14.8ms
video 1/1 (frame 109/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 2 traffic lights, 18.5ms
video 1/1 (frame 110/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 2 traffic lights, 14.9ms
video 1/1 (frame 111/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 2 traffic lights, 21.4ms
video 1/1 (frame 112/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 18.7ms
video 1/1 (frame 113/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 3 traffic lights, 15.6ms
video 1/1 (frame 114/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 17.3ms
video 1/1 (frame 115/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 16.7ms
video 1/1 (frame 116/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 3 traffic lights, 16.3ms
video 1/1 (frame 117/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 4 traffic lights, 16.6ms
video 1/1 (frame 118/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 4 traffic lights, 19.5ms
video 1/1 (frame 119/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 4 traffic lights, 18.2ms
video 1/1 (frame 120/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 4 traffic lights, 17.9ms
120
video 1/1 (frame 121/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 3 traffic lights, 16.1ms
video 1/1 (frame 122/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 3 traffic lights, 16.3ms
video 1/1 (frame 123/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 4 traffic lights, 23.0ms
video 1/1 (frame 124/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 4 traffic lights, 19.5ms
video 1/1 (frame 125/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 3 traffic lights, 15.9ms
video 1/1 (frame 126/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 2 traffic lights, 16.3ms
video 1/1 (frame 127/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 2 traffic lights, 18.6ms
video 1/1 (frame 128/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 2 traffic lights, 17.8ms
video 1/1 (frame 129/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 1 traffic light, 15.6ms
video 1/1 (frame 130/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 1 traffic light, 14.2ms
video 1/1 (frame 131/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 2 traffic lights, 15.0ms
video 1/1 (frame 132/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 2 traffic lights, 14.7ms
video 1/1 (frame 133/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 2 traffic lights, 17.0ms
video 1/1 (frame 134/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 15.1ms
video 1/1 (frame 135/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 16.8ms
video 1/1 (frame 136/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 15.9ms
video 1/1 (frame 137/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 18.1ms
video 1/1 (frame 138/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 1 traffic light, 16.8ms
video 1/1 (frame 139/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 1 traffic light, 18.2ms
video 1/1 (frame 140/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 15.1ms
video 1/1 (frame 141/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 14.6ms
video 1/1 (frame 142/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 1 traffic light, 15.9ms
video 1/1 (frame 143/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 1 traffic light, 15.7ms
video 1/1 (frame 144/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 15.4ms
144
video 1/1 (frame 145/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 14.8ms
video 1/1 (frame 146/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 2 traffic lights, 16.3ms
video 1/1 (frame 147/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 2 traffic lights, 18.1ms

In [89]:
print_time(maskWithShowVideoFalseByteTrack)

Number of files:  0
обработанные кадры сохранятся в папку C:/Users/Yura Sannikov/Учеба/НИР-диплом26/Папка с кодомм/исходные/imagesFolder/4th-small-img . Если произошла ошибка, запустите makeVideo, чтобы собрать собранные кадры в видео
bytetrack

video 1/1 (frame 1/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 2 traffic lights, 26.5ms
Starting: (1304, 663), Ending: (1913, 804)
[(1304, 663), (1913, 804)]
Starting: (1261, 706), Ending: (1350, 629)
[(1261, 706), (1350, 629)]
Starting: (1101, 525), Ending: (1326, 362)
[(1101, 525), (1326, 362)]
Starting: (978, 495), Ending: (1215, 549)
[(978, 495), (1215, 549)]
Starting: (739, 532), Ending: (315, 435)
[(739, 532), (315, 435)]
Starting: (673, 561), Ending: (809, 499)
[(673, 561), (809, 499)]
Starting: (774, 812), Ending: (488, 1073)
[(774, 812), (488, 1073)]
Starting: (684, 781), Ending: (878, 849)
[(684, 781), (878, 849)]
video 1/1 (frame 2/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 2 traffic lights, 41.2ms
video 1/1 (frame 3/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 22.9ms
video 1/1 (frame 4/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 2 traffic lights, 24.4ms
video 1/1 (frame 5/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 23.5ms
video 1/1 (frame 6/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 26.0ms
video 1/1 (frame 7/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 19.1ms
video 1/1 (frame 8/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 15.4ms
video 1/1 (frame 9/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 1 traffic light, 19.4ms
video 1/1 (frame 10/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 14.9ms
video 1/1 (frame 11/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 15.1ms
video 1/1 (frame 12/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 14.4ms
video 1/1 (frame 13/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 24.5ms
video 1/1 (frame 14/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 16.0ms
video 1/1 (frame 15/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 18.3ms
video 1/1 (frame 16/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 16.4ms
video 1/1 (frame 17/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 15.0ms
video 1/1 (frame 18/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 16.4ms
video 1/1 (frame 19/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 16.0ms
video 1/1 (frame 20/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 16.4ms
video 1/1 (frame 21/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 15.7ms
video 1/1 (frame 22/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 1 traffic light, 22.0ms
video 1/1 (frame 23/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 16.3ms
video 1/1 (frame 24/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 17.3ms
24
video 1/1 (frame 25/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 1 traffic light, 16.1ms
video 1/1 (frame 26/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 1 traffic light, 15.2ms
video 1/1 (frame 27/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 1 traffic light, 15.0ms
video 1/1 (frame 28/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 15.0ms
video 1/1 (frame 29/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 14.3ms
video 1/1 (frame 30/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 1 traffic light, 15.9ms
video 1/1 (frame 31/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 14.4ms
video 1/1 (frame 32/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 15.5ms
video 1/1 (frame 33/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 17.9ms
video 1/1 (frame 34/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 1 traffic light, 19.4ms
video 1/1 (frame 35/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 1 traffic light, 15.7ms
video 1/1 (frame 36/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 15.6ms
video 1/1 (frame 37/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 14.4ms
video 1/1 (frame 38/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 20.2ms
video 1/1 (frame 39/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 16.0ms
video 1/1 (frame 40/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 14.9ms
video 1/1 (frame 41/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 21.4ms
video 1/1 (frame 42/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 15.0ms
video 1/1 (frame 43/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 14.3ms
video 1/1 (frame 44/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 15.1ms
video 1/1 (frame 45/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 1 traffic light, 15.1ms
video 1/1 (frame 46/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 2 traffic lights, 15.2ms
video 1/1 (frame 47/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 2 traffic lights, 21.7ms
video 1/1 (frame 48/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 2 traffic lights, 17.5ms
48
video 1/1 (frame 49/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 9 cars, 1 bus, 1 truck, 2 traffic lights, 19.5ms
video 1/1 (frame 50/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 2 traffic lights, 17.7ms
video 1/1 (frame 51/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 1 traffic light, 16.4ms
video 1/1 (frame 52/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 2 traffic lights, 17.5ms
video 1/1 (frame 53/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 2 traffic lights, 17.9ms
video 1/1 (frame 54/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 2 traffic lights, 17.3ms
video 1/1 (frame 55/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 2 traffic lights, 16.0ms
video 1/1 (frame 56/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 2 traffic lights, 16.6ms
video 1/1 (frame 57/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 17.2ms
video 1/1 (frame 58/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 17.4ms
video 1/1 (frame 59/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 16.4ms
video 1/1 (frame 60/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 17.9ms
video 1/1 (frame 61/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 16.5ms
video 1/1 (frame 62/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 15.7ms
video 1/1 (frame 63/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 16.0ms
video 1/1 (frame 64/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 14.9ms
video 1/1 (frame 65/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 3 traffic lights, 24.3ms
video 1/1 (frame 66/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 15.7ms
video 1/1 (frame 67/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 21.2ms
video 1/1 (frame 68/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 14.8ms
video 1/1 (frame 69/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 4 traffic lights, 22.2ms
video 1/1 (frame 70/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 4 traffic lights, 15.1ms
video 1/1 (frame 71/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 4 traffic lights, 14.6ms
video 1/1 (frame 72/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 4 traffic lights, 17.6ms
72
video 1/1 (frame 73/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 18.7ms
video 1/1 (frame 74/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 16.3ms
video 1/1 (frame 75/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 16.9ms
video 1/1 (frame 76/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 24.2ms
video 1/1 (frame 77/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 20.8ms
video 1/1 (frame 78/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 16.8ms
video 1/1 (frame 79/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 15.4ms
video 1/1 (frame 80/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 15.6ms
video 1/1 (frame 81/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 4 traffic lights, 16.1ms
video 1/1 (frame 82/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 4 traffic lights, 15.1ms
video 1/1 (frame 83/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 4 traffic lights, 14.8ms
video 1/1 (frame 84/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 4 traffic lights, 18.0ms
video 1/1 (frame 85/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 4 traffic lights, 15.1ms
video 1/1 (frame 86/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 3 traffic lights, 21.5ms
video 1/1 (frame 87/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 3 traffic lights, 16.4ms
video 1/1 (frame 88/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 3 traffic lights, 15.7ms
video 1/1 (frame 89/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 16.2ms
video 1/1 (frame 90/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 19.5ms
video 1/1 (frame 91/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 16.1ms
video 1/1 (frame 92/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 18.7ms
video 1/1 (frame 93/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 3 traffic lights, 16.2ms
video 1/1 (frame 94/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 3 traffic lights, 14.9ms
video 1/1 (frame 95/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 17.0ms
video 1/1 (frame 96/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 17.9ms
96
video 1/1 (frame 97/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 15.6ms
video 1/1 (frame 98/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 3 traffic lights, 17.4ms
video 1/1 (frame 99/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 15.0ms
video 1/1 (frame 100/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 3 traffic lights, 17.2ms
video 1/1 (frame 101/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 3 traffic lights, 20.2ms
video 1/1 (frame 102/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 17.0ms
video 1/1 (frame 103/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 3 traffic lights, 18.9ms
video 1/1 (frame 104/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 2 traffic lights, 17.5ms
video 1/1 (frame 105/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 2 traffic lights, 17.1ms
video 1/1 (frame 106/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 2 traffic lights, 15.8ms
video 1/1 (frame 107/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 2 traffic lights, 14.4ms
video 1/1 (frame 108/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 2 traffic lights, 16.2ms
video 1/1 (frame 109/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 2 traffic lights, 19.5ms
video 1/1 (frame 110/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 2 traffic lights, 17.7ms
video 1/1 (frame 111/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 2 traffic lights, 19.5ms
video 1/1 (frame 112/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 15.2ms
video 1/1 (frame 113/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 8 cars, 1 bus, 1 truck, 3 traffic lights, 18.0ms
video 1/1 (frame 114/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 15.9ms
video 1/1 (frame 115/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 3 traffic lights, 17.1ms
video 1/1 (frame 116/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 3 traffic lights, 16.3ms
video 1/1 (frame 117/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 6 cars, 1 bus, 1 truck, 4 traffic lights, 16.5ms
video 1/1 (frame 118/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 4 traffic lights, 17.2ms
video 1/1 (frame 119/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 4 traffic lights, 16.8ms
video 1/1 (frame 120/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 7 cars, 1 bus, 1 truck, 4 traffic lights, 19.8ms
120
video 1/1 (frame 121/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 3 traffic lights, 16.9ms
video 1/1 (frame 122/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 3 traffic lights, 16.4ms
video 1/1 (frame 123/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 4 traffic lights, 16.4ms
video 1/1 (frame 124/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 4 traffic lights, 15.7ms
video 1/1 (frame 125/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 3 traffic lights, 17.2ms
video 1/1 (frame 126/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 16.9ms
video 1/1 (frame 127/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 20.0ms
video 1/1 (frame 128/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 1 traffic light, 20.2ms
video 1/1 (frame 129/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 1 traffic light, 18.5ms
video 1/1 (frame 130/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 1 traffic light, 16.0ms
video 1/1 (frame 131/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 2 traffic lights, 15.6ms
video 1/1 (frame 132/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 2 traffic lights, 15.7ms
video 1/1 (frame 133/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 2 traffic lights, 18.1ms
video 1/1 (frame 134/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 15.7ms
video 1/1 (frame 135/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 16.0ms
video 1/1 (frame 136/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 15.2ms
video 1/1 (frame 137/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 16.4ms
video 1/1 (frame 138/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 1 traffic light, 17.2ms
video 1/1 (frame 139/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 1 traffic light, 18.3ms
video 1/1 (frame 140/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 16.6ms
video 1/1 (frame 141/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 15.2ms
video 1/1 (frame 142/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 1 traffic light, 15.6ms
video 1/1 (frame 143/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 1 traffic light, 16.5ms
video 1/1 (frame 144/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 16.6ms
144
video 1/1 (frame 145/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 1 traffic light, 16.3ms
video 1/1 (frame 146/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 4 cars, 1 bus, 1 truck, 2 traffic lights, 19.1ms
video 1/1 (frame 147/1034) C:\Users\Yura Sannikov\\-26\  \\4th_small.mp4: 256x448 5 cars, 1 bus, 1 truck, 2 traffic lights, 14.5ms

In [108]:
fileName = pathToVideoFolder + '5th_small.mp4'
folder_name = '5th-small-img'

In [109]:
print_time(maskWithShowVideo)

Number of files:  0
обработанные кадры сохранятся в папку C:/Users/Yura Sannikov/Учеба/НИР-диплом26/Папка с кодомм/исходные/imagesFolder/5th-small-img . Если произошла ошибка, запустите makeVideo, чтобы собрать собранные кадры в видео
botsort

video 1/1 (frame 1/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 truck, 2 traffic lights, 17.3ms
File with lines not found :(. Please draw new ones
Starting: (821, 410), Ending: (1329, 357)
[(821, 410), (1329, 357)]
Starting: (675, 381), Ending: (975, 434)
[(675, 381), (975, 434)]
Starting: (280, 410), Ending: (49, 337)
[(280, 410), (49, 337)]
Starting: (110, 439), Ending: (443, 383)
[(110, 439), (443, 383)]
Starting: (49, 554), Ending: (-2, 567)
[(49, 554), (-2, 567)]
Starting: (30, 502), Ending: (77, 619)
[(30, 502), (77, 619)]
Starting: (842, 560), Ending: (1910, 841)
[(842, 560), (1910, 841)]
Starting: (1043, 508), Ending: (540, 648)
[(1043, 508), (540, 648)]
video 1/1 (frame 2/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 truck, 2 traffic lights, 67.3ms
video 1/1 (frame 3/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 truck, 2 traffic lights, 67.5ms
video 1/1 (frame 4/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 truck, 2 traffic lights, 17.8ms
video 1/1 (frame 5/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 truck, 2 traffic lights, 17.1ms
video 1/1 (frame 6/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 truck, 2 traffic lights, 18.0ms
video 1/1 (frame 7/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 truck, 2 traffic lights, 16.3ms
video 1/1 (frame 8/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 truck, 2 traffic lights, 21.1ms
video 1/1 (frame 9/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 17.4ms
video 1/1 (frame 10/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.3ms
video 1/1 (frame 11/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.2ms
video 1/1 (frame 12/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 21.2ms
video 1/1 (frame 13/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 19.8ms
video 1/1 (frame 14/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 18.9ms
video 1/1 (frame 15/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 19.7ms
video 1/1 (frame 16/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.2ms
video 1/1 (frame 17/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 22.5ms
video 1/1 (frame 18/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 15.8ms
video 1/1 (frame 19/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 19.2ms
video 1/1 (frame 20/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 25.7ms
video 1/1 (frame 21/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 19.6ms
video 1/1 (frame 22/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 15.6ms
video 1/1 (frame 23/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.6ms
video 1/1 (frame 24/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 2 traffic lights, 19.5ms
24
video 1/1 (frame 25/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 2 traffic lights, 18.1ms
video 1/1 (frame 26/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 21.1ms
video 1/1 (frame 27/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.5ms
video 1/1 (frame 28/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 17.2ms
video 1/1 (frame 29/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 20.3ms
video 1/1 (frame 30/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 19.4ms
video 1/1 (frame 31/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 23.2ms
video 1/1 (frame 32/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 15.4ms
video 1/1 (frame 33/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 20.3ms
video 1/1 (frame 34/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 21.7ms
video 1/1 (frame 35/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 16.1ms
video 1/1 (frame 36/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 19.2ms
video 1/1 (frame 37/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 17.9ms
video 1/1 (frame 38/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 17.6ms
video 1/1 (frame 39/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 18.3ms
video 1/1 (frame 40/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 19.8ms
video 1/1 (frame 41/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 15.9ms
video 1/1 (frame 42/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 17.2ms
video 1/1 (frame 43/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 20.1ms
video 1/1 (frame 44/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.2ms
video 1/1 (frame 45/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 18.4ms
video 1/1 (frame 46/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 16.6ms
video 1/1 (frame 47/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 19.7ms
video 1/1 (frame 48/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 21.8ms
48
video 1/1 (frame 49/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 16.5ms
video 1/1 (frame 50/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 18.6ms
video 1/1 (frame 51/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 18.8ms
video 1/1 (frame 52/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 17.0ms
video 1/1 (frame 53/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 17.6ms
video 1/1 (frame 54/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 18.6ms
video 1/1 (frame 55/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 19.9ms
video 1/1 (frame 56/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 19.8ms
video 1/1 (frame 57/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 19.7ms
video 1/1 (frame 58/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 15.9ms
video 1/1 (frame 59/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 17.0ms
video 1/1 (frame 60/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 19.6ms
video 1/1 (frame 61/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 2 cars, 1 traffic light, 23.4ms
video 1/1 (frame 62/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 15.8ms
video 1/1 (frame 63/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 24.6ms
video 1/1 (frame 64/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 17.4ms
video 1/1 (frame 65/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 16.0ms
video 1/1 (frame 66/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 16.3ms
video 1/1 (frame 67/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 17.5ms
video 1/1 (frame 68/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 16.6ms
video 1/1 (frame 69/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 20.3ms
video 1/1 (frame 70/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 19.5ms
video 1/1 (frame 71/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 16.4ms
video 1/1 (frame 72/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 15.4ms
72
video 1/1 (frame 73/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 15.7ms
video 1/1 (frame 74/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 16.1ms
video 1/1 (frame 75/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 17.4ms
video 1/1 (frame 76/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 17.8ms
video 1/1 (frame 77/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 19.0ms
video 1/1 (frame 78/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 16.8ms
video 1/1 (frame 79/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 27.0ms
video 1/1 (frame 80/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 16.1ms
video 1/1 (frame 81/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 21.2ms
video 1/1 (frame 82/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 19.3ms
video 1/1 (frame 83/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 17.6ms
video 1/1 (frame 84/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 16.5ms
video 1/1 (frame 85/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 25.4ms
video 1/1 (frame 86/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 15.6ms
video 1/1 (frame 87/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 4 persons, 3 cars, 1 traffic light, 22.2ms
video 1/1 (frame 88/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 17.3ms
video 1/1 (frame 89/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 14.9ms
video 1/1 (frame 90/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 17.5ms
video 1/1 (frame 91/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.9ms
video 1/1 (frame 92/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 17.1ms
video 1/1 (frame 93/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 24.8ms
video 1/1 (frame 94/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.9ms
video 1/1 (frame 95/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 17.1ms
video 1/1 (frame 96/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 19.2ms
96
video 1/1 (frame 97/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 16.1ms
video 1/1 (frame 98/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.4ms
video 1/1 (frame 99/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.5ms
video 1/1 (frame 100/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 19.3ms
video 1/1 (frame 101/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.0ms
video 1/1 (frame 102/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.4ms
video 1/1 (frame 103/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 18.6ms
video 1/1 (frame 104/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.3ms
video 1/1 (frame 105/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.6ms
video 1/1 (frame 106/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.0ms
video 1/1 (frame 107/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 18.3ms
video 1/1 (frame 108/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 17.0ms
video 1/1 (frame 109/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 17.5ms
video 1/1 (frame 110/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.3ms
video 1/1 (frame 111/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 22.4ms
video 1/1 (frame 112/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 22.0ms
video 1/1 (frame 113/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.7ms
video 1/1 (frame 114/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 20.0ms
video 1/1 (frame 115/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.3ms
video 1/1 (frame 116/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.9ms
video 1/1 (frame 117/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 17.6ms
video 1/1 (frame 118/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.4ms
video 1/1 (frame 119/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 17.7ms
video 1/1 (frame 120/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 14.9ms
120
video 1/1 (frame 121/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.4ms
video 1/1 (frame 122/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 19.6ms
video 1/1 (frame 123/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 18.9ms
video 1/1 (frame 124/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 18.1ms
video 1/1 (frame 125/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 22.7ms
video 1/1 (frame 126/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.0ms
video 1/1 (frame 127/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.1ms
video 1/1 (frame 128/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 22.0ms
video 1/1 (frame 129/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.7ms
video 1/1 (frame 130/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.9ms
video 1/1 (frame 131/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 22.0ms
video 1/1 (frame 132/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.3ms
video 1/1 (frame 133/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 17.3ms
video 1/1 (frame 134/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.9ms
video 1/1 (frame 135/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 20.3ms
video 1/1 (frame 136/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 17.9ms
video 1/1 (frame 137/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 19.6ms
video 1/1 (frame 138/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 17.7ms
video 1/1 (frame 139/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.4ms
video 1/1 (frame 140/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 15.9ms
video 1/1 (frame 141/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.2ms
video 1/1 (frame 142/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.9ms
video 1/1 (frame 143/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.9ms
video 1/1 (frame 144/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 17.0ms
144
video 1/1 (frame 145/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.1ms
video 1/1 (frame 146/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 19.3ms
video 1/1 (frame 147/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 18.6ms
video 1/1 (frame 148/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 17.9ms
video 1/1 (frame 149/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.1ms
video 1/1 (frame 150/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 15.6ms
video 1/1 (frame 151/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 18.2ms
video 1/1 (frame 152/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 25.2ms
video 1/1 (frame 153/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 22.3ms

In [ ]:
video_name = '5th-small-SegVidV2Botsort.avi'
classToconvertV2.convertToVid(folder_name, video_name)

Images: ['00000000000000000000000000000000.jpg', '00000000000000000000000000000001.jpg', '00000000000000000000000000000002.jpg', '00000000000000000000000000000003.jpg', '00000000000000000000000000000004.jpg', '00000000000000000000000000000005.jpg', '00000000000000000000000000000006.jpg', '00000000000000000000000000000007.jpg', '00000000000000000000000000000008.jpg', '00000000000000000000000000000009.jpg', '00000000000000000000000000000010.jpg', '00000000000000000000000000000011.jpg', '00000000000000000000000000000012.jpg', '00000000000000000000000000000013.jpg', '00000000000000000000000000000014.jpg', '00000000000000000000000000000015.jpg', '00000000000000000000000000000016.jpg', '00000000000000000000000000000017.jpg', '00000000000000000000000000000018.jpg', '00000000000000000000000000000019.jpg', '00000000000000000000000000000020.jpg', '00000000000000000000000000000021.jpg', '00000000000000000000000000000022.jpg', '00000000000000000000000000000023.jpg', '00000000000000000000000000000024.jpg', '00000000000000000000000000000025.jpg', '00000000000000000000000000000026.jpg', '00000000000000000000000000000027.jpg', '00000000000000000000000000000028.jpg', '00000000000000000000000000000029.jpg', '00000000000000000000000000000030.jpg', '00000000000000000000000000000031.jpg', '00000000000000000000000000000032.jpg', '00000000000000000000000000000033.jpg', '00000000000000000000000000000034.jpg', '00000000000000000000000000000035.jpg', '00000000000000000000000000000036.jpg', '00000000000000000000000000000037.jpg', '00000000000000000000000000000038.jpg', '00000000000000000000000000000039.jpg', '00000000000000000000000000000040.jpg', '00000000000000000000000000000041.jpg', '00000000000000000000000000000042.jpg', '00000000000000000000000000000043.jpg', '00000000000000000000000000000044.jpg', '00000000000000000000000000000045.jpg', '00000000000000000000000000000046.jpg', '00000000000000000000000000000047.jpg', '00000000000000000000000000000048.jpg', '00000000000000000000000000000049.jpg', '00000000000000000000000000000050.jpg', '00000000000000000000000000000051.jpg', '00000000000000000000000000000052.jpg', '00000000000000000000000000000053.jpg', '00000000000000000000000000000054.jpg', '00000000000000000000000000000055.jpg', '00000000000000000000000000000056.jpg', '00000000000000000000000000000057.jpg', '00000000000000000000000000000058.jpg', '00000000000000000000000000000059.jpg', '00000000000000000000000000000060.jpg', '00000000000000000000000000000061.jpg', '00000000000000000000000000000062.jpg', '00000000000000000000000000000063.jpg', '00000000000000000000000000000064.jpg', '00000000000000000000000000000065.jpg', '00000000000000000000000000000066.jpg', '00000000000000000000000000000067.jpg', '00000000000000000000000000000068.jpg', '00000000000000000000000000000069.jpg', '00000000000000000000000000000070.jpg', '00000000000000000000000000000071.jpg', '00000000000000000000000000000072.jpg', '00000000000000000000000000000073.jpg', '00000000000000000000000000000074.jpg', '00000000000000000000000000000075.jpg', '00000000000000000000000000000076.jpg', '00000000000000000000000000000077.jpg', '00000000000000000000000000000078.jpg', '00000000000000000000000000000079.jpg', '00000000000000000000000000000080.jpg', '00000000000000000000000000000081.jpg', '00000000000000000000000000000082.jpg', '00000000000000000000000000000083.jpg', '00000000000000000000000000000084.jpg', '00000000000000000000000000000085.jpg', '00000000000000000000000000000086.jpg', '00000000000000000000000000000087.jpg', '00000000000000000000000000000088.jpg', '00000000000000000000000000000089.jpg', '00000000000000000000000000000090.jpg', '00000000000000000000000000000091.jpg', '00000000000000000000000000000092.jpg', '00000000000000000000000000000093.jpg', '00000000000000000000000000000094.jpg', '00000000000000000000000000000095.jpg', '00000000000000000000000000000096.jpg', '00000000000000000000000000000097.jpg', '00000000000000000000000000000098.jpg', '00000000000000000000000000000099.jpg', '00000000000000000000000000000100.jpg', '00000000000000000000000000000101.jpg', '00000000000000000000000000000102.jpg', '00000000000000000000000000000103.jpg', '00000000000000000000000000000104.jpg', '00000000000000000000000000000105.jpg', '00000000000000000000000000000106.jpg', '00000000000000000000000000000107.jpg', '00000000000000000000000000000108.jpg', '00000000000000000000000000000109.jpg', '00000000000000000000000000000110.jpg', '00000000000000000000000000000111.jpg', '00000000000000000000000000000112.jpg', '00000000000000000000000000000113.jpg', '00000000000000000000000000000114.jpg', '00000000000000000000000000000115.jpg', '00000000000000000000000000000116.jpg', '00000000000000000000000000000117.jpg', '00000000000000000000000000000118.jpg', '00000000000000000000000000000119.jpg', '00000000000000000000000000000120.jpg', '00000000000000000000000000000121.jpg', '00000000000000000000000000000122.jpg', '00000000000000000000000000000123.jpg', '00000000000000000000000000000124.jpg', '00000000000000000000000000000125.jpg', '00000000000000000000000000000126.jpg', '00000000000000000000000000000127.jpg', '00000000000000000000000000000128.jpg', '00000000000000000000000000000129.jpg', '00000000000000000000000000000130.jpg', '00000000000000000000000000000131.jpg', '00000000000000000000000000000132.jpg', '00000000000000000000000000000133.jpg', '00000000000000000000000000000134.jpg', '00000000000000000000000000000135.jpg', '00000000000000000000000000000136.jpg', '00000000000000000000000000000137.jpg', '00000000000000000000000000000138.jpg', '00000000000000000000000000000139.jpg', '00000000000000000000000000000140.jpg', '00000000000000000000000000000141.jpg', '00000000000000000000000000000142.jpg', '00000000000000000000000000000143.jpg', '00000000000000000000000000000144.jpg', '00000000000000000000000000000145.jpg', '00000000000000000000000000000146.jpg', '00000000000000000000000000000147.jpg', '00000000000000000000000000000148.jpg', '00000000000000000000000000000149.jpg', '00000000000000000000000000000150.jpg', '00000000000000000000000000000151.jpg', '00000000000000000000000000000152.jpg', '00000000000000000000000000000153.jpg', '00000000000000000000000000000154.jpg', '00000000000000000000000000000155.jpg', '00000000000000000000000000000156.jpg', '00000000000000000000000000000157.jpg', '00000000000000000000000000000158.jpg', '00000000000000000000000000000159.jpg', '00000000000000000000000000000160.jpg', '00000000000000000000000000000161.jpg', '00000000000000000000000000000162.jpg', '00000000000000000000000000000163.jpg', '00000000000000000000000000000164.jpg', '00000000000000000000000000000165.jpg', '00000000000000000000000000000166.jpg', '00000000000000000000000000000167.jpg', '00000000000000000000000000000168.jpg', '00000000000000000000000000000169.jpg', '00000000000000000000000000000170.jpg', '00000000000000000000000000000171.jpg', '00000000000000000000000000000172.jpg', '00000000000000000000000000000173.jpg', '00000000000000000000000000000174.jpg', '00000000000000000000000000000175.jpg', '00000000000000000000000000000176.jpg', '00000000000000000000000000000177.jpg', '00000000000000000000000000000178.jpg', '00000000000000000000000000000179.jpg', '00000000000000000000000000000180.jpg', '00000000000000000000000000000181.jpg', '00000000000000000000000000000182.jpg', '00000000000000000000000000000183.jpg', '00000000000000000000000000000184.jpg', '00000000000000000000000000000185.jpg', '00000000000000000000000000000186.jpg', '00000000000000000000000000000187.jpg', '00000000000000000000000000000188.jpg', '00000000000000000000000000000189.jpg', '00000000000000000000000000000190.jpg', '00000000000000000000000000000191.jpg', '00000000000000000000000000000192.jpg', '00000000000000000000000000000193.jpg', '00000000000000000000000000000194.jpg', '00000000000000000000000000000195.jpg', '00000000000000000000000000000196.jpg', '00000000000000000000000000000197.jpg', '00000000000000000000000000000198.jpg', '00000000000000000000000000000199.jpg', '00000000000000000000000000000200.jpg', '00000000000000000000000000000201.jpg', '00000000000000000000000000000202.jpg', '00000000000000000000000000000203.jpg', '00000000000000000000000000000204.jpg', '00000000000000000000000000000205.jpg', '00000000000000000000000000000206.jpg', '00000000000000000000000000000207.jpg', '00000000000000000000000000000208.jpg', '00000000000000000000000000000209.jpg', '00000000000000000000000000000210.jpg', '00000000000000000000000000000211.jpg', '00000000000000000000000000000212.jpg', '00000000000000000000000000000213.jpg', '00000000000000000000000000000214.jpg', '00000000000000000000000000000215.jpg', '00000000000000000000000000000216.jpg', '00000000000000000000000000000217.jpg', '00000000000000000000000000000218.jpg', '00000000000000000000000000000219.jpg', '00000000000000000000000000000220.jpg', '00000000000000000000000000000221.jpg', '00000000000000000000000000000222.jpg', '00000000000000000000000000000223.jpg', '00000000000000000000000000000224.jpg', '00000000000000000000000000000225.jpg', '00000000000000000000000000000226.jpg', '00000000000000000000000000000227.jpg', '00000000000000000000000000000228.jpg', '00000000000000000000000000000229.jpg', '00000000000000000000000000000230.jpg', '00000000000000000000000000000231.jpg', '00000000000000000000000000000232.jpg', '00000000000000000000000000000233.jpg', '00000000000000000000000000000234.jpg', '00000000000000000000000000000235.jpg', '00000000000000000000000000000236.jpg', '00000000000000000000000000000237.jpg', '00000000000000000000000000000238.jpg', '00000000000000000000000000000239.jpg', '00000000000000000000000000000240.jpg', '00000000000000000000000000000241.jpg', '00000000000000000000000000000242.jpg', '00000000000000000000000000000243.jpg', '00000000000000000000000000000244.jpg', '00000000000000000000000000000245.jpg', '00000000000000000000000000000246.jpg', '00000000000000000000000000000247.jpg', '00000000000000000000000000000248.jpg', '00000000000000000000000000000249.jpg', '00000000000000000000000000000250.jpg', '00000000000000000000000000000251.jpg', '00000000000000000000000000000252.jpg', '00000000000000000000000000000253.jpg', '00000000000000000000000000000254.jpg', '00000000000000000000000000000255.jpg', '00000000000000000000000000000256.jpg', '00000000000000000000000000000257.jpg', '00000000000000000000000000000258.jpg', '00000000000000000000000000000259.jpg', '00000000000000000000000000000260.jpg', '00000000000000000000000000000261.jpg', '00000000000000000000000000000262.jpg', '00000000000000000000000000000263.jpg', '00000000000000000000000000000264.jpg', '00000000000000000000000000000265.jpg', '00000000000000000000000000000266.jpg', '00000000000000000000000000000267.jpg', '00000000000000000000000000000268.jpg', '00000000000000000000000000000269.jpg', '00000000000000000000000000000270.jpg', '00000000000000000000000000000271.jpg', '00000000000000000000000000000272.jpg', '00000000000000000000000000000273.jpg', '00000000000000000000000000000274.jpg', '00000000000000000000000000000275.jpg', '00000000000000000000000000000276.jpg', '00000000000000000000000000000277.jpg', '00000000000000000000000000000278.jpg', '00000000000000000000000000000279.jpg', '00000000000000000000000000000280.jpg', '00000000000000000000000000000281.jpg', '00000000000000000000000000000282.jpg', '00000000000000000000000000000283.jpg', '00000000000000000000000000000284.jpg', '00000000000000000000000000000285.jpg', '00000000000000000000000000000286.jpg', '00000000000000000000000000000287.jpg', '00000000000000000000000000000288.jpg', '00000000000000000000000000000289.jpg', '00000000000000000000000000000290.jpg', '00000000000000000000000000000291.jpg', '00000000000000000000000000000292.jpg', '00000000000000000000000000000293.jpg', '00000000000000000000000000000294.jpg', '00000000000000000000000000000295.jpg', '00000000000000000000000000000296.jpg', '00000000000000000000000000000297.jpg', '00000000000000000000000000000298.jpg', '00000000000000000000000000000299.jpg', '00000000000000000000000000000300.jpg', '00000000000000000000000000000301.jpg', '00000000000000000000000000000302.jpg', '00000000000000000000000000000303.jpg', '00000000000000000000000000000304.jpg', '00000000000000000000000000000305.jpg', '00000000000000000000000000000306.jpg', '00000000000000000000000000000307.jpg', '00000000000000000000000000000308.jpg', '00000000000000000000000000000309.jpg', '00000000000000000000000000000310.jpg', '00000000000000000000000000000311.jpg', '00000000000000000000000000000312.jpg', '00000000000000000000000000000313.jpg', '00000000000000000000000000000314.jpg', '00000000000000000000000000000315.jpg', '00000000000000000000000000000316.jpg', '00000000000000000000000000000317.jpg', '00000000000000000000000000000318.jpg', '00000000000000000000000000000319.jpg', '00000000000000000000000000000320.jpg', '00000000000000000000000000000321.jpg', '00000000000000000000000000000322.jpg', '00000000000000000000000000000323.jpg', '00000000000000000000000000000324.jpg', '00000000000000000000000000000325.jpg', '00000000000000000000000000000326.jpg', '00000000000000000000000000000327.jpg', '00000000000000000000000000000328.jpg', '00000000000000000000000000000329.jpg', '00000000000000000000000000000330.jpg', '00000000000000000000000000000331.jpg', '00000000000000000000000000000332.jpg', '00000000000000000000000000000333.jpg', '00000000000000000000000000000334.jpg', '00000000000000000000000000000335.jpg', '00000000000000000000000000000336.jpg', '00000000000000000000000000000337.jpg', '00000000000000000000000000000338.jpg', '00000000000000000000000000000339.jpg', '00000000000000000000000000000340.jpg', '00000000000000000000000000000341.jpg', '00000000000000000000000000000342.jpg', '00000000000000000000000000000343.jpg', '00000000000000000000000000000344.jpg', '00000000000000000000000000000345.jpg', '00000000000000000000000000000346.jpg', '00000000000000000000000000000347.jpg', '00000000000000000000000000000348.jpg', '00000000000000000000000000000349.jpg', '00000000000000000000000000000350.jpg', '00000000000000000000000000000351.jpg', '00000000000000000000000000000352.jpg', '00000000000000000000000000000353.jpg', '00000000000000000000000000000354.jpg', '00000000000000000000000000000355.jpg', '00000000000000000000000000000356.jpg', '00000000000000000000000000000357.jpg', '00000000000000000000000000000358.jpg', '00000000000000000000000000000359.jpg', '00000000000000000000000000000360.jpg', '00000000000000000000000000000361.jpg', '00000000000000000000000000000362.jpg', '00000000000000000000000000000363.jpg', '00000000000000000000000000000364.jpg', '00000000000000000000000000000365.jpg', '00000000000000000000000000000366.jpg', '00000000000000000000000000000367.jpg', '00000000000000000000000000000368.jpg', '00000000000000000000000000000369.jpg', '00000000000000000000000000000370.jpg', '00000000000000000000000000000371.jpg', '00000000000000000000000000000372.jpg', '00000000000000000000000000000373.jpg', '00000000000000000000000000000374.jpg', '00000000000000000000000000000375.jpg', '00000000000000000000000000000376.jpg', '00000000000000000000000000000377.jpg', '00000000000000000000000000000378.jpg', '00000000000000000000000000000379.jpg', '00000000000000000000000000000380.jpg', '00000000000000000000000000000381.jpg', '00000000000000000000000000000382.jpg', '00000000000000000000000000000383.jpg', '00000000000000000000000000000384.jpg', '00000000000000000000000000000385.jpg', '00000000000000000000000000000386.jpg', '00000000000000000000000000000387.jpg', '00000000000000000000000000000388.jpg', '00000000000000000000000000000389.jpg', '00000000000000000000000000000390.jpg', '00000000000000000000000000000391.jpg', '00000000000000000000000000000392.jpg', '00000000000000000000000000000393.jpg', '00000000000000000000000000000394.jpg', '00000000000000000000000000000395.jpg', '00000000000000000000000000000396.jpg', '00000000000000000000000000000397.jpg', '00000000000000000000000000000398.jpg', '00000000000000000000000000000399.jpg', '00000000000000000000000000000400.jpg', '00000000000000000000000000000401.jpg', '00000000000000000000000000000402.jpg', '00000000000000000000000000000403.jpg', '00000000000000000000000000000404.jpg', '00000000000000000000000000000405.jpg', '00000000000000000000000000000406.jpg', '00000000000000000000000000000407.jpg', '00000000000000000000000000000408.jpg', '00000000000000000000000000000409.jpg', '00000000000000000000000000000410.jpg', '00000000000000000000000000000411.jpg', '00000000000000000000000000000412.jpg', '00000000000000000000000000000413.jpg', '00000000000000000000000000000414.jpg', '00000000000000000000000000000415.jpg', '00000000000000000000000000000416.jpg', '00000000000000000000000000000417.jpg', '00000000000000000000000000000418.jpg', '00000000000000000000000000000419.jpg', '00000000000000000000000000000420.jpg', '00000000000000000000000000000421.jpg', '00000000000000000000000000000422.jpg', '00000000000000000000000000000423.jpg', '00000000000000000000000000000424.jpg', '00000000000000000000000000000425.jpg', '00000000000000000000000000000426.jpg', '00000000000000000000000000000427.jpg', '00000000000000000000000000000428.jpg', '00000000000000000000000000000429.jpg', '00000000000000000000000000000430.jpg', '00000000000000000000000000000431.jpg', '00000000000000000000000000000432.jpg', '00000000000000000000000000000433.jpg', '00000000000000000000000000000434.jpg', '00000000000000000000000000000435.jpg', '00000000000000000000000000000436.jpg', '00000000000000000000000000000437.jpg', '00000000000000000000000000000438.jpg', '00000000000000000000000000000439.jpg', '00000000000000000000000000000440.jpg', '00000000000000000000000000000441.jpg', '00000000000000000000000000000442.jpg', '00000000000000000000000000000443.jpg', '00000000000000000000000000000444.jpg', '00000000000000000000000000000445.jpg', '00000000000000000000000000000446.jpg', '00000000000000000000000000000447.jpg', '00000000000000000000000000000448.jpg', '00000000000000000000000000000449.jpg', '00000000000000000000000000000450.jpg', '00000000000000000000000000000451.jpg', '00000000000000000000000000000452.jpg', '00000000000000000000000000000453.jpg', '00000000000000000000000000000454.jpg', '00000000000000000000000000000455.jpg', '00000000000000000000000000000456.jpg', '00000000000000000000000000000457.jpg', '00000000000000000000000000000458.jpg', '00000000000000000000000000000459.jpg', '00000000000000000000000000000460.jpg', '00000000000000000000000000000461.jpg', '00000000000000000000000000000462.jpg', '00000000000000000000000000000463.jpg', '00000000000000000000000000000464.jpg', '00000000000000000000000000000465.jpg', '00000000000000000000000000000466.jpg', '00000000000000000000000000000467.jpg', '00000000000000000000000000000468.jpg', '00000000000000000000000000000469.jpg', '00000000000000000000000000000470.jpg', '00000000000000000000000000000471.jpg', '00000000000000000000000000000472.jpg', '00000000000000000000000000000473.jpg', '00000000000000000000000000000474.jpg', '00000000000000000000000000000475.jpg', '00000000000000000000000000000476.jpg', '00000000000000000000000000000477.jpg', '00000000000000000000000000000478.jpg', '00000000000000000000000000000479.jpg', '00000000000000000000000000000480.jpg', '00000000000000000000000000000481.jpg', '00000000000000000000000000000482.jpg', '00000000000000000000000000000483.jpg', '00000000000000000000000000000484.jpg', '00000000000000000000000000000485.jpg', '00000000000000000000000000000486.jpg', '00000000000000000000000000000487.jpg', '00000000000000000000000000000488.jpg', '00000000000000000000000000000489.jpg', '00000000000000000000000000000490.jpg', '00000000000000000000000000000491.jpg', '00000000000000000000000000000492.jpg', '00000000000000000000000000000493.jpg', '00000000000000000000000000000494.jpg', '00000000000000000000000000000495.jpg', '00000000000000000000000000000496.jpg', '00000000000000000000000000000497.jpg', '00000000000000000000000000000498.jpg', '000000000000000000000000000004

In [41]:
# С явной пробкой
fileName = pathToVideoFolder + 'jamPicture.mp4'
folder_name = 'jamPicture-img'

In [48]:
print_time(maskWithShowVideo)

Number of files:  1
Error while deleting file :  C:/Users/Yura Sannikov/Учеба/НИР-диплом26/Папка с кодомм/исходные/imagesFolder/jamPicture-img\json_lines
обработанные кадры сохранятся в папку C:/Users/Yura Sannikov/Учеба/НИР-диплом26/Папка с кодомм/исходные/imagesFolder/jamPicture-img . Если произошла ошибка, запустите makeVideo, чтобы собрать собранные кадры в видео
botsort

video 1/1 (frame 1/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.5ms
lines loaded
counters
mid Counter({1: 1, 14: 1, 22: 1})
to_left Counter({8: 1, 15: 1, 19: 1, 21: 1})
to_right Counter({7: 1, 9: 1, 10: 1, 11: 1, 12: 1, 13: 1, 16: 1, 18: 1, 20: 1})
to_top Counter({2: 1, 17: 1})
to_bottom Counter({5: 1, 6: 1})
sets
to_left {8, 19, 21, 15}
to_right {7, 9, 10, 11, 12, 13, 16, 18, 20}
to_top {17, 2}
to_bottom {5, 6}
video 1/1 (frame 2/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 56.1ms
video 1/1 (frame 3/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 69.7ms
video 1/1 (frame 4/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 13 cars, 6 buss, 3 trucks, 65.6ms
video 1/1 (frame 5/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 64.5ms
video 1/1 (frame 6/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 13 cars, 6 buss, 3 trucks, 72.4ms
video 1/1 (frame 7/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 67.2ms
video 1/1 (frame 8/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 71.3ms
video 1/1 (frame 9/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 36.1ms
video 1/1 (frame 10/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 13 cars, 6 buss, 3 trucks, 36.8ms
video 1/1 (frame 11/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 35.5ms
video 1/1 (frame 12/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 18.1ms
video 1/1 (frame 13/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.2ms
video 1/1 (frame 14/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.3ms
video 1/1 (frame 15/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 25.9ms
video 1/1 (frame 16/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 34.2ms
video 1/1 (frame 17/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 34.0ms
video 1/1 (frame 18/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.5ms
video 1/1 (frame 19/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.8ms
video 1/1 (frame 20/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.5ms
video 1/1 (frame 21/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 20.6ms
video 1/1 (frame 22/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 17.5ms
video 1/1 (frame 23/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.8ms
video 1/1 (frame 24/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 17.0ms
24
video 1/1 (frame 25/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 17.1ms
video 1/1 (frame 26/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.6ms
video 1/1 (frame 27/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 21.4ms
video 1/1 (frame 28/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.3ms
video 1/1 (frame 29/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.7ms
video 1/1 (frame 30/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 18.8ms
video 1/1 (frame 31/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 24.3ms
video 1/1 (frame 32/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.4ms
video 1/1 (frame 33/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 17.0ms
video 1/1 (frame 34/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 22.0ms
video 1/1 (frame 35/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.4ms
video 1/1 (frame 36/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 18.8ms
video 1/1 (frame 37/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.7ms
video 1/1 (frame 38/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.7ms
video 1/1 (frame 39/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.3ms
video 1/1 (frame 40/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.2ms
video 1/1 (frame 41/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.5ms
video 1/1 (frame 42/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 23.7ms
video 1/1 (frame 43/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.3ms
video 1/1 (frame 44/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 20.5ms
video 1/1 (frame 45/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.3ms
video 1/1 (frame 46/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.4ms
video 1/1 (frame 47/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.4ms
video 1/1 (frame 48/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 18.9ms
48
video 1/1 (frame 49/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 18.8ms
video 1/1 (frame 50/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 18.3ms
video 1/1 (frame 51/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.1ms
counters
mid Counter({1: 1, 14: 1, 22: 1})
to_left Counter({8: 1, 15: 1, 19: 1, 21: 1})
to_right Counter({7: 1, 9: 1, 10: 1, 11: 1, 12: 1, 13: 1, 16: 1, 18: 1, 20: 1})
to_top Counter({2: 1, 17: 1})
to_bottom Counter({5: 1, 6: 1})
sets
to_left {8, 19, 21, 15}
to_right {7, 9, 10, 11, 12, 13, 16, 18, 20}
to_top {17, 2}
to_bottom {5, 6}
video 1/1 (frame 52/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.9ms
video 1/1 (frame 53/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.4ms
video 1/1 (frame 54/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 18.1ms
video 1/1 (frame 55/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 20.6ms
video 1/1 (frame 56/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 20.0ms
video 1/1 (frame 57/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.9ms
video 1/1 (frame 58/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.0ms
video 1/1 (frame 59/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.8ms
video 1/1 (frame 60/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.0ms
video 1/1 (frame 61/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 13 cars, 6 buss, 3 trucks, 15.7ms
video 1/1 (frame 62/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 13 cars, 6 buss, 3 trucks, 17.1ms
video 1/1 (frame 63/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.5ms
video 1/1 (frame 64/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 17.3ms
video 1/1 (frame 65/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 17.7ms
video 1/1 (frame 66/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 22.4ms
video 1/1 (frame 67/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 18.9ms
video 1/1 (frame 68/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 24.0ms
video 1/1 (frame 69/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.5ms
video 1/1 (frame 70/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 21.3ms
video 1/1 (frame 71/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.5ms
video 1/1 (frame 72/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.2ms
72
video 1/1 (frame 73/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.0ms
video 1/1 (frame 74/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 18.9ms
video 1/1 (frame 75/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 21.1ms
video 1/1 (frame 76/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.9ms
video 1/1 (frame 77/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.5ms
video 1/1 (frame 78/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 17.9ms
video 1/1 (frame 79/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.2ms
video 1/1 (frame 80/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.7ms
video 1/1 (frame 81/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 20.8ms
video 1/1 (frame 82/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.3ms
video 1/1 (frame 83/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.1ms
video 1/1 (frame 84/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 17.9ms
video 1/1 (frame 85/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.7ms
video 1/1 (frame 86/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.0ms
video 1/1 (frame 87/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.0ms
video 1/1 (frame 88/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.4ms
video 1/1 (frame 89/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 17.6ms
video 1/1 (frame 90/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.1ms
video 1/1 (frame 91/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.9ms
video 1/1 (frame 92/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.7ms
video 1/1 (frame 93/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.3ms
video 1/1 (frame 94/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.5ms
video 1/1 (frame 95/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.6ms
video 1/1 (frame 96/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.2ms
96
video 1/1 (frame 97/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 22.6ms
video 1/1 (frame 98/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 23.2ms
video 1/1 (frame 99/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.1ms
video 1/1 (frame 100/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.4ms
video 1/1 (frame 101/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.3ms
counters
mid Counter({1: 2, 14: 2, 22: 2})
to_left Counter({8: 2, 15: 2, 19: 2, 21: 2})
to_right Counter({7: 2, 9: 2, 10: 2, 11: 2, 12: 2, 13: 2, 16: 2, 18: 2, 20: 2})
to_top Counter({2: 2, 17: 2})
to_bottom Counter({5: 2, 6: 2})
sets
to_left {8, 19, 21, 15}
to_right {7, 9, 10, 11, 12, 13, 16, 18, 20}
to_top {17, 2}
to_bottom {5, 6}
video 1/1 (frame 102/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 20.3ms
video 1/1 (frame 103/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 21.9ms
video 1/1 (frame 104/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 25.2ms
video 1/1 (frame 105/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.7ms
video 1/1 (frame 106/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.3ms
video 1/1 (frame 107/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.5ms
video 1/1 (frame 108/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.6ms
video 1/1 (frame 109/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.9ms
video 1/1 (frame 110/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.8ms
video 1/1 (frame 111/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 18.0ms
video 1/1 (frame 112/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 22.6ms
video 1/1 (frame 113/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.6ms
video 1/1 (frame 114/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.4ms
video 1/1 (frame 115/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 18.6ms
video 1/1 (frame 116/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.2ms
video 1/1 (frame 117/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.5ms
video 1/1 (frame 118/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.1ms
video 1/1 (frame 119/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 17.6ms
video 1/1 (frame 120/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.1ms
120
video 1/1 (frame 121/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.7ms
video 1/1 (frame 122/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 17.1ms
video 1/1 (frame 123/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.7ms
video 1/1 (frame 124/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.6ms
video 1/1 (frame 125/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.4ms
video 1/1 (frame 126/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.4ms
video 1/1 (frame 127/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 13 cars, 6 buss, 3 trucks, 17.2ms
video 1/1 (frame 128/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 13 cars, 6 buss, 3 trucks, 17.0ms
video 1/1 (frame 129/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 13 cars, 6 buss, 2 trucks, 22.1ms
video 1/1 (frame 130/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.8ms
video 1/1 (frame 131/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 18.0ms
video 1/1 (frame 132/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.0ms
video 1/1 (frame 133/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 18.8ms
video 1/1 (frame 134/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.8ms
video 1/1 (frame 135/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.7ms
video 1/1 (frame 136/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.5ms
video 1/1 (frame 137/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 25.8ms
video 1/1 (frame 138/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.0ms
video 1/1 (frame 139/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.7ms
video 1/1 (frame 140/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 14.8ms
video 1/1 (frame 141/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.9ms
video 1/1 (frame 142/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.4ms
video 1/1 (frame 143/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.4ms
video 1/1 (frame 144/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.8ms
144
video 1/1 (frame 145/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.1ms
video 1/1 (frame 146/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.3ms
video 1/1 (frame 147/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 17.8ms
video 1/1 (frame 148/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 16.2ms
video 1/1 (frame 149/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.5ms
video 1/1 (frame 150/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.3ms
video 1/1 (frame 151/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 17.0ms
counters
mid Counter({1: 2, 14: 2, 22: 2})
to_left Counter({8: 2, 15: 2, 19: 2, 21: 2})
to_right Counter({7: 2, 9: 2, 10: 2, 11: 2, 12: 2, 13: 2, 16: 2, 18: 2, 20: 2})
to_top Counter({2: 2, 17: 2})
to_bottom Counter({5: 2, 6: 2})
sets
to_left {8, 19, 21, 15}
to_right {7, 9, 10, 11, 12, 13, 16, 18, 20}
to_top {17, 2}
to_bottom {5, 6}
video 1/1 (frame 152/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 19.7ms
video 1/1 (frame 153/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 18.0ms
video 1/1 (frame 154/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 22.4ms
video 1/1 (frame 155/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.9ms
video 1/1 (frame 156/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.8ms
video 1/1 (frame 157/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 15.3ms
video 1/1 (frame 158/771) C:\Users\Yura Sannikov\\-26\  \\jamPicture.mp4: 384x640 14 cars, 6 buss, 3 trucks, 23.3ms

In [49]:
video_name = 'jamPicture-SegVidV2Botsort.avi'
classToconvertV2.convertToVid(folder_name, video_name)

Images: ['00000000000000000000000000000000.jpg', '00000000000000000000000000000001.jpg', '00000000000000000000000000000002.jpg', '00000000000000000000000000000003.jpg', '00000000000000000000000000000004.jpg', '00000000000000000000000000000005.jpg', '00000000000000000000000000000006.jpg', '00000000000000000000000000000007.jpg', '00000000000000000000000000000008.jpg', '00000000000000000000000000000009.jpg', '00000000000000000000000000000010.jpg', '00000000000000000000000000000011.jpg', '00000000000000000000000000000012.jpg', '00000000000000000000000000000013.jpg', '00000000000000000000000000000014.jpg', '00000000000000000000000000000015.jpg', '00000000000000000000000000000016.jpg', '00000000000000000000000000000017.jpg', '00000000000000000000000000000018.jpg', '00000000000000000000000000000019.jpg', '00000000000000000000000000000020.jpg', '00000000000000000000000000000021.jpg', '00000000000000000000000000000022.jpg', '00000000000000000000000000000023.jpg', '00000000000000000000000000000024.jpg', '00000000000000000000000000000025.jpg', '00000000000000000000000000000026.jpg', '00000000000000000000000000000027.jpg', '00000000000000000000000000000028.jpg', '00000000000000000000000000000029.jpg', '00000000000000000000000000000030.jpg', '00000000000000000000000000000031.jpg', '00000000000000000000000000000032.jpg', '00000000000000000000000000000033.jpg', '00000000000000000000000000000034.jpg', '00000000000000000000000000000035.jpg', '00000000000000000000000000000036.jpg', '00000000000000000000000000000037.jpg', '00000000000000000000000000000038.jpg', '00000000000000000000000000000039.jpg', '00000000000000000000000000000040.jpg', '00000000000000000000000000000041.jpg', '00000000000000000000000000000042.jpg', '00000000000000000000000000000043.jpg', '00000000000000000000000000000044.jpg', '00000000000000000000000000000045.jpg', '00000000000000000000000000000046.jpg', '00000000000000000000000000000047.jpg', '00000000000000000000000000000048.jpg', '00000000000000000000000000000049.jpg', '00000000000000000000000000000050.jpg', '00000000000000000000000000000051.jpg', '00000000000000000000000000000052.jpg', '00000000000000000000000000000053.jpg', '00000000000000000000000000000054.jpg', '00000000000000000000000000000055.jpg', '00000000000000000000000000000056.jpg', '00000000000000000000000000000057.jpg', '00000000000000000000000000000058.jpg', '00000000000000000000000000000059.jpg', '00000000000000000000000000000060.jpg', '00000000000000000000000000000061.jpg', '00000000000000000000000000000062.jpg', '00000000000000000000000000000063.jpg', '00000000000000000000000000000064.jpg', '00000000000000000000000000000065.jpg', '00000000000000000000000000000066.jpg', '00000000000000000000000000000067.jpg', '00000000000000000000000000000068.jpg', '00000000000000000000000000000069.jpg', '00000000000000000000000000000070.jpg', '00000000000000000000000000000071.jpg', '00000000000000000000000000000072.jpg', '00000000000000000000000000000073.jpg', '00000000000000000000000000000074.jpg', '00000000000000000000000000000075.jpg', '00000000000000000000000000000076.jpg', '00000000000000000000000000000077.jpg', '00000000000000000000000000000078.jpg', '00000000000000000000000000000079.jpg', '00000000000000000000000000000080.jpg', '00000000000000000000000000000081.jpg', '00000000000000000000000000000082.jpg', '00000000000000000000000000000083.jpg', '00000000000000000000000000000084.jpg', '00000000000000000000000000000085.jpg', '00000000000000000000000000000086.jpg', '00000000000000000000000000000087.jpg', '00000000000000000000000000000088.jpg', '00000000000000000000000000000089.jpg', '00000000000000000000000000000090.jpg', '00000000000000000000000000000091.jpg', '00000000000000000000000000000092.jpg', '00000000000000000000000000000093.jpg', '00000000000000000000000000000094.jpg', '00000000000000000000000000000095.jpg', '00000000000000000000000000000096.jpg', '00000000000000000000000000000097.jpg', '00000000000000000000000000000098.jpg', '00000000000000000000000000000099.jpg', '00000000000000000000000000000100.jpg', '00000000000000000000000000000101.jpg', '00000000000000000000000000000102.jpg', '00000000000000000000000000000103.jpg', '00000000000000000000000000000104.jpg', '00000000000000000000000000000105.jpg', '00000000000000000000000000000106.jpg', '00000000000000000000000000000107.jpg', '00000000000000000000000000000108.jpg', '00000000000000000000000000000109.jpg', '00000000000000000000000000000110.jpg', '00000000000000000000000000000111.jpg', '00000000000000000000000000000112.jpg', '00000000000000000000000000000113.jpg', '00000000000000000000000000000114.jpg', '00000000000000000000000000000115.jpg', '00000000000000000000000000000116.jpg', '00000000000000000000000000000117.jpg', '00000000000000000000000000000118.jpg', '00000000000000000000000000000119.jpg', '00000000000000000000000000000120.jpg', '00000000000000000000000000000121.jpg', '00000000000000000000000000000122.jpg', '00000000000000000000000000000123.jpg', '00000000000000000000000000000124.jpg', '00000000000000000000000000000125.jpg', '00000000000000000000000000000126.jpg', '00000000000000000000000000000127.jpg', '00000000000000000000000000000128.jpg', '00000000000000000000000000000129.jpg', '00000000000000000000000000000130.jpg', '00000000000000000000000000000131.jpg', '00000000000000000000000000000132.jpg', '00000000000000000000000000000133.jpg', '00000000000000000000000000000134.jpg', '00000000000000000000000000000135.jpg', '00000000000000000000000000000136.jpg', '00000000000000000000000000000137.jpg', '00000000000000000000000000000138.jpg', '00000000000000000000000000000139.jpg', '00000000000000000000000000000140.jpg', '00000000000000000000000000000141.jpg', '00000000000000000000000000000142.jpg', '00000000000000000000000000000143.jpg', '00000000000000000000000000000144.jpg', '00000000000000000000000000000145.jpg', '00000000000000000000000000000146.jpg', '00000000000000000000000000000147.jpg', '00000000000000000000000000000148.jpg', '00000000000000000000000000000149.jpg', '00000000000000000000000000000150.jpg', '00000000000000000000000000000151.jpg', '00000000000000000000000000000152.jpg', '00000000000000000000000000000153.jpg', '00000000000000000000000000000154.jpg', '00000000000000000000000000000155.jpg', '00000000000000000000000000000156.jpg', '00000000000000000000000000000157.jpg', '00000000000000000000000000000158.jpg', '00000000000000000000000000000159.jpg', '00000000000000000000000000000160.jpg', '00000000000000000000000000000161.jpg', '00000000000000000000000000000162.jpg', '00000000000000000000000000000163.jpg', '00000000000000000000000000000164.jpg', '00000000000000000000000000000165.jpg', '00000000000000000000000000000166.jpg', '00000000000000000000000000000167.jpg', '00000000000000000000000000000168.jpg', '00000000000000000000000000000169.jpg', '00000000000000000000000000000170.jpg', '00000000000000000000000000000171.jpg', '00000000000000000000000000000172.jpg', '00000000000000000000000000000173.jpg', '00000000000000000000000000000174.jpg', '00000000000000000000000000000175.jpg', '00000000000000000000000000000176.jpg', '00000000000000000000000000000177.jpg', '00000000000000000000000000000178.jpg', '00000000000000000000000000000179.jpg', '00000000000000000000000000000180.jpg', '00000000000000000000000000000181.jpg', '00000000000000000000000000000182.jpg', '00000000000000000000000000000183.jpg', '00000000000000000000000000000184.jpg', '00000000000000000000000000000185.jpg', '00000000000000000000000000000186.jpg', '00000000000000000000000000000187.jpg', '00000000000000000000000000000188.jpg', '00000000000000000000000000000189.jpg', '00000000000000000000000000000190.jpg', '00000000000000000000000000000191.jpg', '00000000000000000000000000000192.jpg', '00000000000000000000000000000193.jpg', '00000000000000000000000000000194.jpg', '00000000000000000000000000000195.jpg', '00000000000000000000000000000196.jpg', '00000000000000000000000000000197.jpg', '00000000000000000000000000000198.jpg', '00000000000000000000000000000199.jpg', '00000000000000000000000000000200.jpg', '00000000000000000000000000000201.jpg', '00000000000000000000000000000202.jpg', '00000000000000000000000000000203.jpg', '00000000000000000000000000000204.jpg', '00000000000000000000000000000205.jpg', '00000000000000000000000000000206.jpg', '00000000000000000000000000000207.jpg', '00000000000000000000000000000208.jpg', '00000000000000000000000000000209.jpg', '00000000000000000000000000000210.jpg', '00000000000000000000000000000211.jpg', '00000000000000000000000000000212.jpg', '00000000000000000000000000000213.jpg', '00000000000000000000000000000214.jpg', '00000000000000000000000000000215.jpg', '00000000000000000000000000000216.jpg', '00000000000000000000000000000217.jpg', '00000000000000000000000000000218.jpg', '00000000000000000000000000000219.jpg', '00000000000000000000000000000220.jpg', '00000000000000000000000000000221.jpg', '00000000000000000000000000000222.jpg', '00000000000000000000000000000223.jpg', '00000000000000000000000000000224.jpg', '00000000000000000000000000000225.jpg', '00000000000000000000000000000226.jpg', '00000000000000000000000000000227.jpg', '00000000000000000000000000000228.jpg', '00000000000000000000000000000229.jpg', '00000000000000000000000000000230.jpg', '00000000000000000000000000000231.jpg', '00000000000000000000000000000232.jpg', '00000000000000000000000000000233.jpg', '00000000000000000000000000000234.jpg', '00000000000000000000000000000235.jpg', '00000000000000000000000000000236.jpg', '00000000000000000000000000000237.jpg', '00000000000000000000000000000238.jpg', '00000000000000000000000000000239.jpg', '00000000000000000000000000000240.jpg', '00000000000000000000000000000241.jpg', '00000000000000000000000000000242.jpg', '00000000000000000000000000000243.jpg', '00000000000000000000000000000244.jpg', '00000000000000000000000000000245.jpg', '00000000000000000000000000000246.jpg', '00000000000000000000000000000247.jpg', '00000000000000000000000000000248.jpg', '00000000000000000000000000000249.jpg', '00000000000000000000000000000250.jpg', '00000000000000000000000000000251.jpg', '00000000000000000000000000000252.jpg', '00000000000000000000000000000253.jpg', '00000000000000000000000000000254.jpg', '00000000000000000000000000000255.jpg', '00000000000000000000000000000256.jpg', '00000000000000000000000000000257.jpg', '00000000000000000000000000000258.jpg', '00000000000000000000000000000259.jpg', '00000000000000000000000000000260.jpg', '00000000000000000000000000000261.jpg', '00000000000000000000000000000262.jpg', '00000000000000000000000000000263.jpg', '00000000000000000000000000000264.jpg', '00000000000000000000000000000265.jpg', '00000000000000000000000000000266.jpg', '00000000000000000000000000000267.jpg', '00000000000000000000000000000268.jpg', '00000000000000000000000000000269.jpg', '00000000000000000000000000000270.jpg', '00000000000000000000000000000271.jpg', '00000000000000000000000000000272.jpg', '00000000000000000000000000000273.jpg', '00000000000000000000000000000274.jpg', '00000000000000000000000000000275.jpg', '00000000000000000000000000000276.jpg', '00000000000000000000000000000277.jpg', '00000000000000000000000000000278.jpg', '00000000000000000000000000000279.jpg', '00000000000000000000000000000280.jpg', '00000000000000000000000000000281.jpg', '00000000000000000000000000000282.jpg', '00000000000000000000000000000283.jpg', '00000000000000000000000000000284.jpg', '00000000000000000000000000000285.jpg', '00000000000000000000000000000286.jpg', '00000000000000000000000000000287.jpg', '00000000000000000000000000000288.jpg', '00000000000000000000000000000289.jpg', '00000000000000000000000000000290.jpg', '00000000000000000000000000000291.jpg', '00000000000000000000000000000292.jpg', '00000000000000000000000000000293.jpg', '00000000000000000000000000000294.jpg', '00000000000000000000000000000295.jpg', '00000000000000000000000000000296.jpg', '00000000000000000000000000000297.jpg', '00000000000000000000000000000298.jpg', '00000000000000000000000000000299.jpg', '00000000000000000000000000000300.jpg', '00000000000000000000000000000301.jpg', '00000000000000000000000000000302.jpg', '00000000000000000000000000000303.jpg', '00000000000000000000000000000304.jpg', '00000000000000000000000000000305.jpg', '00000000000000000000000000000306.jpg', '00000000000000000000000000000307.jpg', '00000000000000000000000000000308.jpg', '00000000000000000000000000000309.jpg', '00000000000000000000000000000310.jpg', '00000000000000000000000000000311.jpg', '00000000000000000000000000000312.jpg', '00000000000000000000000000000313.jpg', '00000000000000000000000000000314.jpg', '00000000000000000000000000000315.jpg', '00000000000000000000000000000316.jpg', '00000000000000000000000000000317.jpg', '00000000000000000000000000000318.jpg', '00000000000000000000000000000319.jpg', '00000000000000000000000000000320.jpg', '00000000000000000000000000000321.jpg', '00000000000000000000000000000322.jpg', '00000000000000000000000000000323.jpg', '00000000000000000000000000000324.jpg', '00000000000000000000000000000325.jpg', '00000000000000000000000000000326.jpg', '00000000000000000000000000000327.jpg', '00000000000000000000000000000328.jpg', '00000000000000000000000000000329.jpg', '00000000000000000000000000000330.jpg', '00000000000000000000000000000331.jpg', '00000000000000000000000000000332.jpg', '00000000000000000000000000000333.jpg', '00000000000000000000000000000334.jpg', '00000000000000000000000000000335.jpg', '00000000000000000000000000000336.jpg', '00000000000000000000000000000337.jpg', '00000000000000000000000000000338.jpg', '00000000000000000000000000000339.jpg', '00000000000000000000000000000340.jpg', '00000000000000000000000000000341.jpg', '00000000000000000000000000000342.jpg', '00000000000000000000000000000343.jpg', '00000000000000000000000000000344.jpg', '00000000000000000000000000000345.jpg', '00000000000000000000000000000346.jpg', '00000000000000000000000000000347.jpg', '00000000000000000000000000000348.jpg', '00000000000000000000000000000349.jpg', '00000000000000000000000000000350.jpg', '00000000000000000000000000000351.jpg', '00000000000000000000000000000352.jpg', '00000000000000000000000000000353.jpg', '00000000000000000000000000000354.jpg', '00000000000000000000000000000355.jpg', '00000000000000000000000000000356.jpg', '00000000000000000000000000000357.jpg', '00000000000000000000000000000358.jpg', '00000000000000000000000000000359.jpg', '00000000000000000000000000000360.jpg', '00000000000000000000000000000361.jpg', '00000000000000000000000000000362.jpg', '00000000000000000000000000000363.jpg', '00000000000000000000000000000364.jpg', '00000000000000000000000000000365.jpg', '00000000000000000000000000000366.jpg', '00000000000000000000000000000367.jpg', '00000000000000000000000000000368.jpg', '00000000000000000000000000000369.jpg', '00000000000000000000000000000370.jpg', '00000000000000000000000000000371.jpg', '00000000000000000000000000000372.jpg', '00000000000000000000000000000373.jpg', '00000000000000000000000000000374.jpg', '00000000000000000000000000000375.jpg', '00000000000000000000000000000376.jpg', '00000000000000000000000000000377.jpg', '00000000000000000000000000000378.jpg', '00000000000000000000000000000379.jpg', '00000000000000000000000000000380.jpg', '00000000000000000000000000000381.jpg', '00000000000000000000000000000382.jpg', '00000000000000000000000000000383.jpg', '00000000000000000000000000000384.jpg', '00000000000000000000000000000385.jpg', '00000000000000000000000000000386.jpg', '00000000000000000000000000000387.jpg', '00000000000000000000000000000388.jpg', '00000000000000000000000000000389.jpg', '00000000000000000000000000000390.jpg', '00000000000000000000000000000391.jpg', '00000000000000000000000000000392.jpg', '00000000000000000000000000000393.jpg', '00000000000000000000000000000394.jpg', '00000000000000000000000000000395.jpg', '00000000000000000000000000000396.jpg', '00000000000000000000000000000397.jpg', '00000000000000000000000000000398.jpg', '00000000000000000000000000000399.jpg', '00000000000000000000000000000400.jpg', '00000000000000000000000000000401.jpg', '00000000000000000000000000000402.jpg', '00000000000000000000000000000403.jpg', '00000000000000000000000000000404.jpg', '00000000000000000000000000000405.jpg', '00000000000000000000000000000406.jpg', '00000000000000000000000000000407.jpg', '00000000000000000000000000000408.jpg', '00000000000000000000000000000409.jpg', '00000000000000000000000000000410.jpg', '00000000000000000000000000000411.jpg', '00000000000000000000000000000412.jpg', '00000000000000000000000000000413.jpg', '00000000000000000000000000000414.jpg', '00000000000000000000000000000415.jpg', '00000000000000000000000000000416.jpg', '00000000000000000000000000000417.jpg', '00000000000000000000000000000418.jpg', '00000000000000000000000000000419.jpg', '00000000000000000000000000000420.jpg', '00000000000000000000000000000421.jpg', '00000000000000000000000000000422.jpg', '00000000000000000000000000000423.jpg', '00000000000000000000000000000424.jpg', '00000000000000000000000000000425.jpg', '00000000000000000000000000000426.jpg', '00000000000000000000000000000427.jpg', '00000000000000000000000000000428.jpg', '00000000000000000000000000000429.jpg', '00000000000000000000000000000430.jpg', '00000000000000000000000000000431.jpg', '00000000000000000000000000000432.jpg', '00000000000000000000000000000433.jpg', '00000000000000000000000000000434.jpg', '00000000000000000000000000000435.jpg', '00000000000000000000000000000436.jpg', '00000000000000000000000000000437.jpg', '00000000000000000000000000000438.jpg', '00000000000000000000000000000439.jpg', '00000000000000000000000000000440.jpg', '00000000000000000000000000000441.jpg', '00000000000000000000000000000442.jpg', '00000000000000000000000000000443.jpg', '00000000000000000000000000000444.jpg', '00000000000000000000000000000445.jpg', '00000000000000000000000000000446.jpg', '00000000000000000000000000000447.jpg', '00000000000000000000000000000448.jpg', '00000000000000000000000000000449.jpg', '00000000000000000000000000000450.jpg', '00000000000000000000000000000451.jpg', '00000000000000000000000000000452.jpg', '00000000000000000000000000000453.jpg', '00000000000000000000000000000454.jpg', '00000000000000000000000000000455.jpg', '00000000000000000000000000000456.jpg', '00000000000000000000000000000457.jpg', '00000000000000000000000000000458.jpg', '00000000000000000000000000000459.jpg', '00000000000000000000000000000460.jpg', '00000000000000000000000000000461.jpg', '00000000000000000000000000000462.jpg', '00000000000000000000000000000463.jpg', '00000000000000000000000000000464.jpg', '00000000000000000000000000000465.jpg', '00000000000000000000000000000466.jpg', '00000000000000000000000000000467.jpg', '00000000000000000000000000000468.jpg', '00000000000000000000000000000469.jpg', '00000000000000000000000000000470.jpg', '00000000000000000000000000000471.jpg', '00000000000000000000000000000472.jpg', '00000000000000000000000000000473.jpg', '00000000000000000000000000000474.jpg', '00000000000000000000000000000475.jpg', '00000000000000000000000000000476.jpg', '00000000000000000000000000000477.jpg', '00000000000000000000000000000478.jpg', '00000000000000000000000000000479.jpg', '00000000000000000000000000000480.jpg', '00000000000000000000000000000481.jpg', '00000000000000000000000000000482.jpg', '00000000000000000000000000000483.jpg', '00000000000000000000000000000484.jpg', '00000000000000000000000000000485.jpg', '00000000000000000000000000000486.jpg', '00000000000000000000000000000487.jpg', '00000000000000000000000000000488.jpg', '00000000000000000000000000000489.jpg', '00000000000000000000000000000490.jpg', '00000000000000000000000000000491.jpg', '00000000000000000000000000000492.jpg', '00000000000000000000000000000493.jpg', '00000000000000000000000000000494.jpg', '00000000000000000000000000000495.jpg', '00000000000000000000000000000496.jpg', '00000000000000000000000000000497.jpg', '00000000000000000000000000000498.jpg', '000000000000000000000000000004

In [50]:
fileName = pathToVideoFolder + '5th_small.mp4'
folder_name = '5th-small-pred-img'

In [51]:
print_time(maskWithShowVideo)

обработанные кадры сохранятся в папку C:/Users/Yura Sannikov/Учеба/НИР-диплом26/Папка с кодомм/исходные/imagesFolder/5th-small-pred-img . Если произошла ошибка, запустите makeVideo, чтобы собрать собранные кадры в видео
botsort

video 1/1 (frame 1/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 truck, 2 traffic lights, 37.1ms
File with lines not found :(. Please draw new ones
Starting: (836, 410), Ending: (1195, 372)
[(836, 410), (1195, 372)]
Starting: (671, 381), Ending: (957, 438)
[(671, 381), (957, 438)]
Starting: (264, 408), Ending: (71, 340)
[(264, 408), (71, 340)]
[]
Starting: (435, 382), Ending: (120, 437)
[(435, 382), (120, 437)]
Starting: (45, 555), Ending: (-2, 572)
[(45, 555), (-2, 572)]
Starting: (29, 510), Ending: (65, 615)
[(29, 510), (65, 615)]
Starting: (851, 560), Ending: (1637, 762)
[(851, 560), (1637, 762)]
Starting: (1038, 508), Ending: (516, 647)
[(1038, 508), (516, 647)]
counters
mid Counter({1: 1, 2: 1})
to_left Counter({3: 1, 5: 1, 6: 1, 7: 1})
to_right Counter()
to_top Counter()
to_bottom Counter()
sets
to_left {3, 5, 6, 7}
to_right set()
to_top set()
to_bottom set()
video 1/1 (frame 2/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 truck, 2 traffic lights, 67.6ms
video 1/1 (frame 3/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 truck, 2 traffic lights, 65.0ms
video 1/1 (frame 4/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 truck, 2 traffic lights, 16.7ms
video 1/1 (frame 5/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 truck, 2 traffic lights, 19.0ms
video 1/1 (frame 6/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 truck, 2 traffic lights, 15.8ms
video 1/1 (frame 7/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 truck, 2 traffic lights, 17.7ms
video 1/1 (frame 8/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 truck, 2 traffic lights, 17.3ms
video 1/1 (frame 9/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 19.6ms
video 1/1 (frame 10/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.6ms
video 1/1 (frame 11/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 17.4ms
video 1/1 (frame 12/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.6ms
video 1/1 (frame 13/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 21.0ms
video 1/1 (frame 14/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 15.6ms
video 1/1 (frame 15/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 15.5ms
video 1/1 (frame 16/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 15.8ms
video 1/1 (frame 17/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 20.0ms
video 1/1 (frame 18/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.0ms
video 1/1 (frame 19/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 24.4ms
video 1/1 (frame 20/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 19.7ms
video 1/1 (frame 21/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 18.6ms
video 1/1 (frame 22/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 19.3ms
video 1/1 (frame 23/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 21.2ms
video 1/1 (frame 24/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 2 traffic lights, 15.5ms
24
video 1/1 (frame 25/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 2 traffic lights, 17.7ms
video 1/1 (frame 26/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.9ms
video 1/1 (frame 27/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.0ms
video 1/1 (frame 28/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 27.2ms
video 1/1 (frame 29/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 16.0ms
video 1/1 (frame 30/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 15.2ms
video 1/1 (frame 31/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 15.1ms
video 1/1 (frame 32/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 26.8ms
video 1/1 (frame 33/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 26.3ms
video 1/1 (frame 34/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 18.9ms
video 1/1 (frame 35/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 15.6ms
video 1/1 (frame 36/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 16.0ms
video 1/1 (frame 37/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 19.4ms
video 1/1 (frame 38/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 15.4ms
video 1/1 (frame 39/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 16.3ms
video 1/1 (frame 40/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 16.0ms
video 1/1 (frame 41/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 18.4ms
video 1/1 (frame 42/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 25.2ms
video 1/1 (frame 43/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 23.9ms
video 1/1 (frame 44/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 14.8ms
video 1/1 (frame 45/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 18.1ms
video 1/1 (frame 46/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 25.7ms
video 1/1 (frame 47/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 30.3ms
video 1/1 (frame 48/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 19.6ms
48
video 1/1 (frame 49/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 15.3ms
video 1/1 (frame 50/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.8ms
video 1/1 (frame 51/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 20.7ms
counters
mid Counter({1: 1, 2: 1})
to_left Counter({3: 1, 5: 1, 6: 1, 7: 1, 10: 1, 15: 1})
to_right Counter()
to_top Counter()
to_bottom Counter()
sets
to_left {3, 5, 6, 7, 10, 15}
to_right set()
to_top set()
to_bottom set()
video 1/1 (frame 52/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 18.3ms
video 1/1 (frame 53/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 15.0ms
video 1/1 (frame 54/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 15.5ms
video 1/1 (frame 55/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 15.8ms
video 1/1 (frame 56/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 15.1ms
video 1/1 (frame 57/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 17.5ms
video 1/1 (frame 58/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 16.0ms
video 1/1 (frame 59/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 19.8ms
video 1/1 (frame 60/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 17.0ms
video 1/1 (frame 61/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 2 cars, 1 traffic light, 16.5ms
video 1/1 (frame 62/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 15.9ms
video 1/1 (frame 63/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 15.8ms
video 1/1 (frame 64/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 17.9ms
video 1/1 (frame 65/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 16.9ms
video 1/1 (frame 66/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 23.6ms
video 1/1 (frame 67/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 20.1ms
video 1/1 (frame 68/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 15.1ms
video 1/1 (frame 69/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 16.0ms
video 1/1 (frame 70/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 20.7ms
video 1/1 (frame 71/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 15.3ms
video 1/1 (frame 72/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 15.4ms
72
video 1/1 (frame 73/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 16.7ms
video 1/1 (frame 74/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 15.2ms
video 1/1 (frame 75/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 18.1ms
video 1/1 (frame 76/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 16.0ms
video 1/1 (frame 77/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 24.4ms
video 1/1 (frame 78/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 15.6ms
video 1/1 (frame 79/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 20.8ms
video 1/1 (frame 80/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 16.9ms
video 1/1 (frame 81/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 15.0ms
video 1/1 (frame 82/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 15.7ms
video 1/1 (frame 83/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 22.2ms
video 1/1 (frame 84/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 15.7ms
video 1/1 (frame 85/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 15.7ms
video 1/1 (frame 86/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 19.6ms
video 1/1 (frame 87/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 4 persons, 3 cars, 1 traffic light, 24.8ms
video 1/1 (frame 88/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 2 persons, 3 cars, 1 traffic light, 15.1ms
video 1/1 (frame 89/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 15.4ms
video 1/1 (frame 90/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 15.4ms
video 1/1 (frame 91/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 15.5ms
video 1/1 (frame 92/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 19.2ms
video 1/1 (frame 93/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 24.9ms
video 1/1 (frame 94/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 18.0ms
video 1/1 (frame 95/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 16.2ms
video 1/1 (frame 96/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 1 traffic light, 15.6ms
96
video 1/1 (frame 97/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 1 traffic light, 33.2ms
video 1/1 (frame 98/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.2ms
video 1/1 (frame 99/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.4ms
video 1/1 (frame 100/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 18.9ms
video 1/1 (frame 101/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.0ms
counters
mid Counter({1: 2, 2: 2, 22: 1})
to_left Counter({3: 2, 15: 2, 24: 2, 5: 1, 6: 1, 7: 1, 10: 1})
to_right Counter()
to_top Counter()
to_bottom Counter()
sets
to_left {3, 5, 6, 7, 10, 15, 24}
to_right set()
to_top set()
to_bottom set()
video 1/1 (frame 102/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 15.9ms
video 1/1 (frame 103/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 19.6ms
video 1/1 (frame 104/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 15.7ms
video 1/1 (frame 105/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 15.7ms
video 1/1 (frame 106/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 17.7ms
video 1/1 (frame 107/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.0ms
video 1/1 (frame 108/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.8ms
video 1/1 (frame 109/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.0ms
video 1/1 (frame 110/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.3ms
video 1/1 (frame 111/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.6ms
video 1/1 (frame 112/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.1ms
video 1/1 (frame 113/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.7ms
video 1/1 (frame 114/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.6ms
video 1/1 (frame 115/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.0ms
video 1/1 (frame 116/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 14.8ms
video 1/1 (frame 117/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 17.1ms
video 1/1 (frame 118/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.4ms
video 1/1 (frame 119/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 19.2ms
video 1/1 (frame 120/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.4ms
120
video 1/1 (frame 121/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 15.8ms
video 1/1 (frame 122/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 15.9ms
video 1/1 (frame 123/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 15.2ms
video 1/1 (frame 124/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.8ms
video 1/1 (frame 125/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 15.1ms
video 1/1 (frame 126/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 19.1ms
video 1/1 (frame 127/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.4ms
video 1/1 (frame 128/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 15.2ms
video 1/1 (frame 129/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 19.2ms
video 1/1 (frame 130/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.5ms
video 1/1 (frame 131/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.3ms
video 1/1 (frame 132/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.2ms
video 1/1 (frame 133/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 16.7ms
video 1/1 (frame 134/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.8ms
video 1/1 (frame 135/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.0ms
video 1/1 (frame 136/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.3ms
video 1/1 (frame 137/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.2ms
video 1/1 (frame 138/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 16.1ms
video 1/1 (frame 139/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 30.4ms
video 1/1 (frame 140/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 18.1ms
video 1/1 (frame 141/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 14.8ms
video 1/1 (frame 142/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 23.0ms
video 1/1 (frame 143/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.0ms
video 1/1 (frame 144/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 29.8ms
144
video 1/1 (frame 145/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 3 cars, 2 traffic lights, 15.9ms
video 1/1 (frame 146/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 15.7ms
video 1/1 (frame 147/1079) C:\Users\Yura Sannikov\\-26\  \\5th_small.mp4: 384x640 3 persons, 2 cars, 2 traffic lights, 19.9ms

# Получение данных для тренироки

In [97]:
# Анализ ситуации на дороге
def get_Y(df: pd.DataFrame):
  '''
    столбцы 
    'time_of_info' - время, когда получена информация
    'count_to...' - текущее количество автомобилей в направлении ...
    'count_stuck_middle' - текущее количесство автомобилей, застрявших посреди перекрестка
    'count_stuck_to...' - текущее количесство автомобилей, застрявших в направлении ...
    'is_jam_next...' - наличие пробки у следующего перекрестка по направлению ...
    *застрявших означает что объект находится в области больше одной итерации.*
    'is_green_horizontal' - В данный момент горит зеленый для горизонтальных направлений
    'is_green_vertical' - В данный момент горит зеленый для вертикальных направлений
    'y' - направление которому необходимо дать зеленый сигнал 
  '''
  # делаем копию датасета
  df_c = df.copy()
  # Если центр перекрестка заблокирован — красный для всех
  stuckMiddleCondition = df['count_stuck_middle'] > 0
  df_c['cars_count'] = df[['count_to_r', 'count_to_l', 'count_to_b', 'count_to_t']].sum(axis=1)
  
  # Считаем Полезности включенного сигнала для каждого из направлений
  # доля от всех машин в каждом направлении + 
  #  + Количество машин которые стоят несколько фаз в каждом из направлений
  # (Для таких машин приоритет выше)

  # В случае, если по направлению вправо нету пробки
  df_c['utility_r'] = np.where(df_c['is_jam_next_r'] == 0,
                             (df_c['count_to_r'] / df_c['cars_count']) + df_c['count_stuck_to_r']
                             , 0)
  df_c['utility_l'] = np.where(df_c['is_jam_next_l'] == 0,
                             (df_c['count_to_l'] / df_c['cars_count']) + df_c['count_stuck_to_l']
                             , 0)
  df_c['utility_t'] = np.where(df_c['is_jam_next_t'] == 0,
                             (df_c['count_to_t'] / df_c['cars_count']) + df_c['count_stuck_to_t']
                             , 0)
  df_c['utility_b'] = np.where(df_c['is_jam_next_b'] == 0,
                             (df_c['count_to_b'] / df_c['cars_count']) + df_c['count_stuck_to_b']
                             , 0)
  
  # print(df_c.head())
  # решаем на основе полезности фаз с учётом пробок на следующих светофорах, какому направлению давать сигнал
  utilityComaprison = (df_c['utility_r'] + df_c['utility_l']) > (df_c['utility_t'] + df_c['utility_b'])

  conditions = [
    (stuckMiddleCondition == True),
    (utilityComaprison == True),
    (utilityComaprison != True)
  ]
  # choices = [DirectionOfGreen.NONE, DirectionOfGreen.HORIZONTAL, DirectionOfGreen.VERTICAL]
  choices = [0, 2, 1]
  # temp_series = np.select(conditions, choices, default=0)
  # return pd.Series(temp_series).map({0: DirectionOfGreen.NONE, 2: DirectionOfGreen.HORIZONTAL, 1:DirectionOfGreen.VERTICAL})
  return np.select(conditions, choices, default=0)

In [165]:
# проверка
path_to_csv = pathToVideoFolder + 'imagesFolder/4th-small-img/json_lines/2_collected_info.csv'

# Чтение файла
df_data = pd.read_csv(path_to_csv)

# Вывод первых 5 строк на экран
print(df_data.head())

   time_of_info  count_to_r  count_to_l  count_to_b  count_to_t  \
0             0           1           9           1           0
1            50           1           9           1           0
2           100           1           9           1           0
3           150           1           9           1           0
4           200           1           9           2           0

   count_stuck_middle  count_stuck_to_r  count_stuck_to_l  count_stuck_to_b  \
0                   0                 0                 0                 0
1                   0                 0                 0                 0
2                   0                 0                 0                 0
3                   0                 0                 0                 0
4                   0                 1                 8                 1

   count_stuck_to_t  is_jam_next_l  is_jam_next_r  is_jam_next_t  \
0                 0              0              0              1
1                 0              0              1              0
2                 0              0              0              1
3                 0              0              1              1
4                 0              0              1              1

   is_jam_next_b  is_green_horizontal  is_green_vertical  y
0              0                    1                  0  1
1              1                    0                  1  1
2              1                    0                  1  1
3              1                    0                  1  1
4              1                    1                  0  1

In [166]:
df_data_copy = df_data.copy()

In [167]:
classV2 = VideoConverterClassV2()
classV2.columns

['time_of_info',
 'count_to_r',
 'count_to_l',
 'count_to_b',
 'count_to_t',
 'count_stuck_middle',
 'count_stuck_to_r',
 'count_stuck_to_l',
 'count_stuck_to_b',
 'count_stuck_to_t',
 'is_jam_next_l',
 'is_jam_next_r',
 'is_jam_next_t',
 'is_jam_next_b',
 'is_green_horizontal',
 'is_green_vertical',
 'y']

In [ ]:
def concatMultipleData(df, paths):
    df_data_copy = df.copy()
    for path_to_csv in paths:
        # Чтение файла
        df_data = pd.read_csv(path_to_csv)
        df_data = df_data[classV2.columns]
        # Вывод первых 5 строк на экран
        df_data_copy = pd.concat([df_data_copy, df_data], ignore_index=True)
    return df_data_copy

In [169]:
paths_to_csv = [pathToVideoFolder + 'imagesFolder/4th-small-img/json_lines/2_collected_info.csv',
                'runInfo_v200_g30_default.csv',
                'runInfo_v200_g30_predict.csv',
                'runInfo_v200_g42_default.csv',
                'runInfo_v300_g20_default.csv',
                'runInfo_v300_g30_default.csv',
                'runInfo_v300_g42_default.csv',
                'runInfo_v400_g20_default.csv',
                'runInfo_v400_g30_default.csv',
                'runInfo_v400_g42_default.csv',
                ]
df_data_copy = concatMultipleData(df_data_copy, paths_to_csv)
print(df_data_copy.info())

<class 'pandas.DataFrame'>
RangeIndex: 27392 entries, 0 to 27391
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time_of_info         27392 non-null  int64
 1   count_to_r           27392 non-null  int64
 2   count_to_l           27392 non-null  int64
 3   count_to_b           27392 non-null  int64
 4   count_to_t           27392 non-null  int64
 5   count_stuck_middle   27392 non-null  int64
 6   count_stuck_to_r     27392 non-null  int64
 7   count_stuck_to_l     27392 non-null  int64
 8   count_stuck_to_b     27392 non-null  int64
 9   count_stuck_to_t     27392 non-null  int64
 10  is_jam_next_l        27392 non-null  int64
 11  is_jam_next_r        27392 non-null  int64
 12  is_jam_next_t        27392 non-null  int64
 13  is_jam_next_b        27392 non-null  int64
 14  is_green_horizontal  27392 non-null  int64
 15  is_green_vertical    27392 non-null  int64
 16  y                    27392 non-null  int64
dtypes: int64(17)
memory usage: 3.6 MB
None

In [170]:
from tqdm import tqdm

n = 1000
for i in tqdm(range(30000)):
    n += i*50
    x2 = i % 200 == 0
    info_collected = {'time_of_info': i,
                    'count_to_r': random.randint(0, 20),
                    'count_to_l': random.randint(0, 20),
                    'count_to_b': random.randint(0, 20),
                    'count_to_t': random.randint(0, 20),
                    'count_stuck_middle': random.randint(0, 20) if n % 500 else 0,
                    'count_stuck_to_r': random.randint(0, 20),
                    'count_stuck_to_l': random.randint(0, 20),
                    'count_stuck_to_b': random.randint(0, 20),
                    'count_stuck_to_t': random.randint(0, 20),
                    'is_jam_next_l': random.randint(0, 1),
                    'is_jam_next_r': random.randint(0, 1),
                    'is_jam_next_t': random.randint(0, 1),
                    'is_jam_next_b': random.randint(0, 1),
                    'is_green_horizontal': 1 if x2 else 0,
                    'is_green_vertical': 0 if x2 else 1,
                    'y': 1,
          }
    dfInfo = pd.DataFrame(info_collected, index=[0])
    df_data_copy = pd.concat([df_data_copy, dfInfo], ignore_index=True)

for i in tqdm(range(10000)):
    n += i*50
    x2 = i % 200 == 0
    info_collected = {'time_of_info': i,
                    'count_to_r': random.randint(0, 20),
                    'count_to_l': random.randint(0, 20),
                    'count_to_b': random.randint(0, 20),
                    'count_to_t': random.randint(0, 20),
                    'count_stuck_middle': random.randint(0, 20) if n % 100 else 0,
                    'count_stuck_to_r': random.randint(0, 1),
                    'count_stuck_to_l': random.randint(0, 1),
                    'count_stuck_to_b': random.randint(0, 1),
                    'count_stuck_to_t': random.randint(0, 1),
                    'is_jam_next_l': random.randint(0, 1),
                    'is_jam_next_r': random.randint(0, 1),
                    'is_jam_next_t': random.randint(0, 1),
                    'is_jam_next_b': random.randint(0, 1),
                    'is_green_horizontal': 1 if x2 else 0,
                    'is_green_vertical': 0 if x2 else 1,
                    'y': 1,
          }
    dfInfo = pd.DataFrame(info_collected, index=[0])
    df_data_copy = pd.concat([df_data_copy, dfInfo], ignore_index=True)

100%|██████████| 30000/30000 [00:24<00:00, 1225.16it/s]
100%|██████████| 10000/10000 [00:11<00:00, 861.55it/s]

In [171]:
# для is_green_horizontal=0 и is_green_vertical = 0
for i in tqdm(range(1000)):
    n += i*50
    x2 = i % 200 == 0
    info_collected = {'time_of_info': i,
                    'count_to_r': random.randint(0, 20),
                    'count_to_l': random.randint(0, 20),
                    'count_to_b': random.randint(0, 20),
                    'count_to_t': random.randint(0, 20),
                    'count_stuck_middle': random.randint(0, 20) if n % 100 else 0,
                    'count_stuck_to_r': random.randint(0, 20),
                    'count_stuck_to_l': random.randint(0, 20),
                    'count_stuck_to_b': random.randint(0, 20),
                    'count_stuck_to_t': random.randint(0, 20),
                    'is_jam_next_l': random.randint(0, 1),
                    'is_jam_next_r': random.randint(0, 1),
                    'is_jam_next_t': random.randint(0, 1),
                    'is_jam_next_b': random.randint(0, 1),
                    'is_green_horizontal':  0,
                    'is_green_vertical': 0,
                    'y': 1,
          }
    dfInfo = pd.DataFrame(info_collected, index=[0])
    df_data_copy = pd.concat([df_data_copy, dfInfo], ignore_index=True)

100%|██████████| 1000/1000 [00:01<00:00, 804.17it/s]

In [172]:
print(df_data_copy.info())

<class 'pandas.DataFrame'>
RangeIndex: 68392 entries, 0 to 68391
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   time_of_info         68392 non-null  int64
 1   count_to_r           68392 non-null  int64
 2   count_to_l           68392 non-null  int64
 3   count_to_b           68392 non-null  int64
 4   count_to_t           68392 non-null  int64
 5   count_stuck_middle   68392 non-null  int64
 6   count_stuck_to_r     68392 non-null  int64
 7   count_stuck_to_l     68392 non-null  int64
 8   count_stuck_to_b     68392 non-null  int64
 9   count_stuck_to_t     68392 non-null  int64
 10  is_jam_next_l        68392 non-null  int64
 11  is_jam_next_r        68392 non-null  int64
 12  is_jam_next_t        68392 non-null  int64
 13  is_jam_next_b        68392 non-null  int64
 14  is_green_horizontal  68392 non-null  int64
 15  is_green_vertical    68392 non-null  int64
 16  y                    68392 non-null  int64
dtypes: int64(17)
memory usage: 8.9 MB
None

In [173]:
df_data_copy['y'] = get_Y(df_data_copy)

In [174]:
df_data_copy.to_csv('bigData.csv', index=False)

In [65]:
print(df_data.columns)

Index(['time_of_info', 'count_to_r', 'count_to_l', 'count_to_b', 'count_to_t',
       'count_stuck_middle', 'count_stuck_to_r', 'count_stuck_to_l',
       'count_stuck_to_b', 'count_stuck_to_t', 'is_jam_next_l',
       'is_jam_next_r', 'is_jam_next_t', 'is_jam_next_b',
       'is_green_horizontal', 'is_green_vertical', 'y'],
      dtype='str')

In [176]:
df_data['y'] = get_Y(df_data)

In [177]:
df_data['y']

0     2
1     2
2     2
3     2
4     2
5     2
6     2
7     1
8     2
9     2
10    1
11    1
12    1
13    1
14    0
15    1
16    0
17    0
18    0
19    0
20    0
Name: y, dtype: int64

In [178]:
df_data['y']

0     2
1     2
2     2
3     2
4     2
5     2
6     2
7     1
8     2
9     2
10    1
11    1
12    1
13    1
14    0
15    1
16    0
17    0
18    0
19    0
20    0
Name: y, dtype: int64

In [110]:
classV2 = VideoConverterClassV2()

In [179]:

# Признаки
classV2.columns
feature_cols = classV2.columns[1:-1]

X = df_data_copy[feature_cols]
y = df_data_copy['y']  # 0, 1, 2

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

model = CatBoostClassifier(
    iterations=500,
    depth=6,
    learning_rate=0.1,
    loss_function='MultiClass',
    eval_metric='Accuracy',
    verbose=50,
    cat_features=['is_jam_next_t', 'is_jam_next_b', 'is_jam_next_l', 'is_jam_next_r']  # можно и как числовые
)

model.fit(X_train, y_train, eval_set=(X_test, y_test))

# Предсказание
pred = model.predict(X_test)
print(classification_report(y_test, pred))

0:	learn: 0.8871201	test: 0.8865414	best: 0.8865414 (0)	total: 6.79ms	remaining: 3.39s
50:	learn: 0.9745216	test: 0.9731706	best: 0.9731706 (50)	total: 265ms	remaining: 2.33s
100:	learn: 0.9849579	test: 0.9835514	best: 0.9835514 (100)	total: 535ms	remaining: 2.11s
150:	learn: 0.9895820	test: 0.9868411	best: 0.9870605 (144)	total: 807ms	remaining: 1.86s
200:	learn: 0.9922687	test: 0.9898384	best: 0.9902040 (198)	total: 1.08s	remaining: 1.61s
250:	learn: 0.9941330	test: 0.9912274	best: 0.9915198 (240)	total: 1.35s	remaining: 1.34s
300:	learn: 0.9953759	test: 0.9921047	best: 0.9922509 (289)	total: 1.58s	remaining: 1.04s
350:	learn: 0.9964725	test: 0.9926164	best: 0.9929088 (340)	total: 1.81s	remaining: 769ms
400:	learn: 0.9971305	test: 0.9930550	best: 0.9932013 (380)	total: 2.05s	remaining: 506ms
450:	learn: 0.9973498	test: 0.9929819	best: 0.9933475 (426)	total: 2.28s	remaining: 247ms
499:	learn: 0.9977519	test: 0.9934206	best: 0.9934206 (499)	total: 2.5s	remaining: 0us

bestTest = 0.9934205717
bestIteration = 499

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      5603
           1       0.99      0.99      0.99      4283
           2       0.99      0.99      0.99      3793

    accuracy                           0.99     13679
   macro avg       0.99      0.99      0.99     13679
weighted avg       0.99      0.99      0.99     13679

In [182]:
info_collected = {'time_of_info': 6000,
                    'count_to_r': 9,
                    'count_to_l': 0,
                    'count_to_b': 1,
                    'count_to_t': 1,
                    'count_stuck_middle': 0,
                    'count_stuck_to_r': 0,
                    'count_stuck_to_l': 0,
                    'count_stuck_to_b': 0,
                    'count_stuck_to_t': 0,
                    'is_jam_next_l': 0,
                    'is_jam_next_r': 0,
                    'is_jam_next_t': 0,
                    'is_jam_next_b': 0,
                    'is_green_horizontal':  0,
                    'is_green_vertical': 1,
                    'y': 2,
          }
dfInfo_singula = pd.DataFrame(info_collected, index=[0])

In [185]:
dfInfo_singula['y'] = get_Y(dfInfo_singula)

In [186]:
dfInfo_singula

,time_of_info,count_to_r,count_to_l,count_to_b,count_to_t,count_stuck_middle,count_stuck_to_r,count_stuck_to_l,count_stuck_to_b,count_stuck_to_t,is_jam_next_l,is_jam_next_r,is_jam_next_t,is_jam_next_b,is_green_horizontal,is_green_vertical,y
0,6000,9,0,1,1,0,0,0,0,0,0,0,0,0,0,1,2

In [184]:
# Предсказание
pred = model.predict(dfInfo_singula[feature_cols])
print(pred)

[[2]]

In [180]:
X_test

,count_to_r,count_to_l,count_to_b,count_to_t,count_stuck_middle,count_stuck_to_r,count_stuck_to_l,count_stuck_to_b,count_stuck_to_t,is_jam_next_l,is_jam_next_r,is_jam_next_t,is_jam_next_b,is_green_horizontal,is_green_vertical
46876,1,3,14,0,0,20,16,2,0,1,0,0,0,0,1
26225,1,0,2,9,0,0,0,0,0,0,0,0,0,0,1
32964,17,7,8,1,17,8,12,6,4,1,1,0,1,0,1
31656,18,6,2,4,0,20,3,16,7,1,1,0,0,0,1
45190,4,8,9,3,6,15,17,4,16,1,0,0,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18309,2,1,1,1,0,0,0,0,0,0,0,0,0,1,0
10130,1,0,2,4,0,0,0,0,0,0,0,0,0,1,0
47364,15,19,15,2,18,0,2,14,7,1,1,1,1,0,1
21242,1,14,0,1,0,0,0,0,0,0,0,0,0,0,1
10887,1,10,0,2,0,0,0,0,0,0,0,0,0,1,0

In [181]:
model.save_model("catboost_model_v2.cbm")

In [189]:
!pip install seaborn

Collecting seaborn
  Downloading seaborn-0.13.2-py3-none-any.whl.metadata (5.4 kB)
Requirement already satisfied: numpy!=1.24.0,>=1.20 in .\git\.venv\Lib\site-packages (from seaborn) (2.4.4)
Requirement already satisfied: pandas>=1.2 in .\git\.venv\Lib\site-packages (from seaborn) (3.0.2)
Requirement already satisfied: matplotlib!=3.6.1,>=3.4 in .\git\.venv\Lib\site-packages (from seaborn) (3.11.0)
Requirement already satisfied: contourpy>=1.0.1 in .\git\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.3.3)
Requirement already satisfied: cycler>=0.10 in .\git\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in .\git\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in .\git\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (1.5.0)
Requirement already satisfied: packaging>=20.0 in .\git\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (26.1)
Requirement already satisfied: pillow>=9 in .\git\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (12.2.0)
Requirement already satisfied: pyparsing>=3 in .\git\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in .\git\.venv\Lib\site-packages (from matplotlib!=3.6.1,>=3.4->seaborn) (2.9.0.post0)
Requirement already satisfied: tzdata in .\git\.venv\Lib\site-packages (from pandas>=1.2->seaborn) (2026.1)
Requirement already satisfied: six>=1.5 in .\git\.venv\Lib\site-packages (from python-dateutil>=2.7->matplotlib!=3.6.1,>=3.4->seaborn) (1.17.0)
Downloading seaborn-0.13.2-py3-none-any.whl (294 kB)
Installing collected packages: seaborn
Successfully installed seaborn-0.13.2

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
import seaborn as sns

# значения важности признаков
importances = model.get_feature_importance()

feature_importance_df = pd.DataFrame({
    'Feature': X_train.columns,
    'Importance': importances
})

#  от самых важных к менее важным
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)
print(feature_importance_df.head(len(feature_cols)))

# Визуализация
plt.figure(figsize=(10, 6))
ax = sns.barplot(x="Importance", y="Feature", data=feature_importance_df.head(len(feature_cols)))
plt.title('Самые важные признаки')
plt.xlabel('Важность')
plt.ylabel('Признак')

# Добавление подписей значений (аналог bar_label)
ax.bar_label(ax.containers[0], fmt='%.4f', fontsize=9, padding=3)

plt.show()

                Feature  Importance
4    count_stuck_middle   54.388210
0            count_to_r    6.904446
1            count_to_l    6.854122
3            count_to_t    6.250886
2            count_to_b    6.204896
10        is_jam_next_r    3.266381
9         is_jam_next_l    3.254365
5      count_stuck_to_r    2.356050
6      count_stuck_to_l    2.350694
7      count_stuck_to_b    2.140813
12        is_jam_next_b    1.963485
11        is_jam_next_t    1.957789
8      count_stuck_to_t    1.932051
13  is_green_horizontal    0.133442
14    is_green_vertical    0.042370

# Конвертер видео в изображения

In [ ]:
import os
import cv2

def video_to_images(video_path, output_folder="extracted_frames"):
    if not os.path.exists(output_folder):
        os.makedirs(output_folder)
    else:
        fileList = glob(output_folder+'/*')
        print("Number of files: ",len(fileList))
        for filePath in fileList:
            try:
                os.remove(filePath)
            except:
                print("Error while deleting file : ", filePath)
    # Initialize video capture object
    cap = cv2.VideoCapture(video_path)

    # Check if video opened successfully
    if not cap.isOpened():
        print(f"Error: Could not open video file {video_path}")
        return

    frame_count = 0

    while True:
        
        # Read the next frame from the video
        ret, frame = cap.read()

        # Break the loop if there are no more frames to read
        if not ret:
            break
        # записываем только half frames
        if frame_count % 2 == 0:
            # Generate a zero-padded filename (e.g., frame_0000.jpg)
            file_name = f"frame_{frame_count:04d}.jpg"
            file_path = os.path.join(output_folder, file_name)

            # Save the current frame as an image
            cv2.imwrite(file_path, frame)
            if (frame_count % 100 ==0):
                print(frame_count)

        frame_count += 1

    # Release resources
    cap.release()
    print(f"Done! Successfully extracted {frame_count} frames.")

In [ ]:
# video_path = 'C:/Users/Yura Sannikov/Videos/2026-05-31 18-26-27.mp4'
# video_to_images(video_path=video_path)

Number of files:  0
0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
Done! Successfully extracted 9544 frames.